### ISSUE TITLE
Cannot connect to the MHCstab server

### ISSUE THREAD

**Issue by Histidine127** [griffithlab/pVACtools#1027]
### Installation Type

Standalone

### pVACtools Version / Docker Image

latest edition

### Python Version

3.8

### Operating System

Linux

### Describe the bug

Prompt MHCstab connection reset while running pVACseq. Looks like there's something wrong with their server. Hope to get a new connection address.

### How to reproduce this bug

```Shell
#!/bin/bash -ue
pvacseq run \
    --iedb-install-directory /data2/neoantigen/resources/databases/iedb \
    -t 50 \
    -p sample1_vep_phased.vcf.gz \
    -e1 8,9,10,11 \
    -e2 15,16,17,18,19,20,21,22,23,24,25 \
    --normal-sample-name sample1_normal \
    --tumor-purity 0.51 \
     \
    --netmhc-stab \
    --binding-threshold 500 --top-score-metric median --minimum-fold-change 0.0 --normal-cov 5 --tdna-cov 10 --trna-cov 10 --normal-vaf 0.02 --tdna-vaf 0.25 --trna-vaf 0.25 --expn-val 1 --maximum-transcript-support-level 1 \
    sample1_hc_vep_pick.vcf.gz sample1_tumor HLA-A*24:02 NetMHCpan NetMHCIIpan ./

if [ -e ./MHC_Class_I/sample1_tumor.filtered.tsv ]; then
    mv ./MHC_Class_I/sample1_tumor.filtered.tsv ./MHC_Class_I/sample1_tumor_HLA-A*24:02.filtered.tsv
fi
if [ -e ./MHC_Class_I/sample1_tumor.all_epitopes.tsv ]; then
    mv ./MHC_Class_I/sample1_tumor.all_epitopes.tsv ./MHC_Class_I/sample1_tumor_HLA-A*24:02.all_epitopes.tsv
fi
if [ -e ./MHC_Class_II/sample1_tumor.filtered.tsv ]; then
    mv ./MHC_Class_II/sample1_tumor.filtered.tsv ./MHC_Class_II/sample1_tumor_HLA-A*24:02.filtered.tsv
fi
if [ -e ./MHC_Class_II/sample1_tumor.all_epitopes.tsv ]; then
    mv ./MHC_Class_II/sample1_tumor.all_epitopes.tsv ./MHC_Class_II/sample1_tumor_HLA-A*24:02.all_epitopes.tsv
fi
```

### Log output

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/conda/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/conda/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/conda/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/conda/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/opt/conda/lib/python3.8/site-packages/pvactools/tools/pvacseq/run.py", line 138, in main
    pipeline.execute()
  File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 484, in execute
    PostProcessor(**post_processing_params).execute()
  File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/post_processor.py", line 64, in execute
    self.call_netmhc_stab()
  File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/post_processor.py", line 225, in call_netmhc_stab
    NetMHCStab(self.net_chop_fh.name, self.netmhc_stab_fh.name, self.file_type, self.top_score_metric).execute()
  File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/netmhc_stab.py", line 37, in execute
    alleles = self.valid_alleles(list(set(observed_alleles).intersection(set(mhci_alleles))))
  File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/netmhc_stab.py", line 195, in valid_alleles
    response = self.query_netmhcstabpan_server(staging_file, 9, allele.replace("*", ""))
  File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/netmhc_stab.py", line 152, in query_netmhcstabpan_server
    response = requests.post(
  File "/opt/conda/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by susannasiebert** [comment]
@Histidine127, as far as I can tell, the NetMHCstabpan server is up and running. Can you please try again and let me know if the problem persists?

**Comment by susannasiebert** [comment]
Closing this issue due to inactivity.
