### ISSUE TITLE
Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.

### ISSUE THREAD

**Issue by ShixiangWang** [griffithlab/pVACtools#103]
Error info:

```
Combining Parsed IEDB Output Files
Completed
Running Binding Filters
Completed
Running Top Score Filter
Submitting remaining epitopes to NetChop
Waiting for results from NetChop... |/public/home/liuxs/anaconda3/lib/python3.6/site-packages/lib/pipeline.py:347: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  self.binding_filter()
Traceback (most recent call last):
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/public/home/liuxs/anaconda3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/public/home/liuxs/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/public/home/liuxs/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/public/home/liuxs/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/public/home/liuxs/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/public/home/liuxs/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2b01349edc88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.cbs.dtu.dk', port=80): Max retries exceeded with url: /cgi-bin/webface2.fcgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b01349edc88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuxs/anaconda3/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/tools/pvacseq/run.py", line 126, in main
    pipeline.execute()
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/lib/pipeline.py", line 370, in execute
    self.net_chop()
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/lib/pipeline.py", line 309, in net_chop
    str(self.net_chop_threshold)
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/lib/net_chop.py", line 82, in main
    'thresh':'%0f'%args.threshold
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/public/home/liuxs/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.cbs.dtu.dk', port=80): Max retries exceeded with url: /cgi-bin/webface2.fcgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b01349edc88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

```

Example data download from `pvacseq`  can  run successfully. But when I try testing my own data, `NetChop` give errors.

I use commands,

```
# run pvacseq for test neoantigens
pvacseq run \
~/wangshx/projects/tests/test_new.vcf \
Test_neoantigen \
HLA-A*01:01,HLA-A*02:01,HLA-A*02:02,HLA-A*02:03,HLA-A*02:06,HLA-A*02:11,HLA-A*02:12 \
NetMHC output_dir_neoantigen_allHLA \
-e 9 \
--net-chop-method cterm --netmhc-stab \
-m median -t -a sample_name \
--iedb-install-directory ~/wangshx/projects/biotools/
```

Is something wrong in these options? Or the data submitted to NetChop Server is limited, thus I can not get the results?

**Comment by susannasiebert** [comment]
It looks like pVACseq wasn't able to establish an internet connection. Please make sure that you are connected to the internet while running pVACseq with netmhcstab and/or netchop. If you aren't able to be on the internet while running pVACseq you can skip the netmhcstab and netchop steps by removing the `--net-chop-method cterm --netmhc-stab` flags.

**Comment by ShixiangWang** [comment]
thanks.

发自我的 iPhone

在 2018年4月2日，下午10:01，Susanna Kiwala <notifications@github.com<mailto:notifications@github.com>> 写道：


It looks like pVACseq wasn't able to establish an internet connection. Please make sure that you are connected to the internet while running pVACseq with netmhcstab and/or netchop. If you aren't able to be on the internet while running pVACseq you can skip the netmhcstab and netchop steps by removing the --net-chop-method cterm --netmhc-stab flags.

―
