### ISSUE TITLE
[Bug report title] WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output

### ISSUE THREAD

**Issue by PierreLaplante** [griffithlab/pVACtools#1043]
### Installation Type

Docker

### pVACtools Version / Docker Image

4.0.6

### Python Version

3.11.0

### Operating System

CentOs 7 HPC

### Describe the bug

The pipeline stops at the prediction step H-2-Dd, Kd and Ld using NetMHCpan with mouse data: 

```
Split FASTA file for Epitope Length 9 - Entries 11801-11986 already exists. Skipping.
Split FASTA file for Epitope Length 10 - Entries 11801-11986 already exists. Skipping.
Split FASTA file for Epitope Length 11 - Entries 11801-11986 already exists. Skipping.
Completed
Making binding predictions on Allele H-2-Dd and Epitope Length 8 with Method NetMHCpan - File /mnt/pvac_files/pvac_output/6_2_Msh2KO_g/MHC_Class_I/tmp/6_2_Msh2KO_g.netmhcpan.H-2-Dd.8.tsv_1-200
2024-01-05:17:59:27,871 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:27,888 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:27,903 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:27,919 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:27,934 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:27,950 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:27,966 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:27,983 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,1 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,17 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,34 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,50 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,66 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,83 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,99 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,115 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,132 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,148 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,164 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,180 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,196 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,212 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,229 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,245 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,262 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,278 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,294 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,310 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,327 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,344 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,360 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,377 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,393 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,409 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,425 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,442 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,458 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,475 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,491 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,507 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,524 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,540 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,557 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,574 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,592 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,610 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,628 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,646 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,664 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,682 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,701 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,719 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,737 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,756 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,774 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,793 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,811 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,830 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,848 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,866 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,885 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,903 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,921 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,940 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,958 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,977 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:28,995 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,14 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,32 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,51 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,69 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,88 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,106 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,124 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,147 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,166 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,185 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,203 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,222 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,240 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,259 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,277 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,295 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,314 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,332 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,351 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,369 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,388 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,407 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,427 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,445 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,464 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,482 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,501 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,519 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
2024-01-05:17:59:29,538 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
Traceback (most recent call last):
  File "/opt/iedb/mhc_i/src/predict_binding.py", line 516, in <module>
    Prediction().main()
  File "/opt/iedb/mhc_i/src/predict_binding.py", line 507, in main
    self.commandline_input(args)
  File "/opt/iedb/mhc_i/src/predict_binding.py", line 134, in commandline_input
    table_rows = self.format_binding(input, mhc_scores, method, use_cutoff, cutoff_value)
  File "/opt/iedb/mhc_i/src/predict_binding.py", line 206, in format_binding
    self.add_rows_binding(allele, length, proteins, score, actual_methods_used, cutoff, value)
  File "/opt/iedb/mhc_i/src/predict_binding.py", line 211, in add_rows_binding
    for (k, prediction) in enumerate(predictions):
TypeError: 'NoneType' object is not iterable
CRITICAL:pymp:An exception occured in thread 0: (<class 'subprocess.CalledProcessError'>, Command '['/usr/local/bin/python', '/opt/iedb/mhc_i/src/predict_binding.py', 'netmhcpan', 'H-2-Dd', '8', '/mnt/pvac_files/pvac_output/6_2_Msh2KO_g/MHC_Class_I/tmp/6_2_Msh2KO_g.8.fa.split_1-200']' returned non-zero exit status 1.).
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 356, in call_iedb
    pvactools.lib.call_iedb.main(arguments)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/call_iedb.py", line 44, in main
    raise err
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/call_iedb.py", line 39, in main
    (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries, tmp_dir=args.tmp_dir)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/prediction_class.py", line 58, in predict
    response = run(arguments, stdout=response_fh, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '/opt/iedb/mhc_i/src/predict_binding.py', 'netmhcpan', 'H-2-Dd', '8', '/mnt/pvac_files/pvac_output/6_2_Msh2KO_g/MHC_Class_I/tmp/6_2_Msh2KO_g.8.fa.split_1-200']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/run.py", line 138, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 450, in execute
    self.call_iedb(chunks)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 357, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/usr/local/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: __init__() missing 1 required positional argument: 'cmd'
```
This error **doesn't happen** with NetMHC.
Let me know if you need my input files.

### How to reproduce this bug

```Shell
singularity exec \
	--mount type=bind,src=SOURCE,dst=DEST \
	pvac406.sif pvacseq run \
	input.vcf.gz \
	id \
	H-2-Kd,H-2-Dd,H-2-Ld \
	NetMHCpan \
	output/dir \
	--iedb-install-directory /opt/iedb \
	--net-chop-method cterm \
	--netmhc-stab \
	--run-reference-proteome-similarity --blastp-path ncbi/dir --blastp-db refseq_select_prot \
	-a sample_name \
	--phased-proximal-variants-vcf phased.vcf.gz \
	--tdna-vaf 0.05 \
	--trna-vaf 0.05 \
```

### Log output

No log.

**Comment by susannasiebert** [comment]
@PierreLaplante Thank you for this bug report. Unfortunately, I'm unable to reproduce this error with my test data. Would you be able to include your input files with this ticket for further debugging?

**Comment by PierreLaplante** [comment]
Sure thing!

https://we.tl/t-twhdT3KP9p

**Comment by susannasiebert** [comment]
Unfortunately, I've not been able to replicate this error so I think this might be an intermittent error. The error was emitted by IEDB itself so I can't provide any information about what might've gone wrong. The actual failure was:
```
  File "/opt/iedb/mhc_i/src/predict_binding.py", line 211, in add_rows_binding
    for (k, prediction) in enumerate(predictions):
TypeError: 'NoneType' object is not iterable
```
My best guess would be that this process ran out of memory while making predictions or ran into some other sort of problem. I think if you were to restart this job, it would probably succeed.

**Comment by PierreLaplante** [comment]
Ok, I'll give it a shot and let you know, thanks.

**Comment by susannasiebert** [comment]
@PierreLaplante were you able to get a successful run?

**Comment by PierreLaplante** [comment]
Hi, sorry for disappearing, it indeed worked, I added additional memory just in case.
Thank you for your help!

**Comment by susannasiebert** [comment]
Awesome. I'll close this ticket.

**Comment by susannasiebert** [comment]
Can you please try rerunning your pVACseq command to see if this error is intermittent?
