### ISSUE TITLE
Bug：corresponding_wt = min(result['wt_{}s'.format(metric)][best_mt_value_method].values()) TypeError: '<' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by ZoeChao2001** [griffithlab/pVACtools#1046]
### Installation Type

Standalone

### pVACtools Version / Docker Image

4.0.6

### Python Version

3.7.16

### Operating System

UBUNTU

### Describe the bug

When processing data from approximately 300 samples with the same set of parameters, four samples encountered the identical error as shown below. Despite deleting the output data and rerunning the process, the same error persists. Attached are the input and output files for one of these samples.
```
Parsing prediction file for Allele HLA-C*06:02 and Epitope Length 11 - Entries 1-92 - Completed
Parsing prediction file for Allele HLA-C*15:05 and Epitope Length 8 - Entries 1-92
Traceback (most recent call last):
  File "/home/z/miniconda3/envs/pvactools/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/home/z/miniconda3/envs/pvactools/lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/home/z/miniconda3/envs/pvactools/lib/python3.7/site-packages/pvactools/tools/pvacseq/run.py", line 138, in main
    pipeline.execute()
  File "/home/z/miniconda3/envs/pvactools/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 451, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
  File "/home/z/miniconda3/envs/pvactools/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 412, in parse_outputs
    parser.execute()
  File "/home/z/miniconda3/envs/pvactools/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 629, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
  File "/home/z/miniconda3/envs/pvactools/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 515, in process_input_iedb_file
    iedb_results_with_metrics = self.add_summary_metrics(iedb_results)
  File "/home/z/miniconda3/envs/pvactools/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 452, in add_summary_metrics
    corresponding_wt = min(result['wt_{}s'.format(metric)][best_mt_value_method].values())
TypeError: '<' not supported between instances of 'float' and 'str'
```

### How to reproduce this bug

```Shell
pvacseq run --iedb-install-directory <IEDB_INSTALL_DIRECTORY> -t 7 --run-reference-proteome-similarity --peptide-fasta <PEPTIDE_FASTA> --normal-sample-name 7942d378-faae-46e3-bf2b-29ec424e3da3 -c 1 c00d925a-ca4d-4561-a8f2-d4542f218086.gx.vcf.gz c00d925a-ca4d-4561-a8f2-d4542f218086 HLA-A*02:01,HLA-A*32:01,HLA-B*49:01,HLA-B*73:01,HLA-C*06:02,HLA-C*15:05 all_class_i <output_dir>
```

### Input files

[c00d925a-ca4d-4561-a8f2-d4542f218086.gx.vcf.gz](https://github.com/griffithlab/pVACtools/files/13870988/c00d925a-ca4d-4561-a8f2-d4542f218086.gx.vcf.gz)

### Log output

.

### Output files

[output.zip](https://github.com/griffithlab/pVACtools/files/13870991/output.zip)

**Comment by susannasiebert** [comment]
@ZoeChao2001 thank you for bringing this bug to our attention. I made a bugfix PR to address this issue and it should go out with the next bugfix release.

**Comment by ZoeChao2001** [comment]
@susannasiebert Thanks for the quick response and addressing the bug! Looking forward to the next release.

**Comment by susannasiebert** [comment]
This should be fixed in version 4.0.7. Please give it a try and let me know if you're still running into this error.
