### ISSUE TITLE
"TypeError: 'NoneType' object is not subscriptable" with SMMPMBEC 8mers

### ISSUE THREAD

**Issue by connorjliu** [griffithlab/pVACtools#105]
I receive the following error when running pvacseq class I predictions. Initially, I removed all tmp files for entries 1401-1600 but received the same error message after re-running. I double checked and I am using the latest pvactools version 1.0.3

Running IEDB on Allele HLA-A*24:02 and Epitope Length 8 with Method SMMPMBEC - Entries 1401-1600
Completed
Parsing IEDB Output for Allele HLA-A*24:02 and Epitope Length 8 - Entries 1401-1600
Traceback (most recent call last):
  File "/gscuser/yafeng/miniconda2/envs/python3/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/tools/pvacseq/run.py", line 126, in main
    pipeline.execute()
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/lib/pipeline.py", line 340, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/lib/pipeline.py", line 500, in call_iedb_and_parse_outputs
    parser.execute()
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/lib/output_parser.py", line 374, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/lib/output_parser.py", line 306, in process_input_iedb_file
    iedb_results              = self.parse_iedb_file(tsv_entries)
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/lib/output_parser.py", line 514, in parse_iedb_file
    return self.match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/lib/output_parser.py", line 249, in match_wildtype_and_mutant_entries
    self.match_wildtype_and_mutant_entry_for_frameshift(result, mt_position, wt_results, previous_result)
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/lib/output_parser.py", line 130, in match_wildtype_and_mutant_entry_for_frameshift
    if mutation_position == 1 and int(previous_result['mutation_position']) <= 1:
TypeError: 'NoneType' object is not subscriptable

**Comment by susannasiebert** [comment]
Doing some digging it looks like the Downstream protein sequence in the input file is incorrect. The VEP annotation looks like this: 
```
-|frameshift_variant|HIGH|PRSS3|ENSG00000010438|Transcript|ENST00000457896|protein_coding|2/5||||93-94|3-4|1-2|MR/MX|atGAga/atga|||1|cds_end_NF|HGNC|9486|RETSGFTLKKGRSAPLVFHPPDALIAVPFDDDDKIVGGYTCEENSLPYQVSLNSGSHFCGGSLISEQWVVSAAHCYKTRIQVRLGEHNIKVLEGNEQFINAAKIIRHPKYNRDTLDNDIMLIKLSSPAVINARVSTISLPTTPPAAGTECLISGWGNTLSFGADYPDELKCLDAPVRETSGFTLKKGRSAPLVFHPPDALIAVPFDDDDKIVGGYTCEENSLPYQVSLNSGSHFCGGSLISEQWVVSAAHCYKTRIQVRLGEHNIKVLEGNEQFINAAKIIRHPKYNRDTLDNDIMLIKLSSPAVINARVSTISLPTTPPAAGTECLISGWGNTLSFGADYPDELKCLDAPV|176|MRETSGFTLKKGRSAPLVFHPPDALIAVPFDDDDKIVGGYTCEENSLPYQVSLNSGSHFCGGSLISEQWVVSAAHCYKTRIQVRLGEHNIKVLEGNEQFINAAKIIRHPKYNRDTLDNDIMLIKLSSPAVINARVSTISLPTTPPAAGTECLISGWGNTLSFGADYPDELKCLDAPV
```
Applying the mutation manually to the transcript sequence the sequences should be as follows:
WT: `MRETSGFTLKKGRSAPLVFHPPDALIAVPFDDDDKIVGGYTCEENSLPYQVSLNSGSHFCGGSLISEQWVVSAAHCYKTRIQVRLGEHNIKVLEGNEQFINAAKIIRHPKYNRDTLDNDIMLIKLSSPAVINARVSTISLPTTPPAAGTECLISGWGNTLSFGADYPDELKCLDAPV`
MT: `MRDKWLHIEEGEECAIGFPSSRCTDCCPL`

There is a new version of the Downstream plugin so Connor will rerun the VEP annotation with the updated plugin and see if that fixes the VEP annotation. If it doesn't we'll need to contact ensembl.

**Comment by susannasiebert** [comment]
@connorjliu did running with the newest Downstream plugin fix this error?

**Comment by susannasiebert** [comment]
I assumed that this has been resolved. Please feel free to reopen if you're still having problems.
