### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by ZoeChao2001** [griffithlab/pVACtools#1053]
### Installation Type

Standalone

### pVACtools Version / Docker Image

4.0.6

### Python Version

3.8.18

### Operating System

CentOS

### Describe the bug

```
Executing MHC Class I predictions
Converting .vcf to TSV
Completed
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-48
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 1-96
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 1-96
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 1-96
Generating Variant Peptide FASTA and Key Files - Epitope Length 11 - Entries 1-96
Completed
Epitope Length 8 is not valid for Method SMM and Allele HLA-C*04:01. Skipping.
Epitope Length 8 is not valid for Method SMMPMBEC and Allele HLA-C*04:01. Skipping.
Epitope Length 10 is not valid for Method SMM and Allele HLA-C*04:01. Skipping.
Epitope Length 10 is not valid for Method SMMPMBEC and Allele HLA-C*04:01. Skipping.
Epitope Length 11 is not valid for Method SMM and Allele HLA-C*04:01. Skipping.
Epitope Length 11 is not valid for Method SMMPMBEC and Allele HLA-C*04:01. Skipping.
Allele HLA-C*16:01 not valid for Method NetMHC. Skipping.
Allele HLA-C*16:01 not valid for Method SMM. Skipping.
Allele HLA-C*16:01 not valid for Method SMMPMBEC. Skipping.
Making binding predictions on Allele HLA-A*11:01 and Epitope Length 8 with Method MHCflurry - File /Users/zhaozidi/pvactools/test/1__dc505248-ed04-4f77-a7c6-3fefbc5df27b/individualHLA/MHC_Class_I/tmp/dc505248-ed04-4f77-a7c6-3fefbc5df27b.MHCflurry.HLA-A*11:01.8.tsv_1-96
Making binding predictions on Allele HLA-A*11:01 and Epitope Length 8 with Method MHCflurry - File /Users/zhaozidi/pvactools/test/1__dc505248-ed04-4f77-a7c6-3fefbc5df27b/individualHLA/MHC_Class_I/tmp/dc505248-ed04-4f77-a7c6-3fefbc5df27b.MHCflurry.HLA-A*11:01.8.tsv_1-96 - Completed
Making binding predictions on Allele HLA-A*11:01 and Epitope Length 8 with Method MHCnuggetsI - File /Users/zhaozidi/pvactools/test/1__dc505248-ed04-4f77-a7c6-3fefbc5df27b/individualHLA/MHC_Class_I/tmp/dc505248-ed04-4f77-a7c6-3fefbc5df27b.MHCnuggetsI.HLA-A*11:01.8.tsv_1-96
Making binding predictions on Allele HLA-A*11:01 and Epitope Length 8 with Method MHCnuggetsI - File /Users/zhaozidi/pvactools/test/1__dc505248-ed04-4f77-a7c6-3fefbc5df27b/individualHLA/MHC_Class_I/tmp/dc505248-ed04-4f77-a7c6-3fefbc5df27b.MHCnuggetsI.HLA-A*11:01.8.tsv_1-96 - Completed
Making binding predictions on Allele HLA-A*11:01 and Epitope Length 8 with Method NetMHC - File /Users/zhaozidi/pvactools/test/1__dc505248-ed04-4f77-a7c6-3fefbc5df27b/individualHLA/MHC_Class_I/tmp/dc505248-ed04-4f77-a7c6-3fefbc5df27b.ann.HLA-A*11:01.8.tsv_1-96
Traceback (most recent call last):
  File "/Software/pvactools/reference_data/IEDB/mhc_i/src/predict_binding.py", line 516, in <module>
    Prediction().main()
  File "/Software/pvactools/reference_data/IEDB/mhc_i/src/predict_binding.py", line 507, in main
    self.commandline_input(args)
  File "/Software/pvactools/reference_data/IEDB/mhc_i/src/predict_binding.py", line 132, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.as_amino_acid_text())
  File "/Software/pvactools/reference_data/IEDB/mhc_i/src/seqpredictor.py", line 903, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/Software/pvactools/reference_data/IEDB/mhc_i/src/seqpredictor.py", line 268, in predict_sequence
    scores = predict_netmhc(allele_name, str(self.length), sequence)
  File "/Software/pvactools/reference_data/IEDB/mhc_i/src/../method/netmhc-4.0-executable/netmhc_4_0_executable/__init__.py", line 33, in predict
    process = Popen(cmd, stdout=PIPE)
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '../../../../Software/pvactools/reference_data/IEDB/mhc_i/method/netmhc-4.0-executable/netmhc_4_0_executable/netMHC'
An exception occured in thread 0: (<class 'subprocess.CalledProcessError'>, Command '['/Software/miniconda3/envs/pvactools/bin/python', '/Software/pvactools/reference_data/IEDB/mhc_i/src/predict_binding.py', 'ann', 'HLA-A*11:01', '8', '/Users/zhaozidi/pvactools/test/1__dc505248-ed04-4f77-a7c6-3fefbc5df27b/individualHLA/MHC_Class_I/tmp/dc505248-ed04-4f77-a7c6-3fefbc5df27b.8.fa.split_1-96']' returned non-zero exit status 1.).
Traceback (most recent call last):
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 356, in call_iedb
    pvactools.lib.call_iedb.main(arguments)
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pvactools/lib/call_iedb.py", line 44, in main
    raise err
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pvactools/lib/call_iedb.py", line 39, in main
    (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries, tmp_dir=args.tmp_dir)
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pvactools/lib/prediction_class.py", line 58, in predict
    response = run(arguments, stdout=response_fh, check=True)
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Software/miniconda3/envs/pvactools/bin/python', '/Software/pvactools/reference_data/IEDB/mhc_i/src/predict_binding.py', 'ann', 'HLA-A*11:01', '8', '/Users/zhaozidi/pvactools/test/1__dc505248-ed04-4f77-a7c6-3fefbc5df27b/individualHLA/MHC_Class_I/tmp/dc505248-ed04-4f77-a7c6-3fefbc5df27b.8.fa.split_1-96']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Software/miniconda3/envs/pvactools/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pvactools/tools/pvacseq/run.py", line 138, in main
    pipeline.execute()
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 450, in execute
    self.call_iedb(chunks)
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 357, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/Software/miniconda3/envs/pvactools/lib/python3.8/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: __init__() missing 1 required positional argument: 'cmd'

```

### How to reproduce this bug

```Shell
pvacseq run --iedb-install-directory <iedb_dir> -t 1 --run-reference-proteome-similarity --peptide-fasta Homo_sapiens.GRCh37.pep.all.fa.gz --normal-sample-name 1db021c8-f3b6-4012-9c12-53ca38d8f45c -c 1 dc505248-ed04-4f77-a7c6-3fefbc5df27b.gx.vcf.gz dc505248-ed04-4f77-a7c6-3fefbc5df27b HLA-A*11:01,HLA-A*24:02,HLA-C*04:01,HLA-C*16:01 all_class_i <output_file>
```

### Input files

[dc505248-ed04-4f77-a7c6-3fefbc5df27b.gx.vcf.gz](https://github.com/griffithlab/pVACtools/files/13988443/dc505248-ed04-4f77-a7c6-3fefbc5df27b.gx.vcf.gz)

### Log output

.

### Output files

[MHC_Class_I.zip](https://github.com/griffithlab/pVACtools/files/13988446/MHC_Class_I.zip)

**Comment by ZoeChao2001** [comment]
I have examined similar error reports in the past and attempted various solutions, including adjusting the fasta size, reducing the number of threads to 1, and changing the version of IEDB being used. Unfortunately, none of these approaches have successfully resolved the issue. I would appreciate your assistance in finding a solution to this problem. Thank you.

**Comment by susannasiebert** [comment]
You problem seems to be related to your actual IEDB installation path:
```
FileNotFoundError: [Errno 2] No such file or directory: '../../../../Software/pvactools/reference_data/IEDB/mhc_i/method/netmhc-4.0-executable/netmhc_4_0_executable/netMHC'
```
Can you confirm that this file exists on your machine (including all the ../)? What are you specifying as your --iedb-install-directory and what's the absolute path to your IEDB installation?
