### ISSUE TITLE
Error with IEDB local installation

### ISSUE THREAD

**Issue by jlanillos** [griffithlab/pVACtools#107]
Hello!

I got the error pasted below when I tried my IEDB local installation. This is the command line (it's been running without `--iedb-install-directory $IEDB`):

`run --iedb-install-directory $IEDB -e 10 --net-chop-method cterm --netmhc-stab --top-score-metric=lowest -d full -i $ADDITYAML input.vcf Test HLA-G*01:09,HLA-E*01:01,H2-IAb {NNalign,NetMHC,PickPocket} TRIAL`

I installed pvactools in a py35 conda environment (using miniconda2).

I followed the IEDB installation according to the instructions in the website (also, deleting/commenting the lines in the specified files to execute some methods). Please, note the code written in bold below related to pkg_resources: should I also modify line 13 in _method/netmhcpan-3.0-executable/netmhcpan_3_0_executable/__init__.py_ file? :

`_executable_filename = \
    pkg_resources.resource_filename('netmhcpan_3_0_executable', 'netMHCpan')`

##### ERROR #####

_Running IEDB on Allele HLA-E*01:01 and Epitope Length 10 with Method NetMHC - Entries 1-48
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/tmp/javier/tools/pvacseq/IEDB_MHC/mhc_i/src/predict_binding.py", line 14, in <module>
    from seqpredictor import MHCBindingPredictions
  File "/mnt/hds/proj/bioinfo/tmp/javier/tools/pvacseq/IEDB_MHC/mhc_i/src/seqpredictor.py", line 10, in <module>
    from netmhcpan_3_0_executable import predict_many as predict_netmhcpan
  **File "/mnt/hds/proj/bioinfo/tmp/javier/tools/pvacseq/IEDB_MHC/mhc_i/src/../method/netmhcpan-3.0-executable/netmhcpan_3_0_executable/__init__.py", line 14, in <module>
    pkg_resources.resource_filename('netmhcpan_3_0_executable', 'netMHCpan')
NameError: name 'pkg_resources' is not defined**
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/tmp/javier/miniconda2/envs/py35/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/mnt/hds/proj/bioinfo/tmp/javier/miniconda2/envs/py35/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/mnt/hds/proj/bioinfo/tmp/javier/miniconda2/envs/py35/lib/python3.5/site-packages/tools/pvacseq/run.py", line 126, in main
    pipeline.execute()
  File "/mnt/hds/proj/bioinfo/tmp/javier/miniconda2/envs/py35/lib/python3.5/site-packages/lib/pipeline.py", line 340, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/mnt/hds/proj/bioinfo/tmp/javier/miniconda2/envs/py35/lib/python3.5/site-packages/lib/pipeline.py", line 473, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/mnt/hds/proj/bioinfo/tmp/javier/miniconda2/envs/py35/lib/python3.5/site-packages/lib/call_iedb.py", line 56, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/mnt/hds/proj/bioinfo/tmp/javier/miniconda2/envs/py35/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/mnt/hds/proj/bioinfo/tmp/javier/tools/pvacseq/IEDB_MHC/mhc_i/src/predict_binding.py', 'ann', 'HLA-E*01:01', '10', '/mnt/hds/proj/bioinfo/tmp/javier/tools/pvacseq/tmp/pvacseq_example_data/TRIAL/MHC_Class_I/tmp/Test_21.fa.split_1-48']' returned non-zero exit status 1
_

**Comment by susannasiebert** [comment]
Actually, try putting the `import pkg_resources` statement back in the file. Our instructions are a bit outdated and not compatible with the newest version of IEDB. This will all go away once https://github.com/griffithlab/pVACtools/pull/99 gets merged in and released.

**Comment by susannasiebert** [comment]
I assume that my recommendation fixed your error so I will close this issue but please do reopen it if you are still having problems.
