### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by ahkamzifo** [griffithlab/pVACtools#1081]
Facing almost similar issue https://github.com/griffithlab/pVACtools/issues/692 when running pvacseq using docker via snakemake as part of the pipeline. I started the run for six samples. However, one sample failed and have shared and attached the log below:

pVACtools Version / Docker Image
4.1.0 - running via Singularity (v3.8.6)

Operating System
NAME="Ubuntu"
VERSION="22.04.3 LTS (Jammy Jellyfish)"

While running "pvacseq run" command, my run is getting interpreted after a while and error log for one particular sample is shown below: Also have attached the log file.
[SRR8281226.neoantigen_pvacseq.log](https://github.com/griffithlab/pVACtools/files/14540936/SRR8281226.neoantigen_pvacseq.log)

`Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/run.py", line 142, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 452, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 413, in parse_outputs
    parser.execute()
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 637, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 522, in process_input_iedb_file
    iedb_results = self.parse_iedb_file(tsv_entries)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 808, in parse_iedb_file
    return self.match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 406, in match_wildtype_and_mutant_entries
    self.match_wildtype_and_mutant_entry_for_inframe_indel(result, mt_position, wt_results, previous_result, iedb_results_for_wt_iedb_result_key)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 313, in match_wildtype_and_mutant_entry_for_inframe_indel
    result['mutation_position'] = self.determine_ins_mut_position_from_previous_result(previous_result, mt_epitope_seq, result)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 77, in determine_ins_mut_position_from_previous_result
    previous_mutation_position = self.position_to_tuple(previous_result['mutation_position'])
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/output_parser.py", line 182, in position_to_tuple
    return (int(mut_pos[0:d_ind]), int(mut_pos[d_ind+1:]))
ValueError: invalid literal for int() with base 10: ''`

Please find the generated pVACseq input YAML attached here.
[SRR8281226_inputs.txt](https://github.com/griffithlab/pVACtools/files/14541040/SRR8281226_inputs.txt)

Please help us know what is causing the issue here with this specific sample.

**Comment by susannasiebert** [comment]
Thank you for this error report. Can you please attach your input VCF or the full set of output files to this ticket so I can try to replicate this error on my end?

**Comment by ahkamzifo** [comment]
@susannasiebert Thanks for your reply. Please find the input VCF attached here (zipped to reduce the size). 
[SRR8281226.vcf.txt.zip](https://github.com/griffithlab/pVACtools/files/14543582/SRR8281226.vcf.txt.zip)

**Comment by susannasiebert** [comment]
This issue has been fixed in version 4.1.1. Please give that version a try and feel free to reopen this issue if the error persists.
