### ISSUE TITLE
Illegal division by 0

### ISSUE THREAD

**Issue by zlskidmore** [griffithlab/pVACtools#132]
When running pvactools (1.0.6a) I receive the following error:

```
Executing MHC Class I predictions
Converting .vcf to TSV
Traceback (most recent call last):
  File "/opt/conda/bin/pvacseq", line 11, in <module>
    load_entry_point('pvactools', 'console_scripts', 'pvacseq')()
  File "/src/pvactools/tools/pvacseq/main.py", line 85, in main
    args[0].func.main(args[1])
  File "/src/pvactools/tools/pvacseq/run.py", line 227, in main
    pipeline.execute()
  File "/src/pvactools/lib/pipeline.py", line 352, in execute
    self.convert_vcf()
  File "/src/pvactools/lib/pipeline.py", line 175, in convert_vcf
    converter.execute()
  File "/src/pvactools/lib/input_file_converter.py", line 288, in execute
    coverage_for_entry = self.calculate_coverage_for_entry(coverage, entry, reference, alt, start, chromosome, genotype)
  File "/src/pvactools/lib/input_file_converter.py", line 243, in calculate_coverage_for_entry
    coverage_for_entry[coverage_type + '_vaf']   = self.calculate_vaf(int(brct[var_base]), int(brct['depth']))
  File "/src/pvactools/lib/input_file_converter.py", line 146, in calculate_vaf
    return (var_count / depth) * 100
ZeroDivisionError: division by zero
```

I suspect this is because I am giving tumor rna rcnts in the yaml and there are cases where the is no RNA expression and so coverage is 0 but pvactools is still trying to calculate VAF in these cases.

**Comment by zlskidmore** [comment]
I think NA would be fine

**Comment by chrisamiller** [comment]
I lean towards NA, as long as downstream filters and scoring handle that correctly. No coverage means that you can't calculate a VAF, not that the VAF is zero.  Things like the priority score should probably treat an NA as zero though.
