### ISSUE TITLE
Invalid character 'U'

### ISSUE THREAD

**Issue by connorjliu** [griffithlab/pVACtools#136]
I first encountered this error message and attempted to remove the particular sequence that was cited as containing the invalid 'U'. However when re-running I got the same error message for a different amino acid sequence containing 'U'.

Running IEDB on Allele HLA-A*24:02 and Epitope Length 9 with Method NetMHC - Entries 246601-246800
Traceback (most recent call last):
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py", line 383, in <module>
    Prediction().main()
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py", line 375, in main
    elif (len(args)  == 4):                            self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py", line 96, in commandline_input
    proteins = self.read_protein(fname)
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py", line 57, in read_protein
    protein.extract_fasta(f.read())
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/util.py", line 66, in extract_fasta
    self.add_protein("".join(seq), length, source, name)
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/util.py", line 47, in add_protein
    raise InputError("Sequence: '%s' contains an invalid character: '%c' at position %d." %(sequence, amino_acid, sequence.find(amino_acid)))
util.InputError: Sequence: 'SSSTRTAAWUSATDPWRSPWU' contains an invalid character: 'U' at position 9.
Traceback (most recent call last):
  File "/gscuser/coliu/miniconda2/envs/pvactools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 126, in main
    pipeline.execute()
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 340, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 473, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/call_iedb.py", line 56, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py', 'ann', 'HLA-A*24:02', '9', '/gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/classI_snvs_test/MHC_Class_I/tmp/GL261_classI_snvs_21.fa.split_246601-246800']' returned non-zero exit status 1

Second attempt: 

Running IEDB on Allele HLA-A*24:02 and Epitope Length 9 with Method NetMHC - Entries 285001-285200
Traceback (most recent call last):
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py", line 383, in <module>
    Prediction().main()
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py", line 375, in main
    elif (len(args)  == 4):                            self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py", line 96, in commandline_input
    proteins = self.read_protein(fname)
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py", line 57, in read_protein
    protein.extract_fasta(f.read())
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/util.py", line 66, in extract_fasta
    self.add_protein("".join(seq), length, source, name)
  File "/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/util.py", line 47, in add_protein
    raise InputError("Sequence: '%s' contains an invalid character: '%c' at position %d." %(sequence, amino_acid, sequence.find(amino_acid)))
util.InputError: Sequence: 'VETCGGUQLNRLKEVKAFVTQ' contains an invalid character: 'U' at position 6.
Traceback (most recent call last):
  File "/gscuser/coliu/miniconda2/envs/pvactools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 126, in main
    pipeline.execute()
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 340, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 473, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/call_iedb.py", line 56, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/gscmnt/gc2502/griffithlab/yafeng/mhc_i/src/predict_binding.py', 'ann', 'HLA-A*24:02', '9', '/gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/classI_snvs_test22/MHC_Class_I/tmp/GBM27_classI_snvs_21.fa.split_285001-285200']' returned non-zero exit status 1
coliu@linus97:/gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27$ d

**Comment by susannasiebert** [comment]
@connorjliu do you get the same error when running with the api instead of the standalone iedb install?

**Comment by susannasiebert** [comment]
I made a new hotfix release (1.0.7) that contains this fix. It has also been merged into the staging branch. Closing.
