### ISSUE TITLE
KeyError: 'pvactools_version'

### ISSUE THREAD

**Issue by gudaslug** [griffithlab/pVACtools#163]
hello,
When I　run the example of pvacseq, the program broke off. Here is my input command.
pvacseq run input.vcf Test HLA-G*01:09,HLA-E*01:01,H2-IAb NetMHC PickPocket NNalign .  -e 9,10 -i additional_input_file_list.yaml --tdna-vaf 20 --net-chop-method cterm --netmhc-stab --top-score-metric=lowest -d full --keep-tmp-files

The follow is the output

Executing MHC Class I predictions
Traceback (most recent call last):
  File "/lustre/home/.conda/envs/py35/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/lustre/home/.conda/envs/py35/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/lustre/home/.conda/envs/py35/lib/python3.5/site-packages/tools/pvacseq/run.py", line 126, in main
    pipeline.execute()
  File "/lustre/home/.conda/envs/py35/lib/python3.5/site-packages/lib/pipeline.py",line 328, in execute
    self.print_log()
  File "/lustre/home/.conda/envs/py35/lib/python3.5/site-packages/lib/pipeline.py",line 80, in print_log
    if past_inputs['pvactools_version'] != current_inputs['pvactools_version']:
KeyError: 'pvactools_version'

Can anyone help me with this? Thank you

**Comment by susannasiebert** [comment]
I apologize that you are having into problems running the example data. Please delete the `log` folders in `MHC_Class_I` and `MHC_Class_II`. They were erroneously included in the example data.
