### ISSUE TITLE
Working with online VEP

### ISSUE THREAD

**Issue by sagarutturkar** [griffithlab/pVACtools#242]
I used the web version of VEP to annotate my VCF files. Is there any way to make wildtype plugin work with VCF files annotated through web VEP? If I use web VEP files directly then I get an error as:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/group/bioinfo/apps/apps/miniconda-4.3.21/envs/pvactools-2018-Dec-13/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/group/bioinfo/apps/apps/miniconda-4.3.21/envs/pvactools-2018-Dec-13/lib/python3.5/site-packages/tools/pvacseq/main.py", line 99, in main
    args[0].func.main(args[1])
  File "/group/bioinfo/apps/apps/miniconda-4.3.21/envs/pvactools-2018-Dec-13/lib/python3.5/site-packages/tools/pvacseq/run.py", line 170, in main
    pipeline.execute()
  File "/group/bioinfo/apps/apps/miniconda-4.3.21/envs/pvactools-2018-Dec-13/lib/python3.5/site-packages/lib/pipeline.py", line 276, in execute
    self.convert_vcf()
  File "/group/bioinfo/apps/apps/miniconda-4.3.21/envs/pvactools-2018-Dec-13/lib/python3.5/site-packages/lib/pipeline.py", line 182, in convert_vcf
    converter.execute()
  File "/group/bioinfo/apps/apps/miniconda-4.3.21/envs/pvactools-2018-Dec-13/lib/python3.5/site-packages/lib/input_file_converter.py", line 381, in execute
    if transcript['DownstreamProtein'] == '':
KeyError: 'DownstreamProtein'
```

**Comment by susannasiebert** [comment]
The web version of VEP does not support plugins. Both the Wildtype and Downstream plugin are required to run pVACseq, therefore, you will need to use the standalone VEP software to annotate your VCF.
