### ISSUE TITLE
FutureWarning

### ISSUE THREAD

**Issue by 41526** [griffithlab/pVACtools#298]
* pvactools version: 1.3.0
* Python version: 3.6.8
* Operating System: linux

**Describe the bug**
After I install pvactools, it looks good. However, when I run the code `pvacseq -h` just for a test. A error occurs. The error message is :   
`/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/mhcflurry/amino_acid.py:71: FutureWarning: read_table is deprecated, use read_csv instead.
  """), sep='\s+').loc[AMINO_ACIDS, AMINO_ACIDS]
Using TensorFlow backend.
Traceback (most recent call last):
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/libc.so.6: version `GLIBC_2.16' not found (required by /pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/bin/pvacseq", line 7, in <module>
    from tools.pvacseq.main import main
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tools/pvacseq/__init__.py", line 16, in <module>
    from . import *
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tools/pvacseq/run.py", line 4, in <module>
    from lib.prediction_class import *
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/lib/__init__.py", line 26, in <module>
    from . import *
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/lib/binding_filter.py", line 6, in <module>
    from lib.allele_specific_binding_filter import *
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/lib/allele_specific_binding_filter.py", line 3, in <module>
    from lib.prediction_class import *
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/lib/prediction_class.py", line 7, in <module>
    from mhcnuggets.src.predict import predict
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/mhcnuggets/src/predict.py", line 11, in <module>
    from mhcnuggets.src.models import get_predictions, mhcnuggets_lstm
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/mhcnuggets/src/models.py", line 9, in <module>
    import keras
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/libc.so.6: version `GLIBC_2.16' not found (required by /pub5/xiaoyun/BioSoftware/Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

**Log Output**
```
The log that gets written to standard out
```

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.

**Expected behavior**

**Comment by susannasiebert** [comment]
The FutureWarning is a red herring and not actually related to this error. The real cause of the error is buried a bit deep in the stack trace: `Failed to load the native TensorFlow runtime.`. I see that you are using a Python 3.6 environment. Can you please downgrade to python 3.5 and see if that fixes this problem? pVACtools is currently not compatible with python 3.6.

**Comment by 41526** [comment]
Thanks, i will hava a try.
