### ISSUE TITLE
Installing pVACtools in a conda environment where tensorflow is already installed breaks pvacseq

### ISSUE THREAD

**Issue by d-henness** [griffithlab/pVACtools#312]
* pvactools version: 1.3.1
* Python version: 3.5
* Operating System: Ubuntu 18.04 and CentOS 7.5.1804

**Describe the bug**
Installing pvactools in a conda environment where tensorflow is already installed in causes pvacseq to break. For example, editing the pvacseq script to 

```
#!/home/dylan/miniconda3/envs/testing_pvec/bin/python

# -*- coding: utf-8 -*-
print('hello1')                                                                                                                     
import re                                                                                                                                   
import sys                                                                                                                                  

print('hello2')                                                                                                                                            
from tools.pvacseq.main import main                                                                                                         
print('hello3') 
                                                                                                                                           
if __name__ == '__main__':                                                                                                                  
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])                                                                       
    sys.exit(main())
```

only prints hello1 and hello2. There is no error message.

**To Reproduce**

```
conda create -n testing_pvec ensembl-vep=95.2 python=3.5   vt=2015.11.10 tensorflow=1.8.0
conda activate testing_pvec
pip install pvactools
pvacseq -h

```

I should mention that I can install and run pvacseq just fine if tensorflow is not pre-installed with conda, but I will need to use this on a cluster where the only way I'd be able to install tensorflow is through conda before I try to install pvactools.

**Comment by susannasiebert** [comment]
I'm able to reproduce this problem but I'm not sure how to solve this in pVACtools. My best guess is that the conda tensorflow recipe is not quite working right so I would contact the creators of that recipe. Tensorflow is not directly used by pVACtools but is a dependency of MHCflurry so those folks might have some suggestions (https://github.com/openvax/mhcflurry).

Would it be possible for you to use our docker container?

**Comment by susannasiebert** [comment]
In one of the more recent releases we are doing some special handling of the import statement for for MHCflurry and MHCnuggets in order to suppress the `Using TensorFlow backend.` message. Unfortunately as a side effect this also suppresses any errors during import. I installed an older version of pVACtools and it gives the following error:
```
Traceback (most recent call last):
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/bin/pvacseq", line 7, in <module>
    from tools.pvacseq.main import main
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/tools/pvacseq/__init__.py", line 16, in <module>
    from . import *
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/tools/pvacseq/run.py", line 4, in <module>
    from lib.prediction_class import *
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/lib/__init__.py", line 26, in <module>
    from . import *
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/lib/binding_filter.py", line 6, in <module>
    from lib.allele_specific_binding_filter import *
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/lib/allele_specific_binding_filter.py", line 3, in <module>
    from lib.prediction_class import *
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/lib/prediction_class.py", line 7, in <module>
    from mhcnuggets.src.predict import predict
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/mhcnuggets/src/predict.py", line 11, in <module>
    from mhcnuggets.src.models import get_predictions, mhcnuggets_lstm
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/mhcnuggets/src/models.py", line 9, in <module>
    import keras
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /gscuser/ssiebert/miniconda2/envs/testing_pvec/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb
```
I'm still not sure what to make of it but I'll do more digging.

**Comment by susannasiebert** [comment]
I found the following issue: https://github.com/conda-forge/tensorflow-feedstock/issues/57 and I was able to get it to work by installing libprotobuf from the conda-forge channel: `conda install libprotobuf -c conda-forge -f`.

**Comment by d-henness** [comment]
Thanks for the help!
