### ISSUE TITLE
pvactools version

### ISSUE THREAD

**Issue by 41526** [griffithlab/pVACtools#314]
How to install previous versions of pvactools. I think the current version may conflict with the machine I am using. When I execute the command pvacseq run -h, the terminal does not display anything.

**Comment by 41526** [comment]
Now the version of pvactools on my machine is 1.3.1.

**Comment by susannasiebert** [comment]
You can install a specific version of pvactools by running `pip install pvactools==<version>`.

**Comment by 41526** [comment]
I used the yolk tool to query the available versions of pvactools and the results returned are only available in 1.3.1. Can I install offline by downloading the previous version of the installation package?

**Comment by 41526** [comment]
I installed pvactools V1.3.2, but this problem still exists.

**Comment by susannasiebert** [comment]
Did you see my comment on your other ticket? (https://github.com/griffithlab/pVACtools/issues/311#issuecomment-469280891) do you by any chance still have the pvacseq package installed in your environment?

**Comment by 41526** [comment]
Sorry, I didn't notice the comment. 
I repeatedly uninstalled and installed pvacseq several times, I tried pvacseq V1.2.0, V1.3.0, V1.3.1, V1.3.2.
When the pvacseq version is higher than or equal to 1.3.0, the exception is that the execution command returns nothing. When the version is lower than 1.3.0, the exception is about TensorFlow. TensorFlow exception I have encountered before and failed to solve.

**Comment by susannasiebert** [comment]
There is a difference between the `pvacseq` package and the `pvactools` package. Both enable the `pvacseq` command so if both _packages_ are installed, there will be conflicts. In your original ticket (#311) you installed the `pvacseq` package v4.0.10 through conda and then I instructed you to instead install the `pvactools` package. I want to make sure that the original `pvacseq` conda package is uninstalled. From your original ticket it is unclear to me whether you installed the `pvacseq` package through conda or through pip. To uninstall you would either run `conda uninstall pvacseq` or `pip uninstall pvacseq`. 

Can you please also try the following: Install the pvactools package version 1.2.0 (`pip install pvactools==1.2.0`). When you now run `pvacseq run -h` can you please post the output from this command. I expect it to throw an actual error. Please note that the `Using TensorFlow backend.` status message is expected. Do you get an actual error like the one I posted here (https://github.com/griffithlab/pVACtools/issues/312#issuecomment-469873030)?

**Comment by 41526** [comment]
Sorry, I said wrong before. I installed pvactools V1.2.0, V1.3.0, V1.3.1, V1.3.2 to find a usable version. I installed it using pip (pip install pvactools==<Version>). I have uninstalled the pvacseq package v4.0.10 previously installed via conda.
When the pvacseq version is higher than or equal to 1.3.0, I execute pvacseq run -h without returning any warnings, exceptions or error messages, nothing in the terminal.

**Comment by susannasiebert** [comment]
Can you please try the following: Install the pvactools package version 1.2.0 (`pip install pvactools==1.2.0`). When you now run `pvacseq run -h` can you please post the output from this command? I expect it to throw an actual error. Please note that the `Using TensorFlow backend.` status message is expected. Do you get an actual error like the one I posted here (https://github.com/griffithlab/pVACtools/issues/312#issuecomment-469873030)?

**Comment by 41526** [comment]
I create a conda environment and install pvactools using the following command:
`conda create -n pVACtools python=3.5`
`source activate pVACtools`
`pip install pvactools==1.2.0`
Successful installation
`pvactools -v`
 `1.2.0`
`pvacseq run -v`
Using TensorFlow backend.
Traceback (most recent call last):
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/libc.so.6: version `GLIBC_2.16' not found (required by /pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/bin/pvacseq", line 7, in <module>
    from tools.pvacseq.main import main
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tools/pvacseq/__init__.py", line 16, in <module>
    from . import *
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 4, in <module>
    from lib.prediction_class import *
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/lib/__init__.py", line 26, in <module>
    from . import *
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/lib/binding_filter.py", line 6, in <module>
    from lib.allele_specific_binding_filter import *
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/lib/allele_specific_binding_filter.py", line 3, in <module>
    from lib.prediction_class import *
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/lib/prediction_class.py", line 7, in <module>
    from mhcnuggets.src.predict import predict
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/mhcnuggets/src/predict.py", line 11, in <module>
    from mhcnuggets.src.models import get_predictions, mhcnuggets_lstm
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/mhcnuggets/src/models.py", line 9, in <module>
    import keras
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/libc.so.6: version `GLIBC_2.16' not found (required by /pub5/xiaoyun/BioSoftware/Conda/envs/pVACtools/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by susannasiebert** [comment]
I did some searching and found this issue on the tensorflow github (https://github.com/tensorflow/tensorflow/issues/53). You might want to try installing tensorflow through conda instead of pip (`pip uninstall tensorflow` `conda install tensorflow==1.8.0`).

**Comment by 41526** [comment]
Thank you very much, now my pvacseq is working.

**Comment by susannasiebert** [comment]
Awesome. Since your dependencies are now installed correctly, you should be able to upgrade to the latest pvactools version (`pip install pvactools --upgrade`).

**Comment by 41526** [comment]
I tried the latest version of pvactools, but it will be inexplicably interrupted. 
`Executing MHC Class I predictions
Restart inputs are different from past inputs: 
Past input: input_file - /IJob/J33/Data/SRP102119_BC_12P22M34NSamples_WES/WESSRA/WESFastq/_AfterFASTQC_/_AfterAlign_/BAMFile/VEPtest/VEPoutput/SMC_OS_42VEPed.vcf
Current input: input_file - /IJob/J33/Data/SRP102119_BC_12P22M34NSamples_WES/WESSRA/WESFastq/_AfterFASTQC_/_AfterAlign_/BAMFile/VEPtest/SMC_OS_42_SomaticTwiceFiltered.vcf.gz
Aborting.`
My command is:
`pvacseq run -e 8,9,10,11 --iedb-install-directory /pub6/temp/pb/Software/IEDB --normal-sample-name SRR5357710 --pass-only /IJob/J33/Data/SRP102119_BC_12P22M34NSamples_WES/WESSRA/WESFastq/_AfterFASTQC_/_AfterAlign_/BAMFile/VEPtest/SMC_OS_42_SomaticTwiceFiltered.vcf.gz SRR5357744 HLA-A*02:01,HLA-B*35:01,DRB1*11:01 NNalign NetMHC NetMHCIIpan NetMHCcons NetMHCpan PickPocket SMM SMMPMBEC SMMalign /IJob/J33/Data/SRP102119_BC_12P22M34NSamples_WES/WESSRA/WESFastq/_AfterFASTQC_/_AfterAlign_/BAMFile/pvacseq_output`

**Comment by susannasiebert** [comment]
You will need to delete the existing output directory since the path to the input file changed between the two runs.
