### ISSUE TITLE
Support VCF that were annotated with the `--total-length` VEP flag

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVACtools#366]
Hello!
I have this error with both pVAC-Seq 4.0.10 and pvactools 1.3.5:
VEP 91 and 95 was used for annotation.
```
Executing MHC Class I predictions
Converting .vcf to TSV
frameshift_variant transcript does not contain a DownstreamProtein sequence. Skipping.
chr16 71284260 AGTTC A ENST00000338099.9
frameshift_variant transcript does not contain a DownstreamProtein sequence. Skipping.
chr16 71284260 AGTTC A ENST00000434935.6
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Splitting TSV into smaller chunks - Entries 101-200
Splitting TSV into smaller chunks - Entries 201-300
Splitting TSV into smaller chunks - Entries 301-400
Splitting TSV into smaller chunks - Entries 401-500
Splitting TSV into smaller chunks - Entries 501-600
Splitting TSV into smaller chunks - Entries 601-700
Splitting TSV into smaller chunks - Entries 701-800
Splitting TSV into smaller chunks - Entries 801-900
Splitting TSV into smaller chunks - Entries 901-1000
Splitting TSV into smaller chunks - Entries 1001-1100
Splitting TSV into smaller chunks - Entries 1101-1200
Splitting TSV into smaller chunks - Entries 1201-1300
Splitting TSV into smaller chunks - Entries 1301-1400
Splitting TSV into smaller chunks - Entries 1401-1500
Splitting TSV into smaller chunks - Entries 1501-1600
Splitting TSV into smaller chunks - Entries 1601-1700
Splitting TSV into smaller chunks - Entries 1701-1800
Splitting TSV into smaller chunks - Entries 1801-1900
Splitting TSV into smaller chunks - Entries 1901-2000
Splitting TSV into smaller chunks - Entries 2001-2100
Splitting TSV into smaller chunks - Entries 2101-2200
Splitting TSV into smaller chunks - Entries 2201-2300
Splitting TSV into smaller chunks - Entries 2301-2400
Splitting TSV into smaller chunks - Entries 2401-2500
Splitting TSV into smaller chunks - Entries 2501-2600
Splitting TSV into smaller chunks - Entries 2601-2700
Splitting TSV into smaller chunks - Entries 2701-2800
Splitting TSV into smaller chunks - Entries 2801-2900
Splitting TSV into smaller chunks - Entries 2901-3000
Splitting TSV into smaller chunks - Entries 3001-3100
Splitting TSV into smaller chunks - Entries 3101-3200
Splitting TSV into smaller chunks - Entries 3201-3300
Splitting TSV into smaller chunks - Entries 3301-3400
Splitting TSV into smaller chunks - Entries 3401-3500
Splitting TSV into smaller chunks - Entries 3501-3600
Splitting TSV into smaller chunks - Entries 3601-3700
Splitting TSV into smaller chunks - Entries 3701-3800
Splitting TSV into smaller chunks - Entries 3801-3900
Splitting TSV into smaller chunks - Entries 3901-4000
Splitting TSV into smaller chunks - Entries 4001-4100
Splitting TSV into smaller chunks - Entries 4101-4200
Splitting TSV into smaller chunks - Entries 4201-4300
Splitting TSV into smaller chunks - Entries 4301-4400
Splitting TSV into smaller chunks - Entries 4401-4500
Splitting TSV into smaller chunks - Entries 4501-4600
Splitting TSV into smaller chunks - Entries 4601-4700
Splitting TSV into smaller chunks - Entries 4701-4752
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-200
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tools/pvacseq/main.py", line 99, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.6/dist-packages/tools/pvacseq/run.py", line 172, in main
    pipeline.execute()
  File "/usr/local/lib/python3.6/dist-packages/lib/pipeline.py", line 462, in execute
    self.generate_fasta(chunks)
  File "/usr/local/lib/python3.6/dist-packages/lib/pipeline.py", line 277, in generate_fasta
    fasta_generator.execute()
  File "/usr/local/lib/python3.6/dist-packages/lib/fasta_generator.py", line 181, in execute
    position = int(line['protein_position']) - 1
ValueError: invalid literal for int() with base 10: '20/207'
```

**Comment by susannasiebert** [comment]
Please attach your input VCF for further debugging.

**Comment by serge2016** [comment]
[pat16.annot.head50.vcf.zip](https://github.com/griffithlab/pVACtools/files/3083046/pat16.annot.head50.vcf.zip)

**Comment by susannasiebert** [comment]
Apparently that option has been around since version 73 but I guess nobody has every tried to use a VCF annotated with this option in pVACseq. Should be pretty straightforward to add support for it.

**Comment by susannasiebert** [comment]
This is supported in the latest version (1.3.7). Closing this issue but please reopen if you're still running into problems.
