### ISSUE TITLE
pvac run example not running:  Error no command specified

### ISSUE THREAD

**Issue by indapa** [griffithlab/pVACtools#433]
Hi pVACtools developers,

I'm new to the software and successfully installed v1.4.2 with a conda python 3.5 environment. I downloaded the test VCF file with the download_example_data command. However when I attempt to execute the run command I get this error. As far as I can tell I am providing the correct positional arguments. Can you help point me in the right direction?

pvacseq run pvacseq_example_data/input.vcf  Test HLA-A*02:01,HLA-A*01:01,HLA-A*03:01,HLA-A*11:01,HLA-A*24:02,HLA-B*7:02,HLA-B*35:01 MHCflurry  pvacseq_results  -e 8

Error: No command specified
Traceback (most recent call last):
  File "/home/indapa/.conda/envs/pvactools/bin/pvacseq", line 10, in <module>
    sys.exit(main())
  File "/home/indapa/.conda/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/home/indapa/.conda/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 163, in main
    pipeline.execute()
  File "/home/indapa/.conda/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 414, in execute
    self.print_log()
  File "/home/indapa/.conda/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 78, in print_log
    past_inputs = yaml.load(log_fh, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by susannasiebert** [comment]
Can you please check which version of the `PyYAML` module you have installed (`pip show PyYAML`) and update to the latest version (5.1.1) if necessary (`pip install PyYAML --upgrade`).

**Comment by indapa** [comment]
Great, I upgraded the PyYAML and some other packages and it worked with the input vcf. Thank you for your quick reply.
