### ISSUE TITLE
mhc_ii   install eror 

### ISSUE THREAD

**Issue by zhangyafeng1** [griffithlab/pVACtools#465]
* pvactools version:  1.5.1
* Python version:  2.7.9
hello,
when i install MHC Class II  , I encountered the following error.
my command line as follows： 
cd  mhc_ii
./configure.py

error as follows：
```
All prerequisites found!
run MHCII tests...
.F.Perl lib version (5.18.2) doesn't match executable '/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_ii/methods/netmhciipan-3.1-executable/netmhciipan_3_1_executable/NetMHCIIpan-3.1.pl' version (v5.10.1) at /PUBLIC/software/public/System/Perl-5.18.2/lib/perl5/5.18.2/x86_64-linux-thread-multi/Config.pm line 61.
Compilation failed in require at /PUBLIC/software/public/System/Perl-5.18.2/lib/perl5/5.18.2/Env.pm line 122.
BEGIN failed--compilation aborted at /PUBLIC/software/public/System/Perl-5.18.2/lib/perl5/5.18.2/Env.pm line 122.
Compilation failed in require at /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_ii/methods/netmhciipan-3.1-executable/netmhciipan_3_1_executable/NetMHCIIpan-3.1.pl line 9.
BEGIN failed--compilation aborted at /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_ii/methods/netmhciipan-3.1-executable/netmhciipan_3_1_executable/NetMHCIIpan-3.1.pl line 9.
Perl lib version (5.18.2) doesn't match executable '/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_ii/methods/netmhciipan-3.1-executable/netmhciipan_3_1_executable/NetMHCIIpan-3.1.pl' version (v5.10.1) at /PUBLIC/software/public/System/Perl-5.18.2/lib/perl5/5.18.2/x86_64-linux-thread-multi/Config.pm line 61.
Compilation failed in require at /PUBLIC/software/public/System/Perl-5.18.2/lib/perl5/5.18.2/Env.pm line 122.
BEGIN failed--compilation aborted at /PUBLIC/software/public/System/Perl-5.18.2/lib/perl5/5.18.2/Env.pm line 122.
Compilation failed in require at /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_ii/methods/netmhciipan-3.1-executable/netmhciipan_3_1_executable/NetMHCIIpan-3.1.pl line 9.
BEGIN failed--compilation aborted at /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_ii/methods/netmhciipan-3.1-executable/netmhciipan_3_1_executable/NetMHCIIpan-3.1.pl line 9.
FF.F..
======================================================================
FAIL: test_consensus (__main__.Test_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./configure.py", line 19, in test_consensus
    self.assertEqual(result, 'allele\tseq_num\tstart\tend\tpeptide\tconsensus_percentile_rank\tcomblib_core\tcomblib_score\tcomblib_rank\tsmm_align_core\tsmm_align_ic50\tsmm_align_rank\tnn_align_core\tnn_align_ic50\tnn_align_rank\tsturniolo_core\tsturniolo_score\tsturniolo_rank\nHLA-DRB1*03:01\t1\t1\t15\tMSNRDFLEGVSGATW\t28.13\t-\t-\t-\tFLEGVSGAT\t9343.0\t19.11\tFLEGVSGAT\t15398.6\t72.13\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t2\t16\tSNRDFLEGVSGATWV\t28.13\t-\t-\t-\tFLEGVSGAT\t8986.0\t18.32\tFLEGVSGAT\t13753.3\t69.06\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t3\t17\tNRDFLEGVSGATWVD\t28.13\t-\t-\t-\tFLEGVSGAT\t9085.0\t18.56\tFLEGVSGAT\t12966.4\t67.52\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t4\t18\tRDFLEGVSGATWVDL\t28.13\t-\t-\t-\tFLEGVSGAT\t8523.0\t17.28\tFLEGVSGAT\t12159.0\t65.84\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t8\t22\tEGVSGATWVDLVLEG\t28.63\t-\t-\t-\tVSGATWVDL\t5932.0\t11.7\tTWVDLVLEG\t3336.2\t37.49\tVSGATWVDL\t-1.34\t28.63\nHLA-DRB1*03:01\t1\t6\t20\tFLEGVSGATWVDLVL\t36.26\t-\t-\t-\tFLEGVSGAT\t18363.0\t36.26\tVSGATWVDL\t9927.8\t60.7\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t5\t19\tDFLEGVSGATWVDLV\t37.04\t-\t-\t-\tFLEGVSGAT\t18841.0\t37.04\tVSGATWVDL\t12588.1\t66.77\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t7\t21\tLEGVSGATWVDLVLE\t48.66\t-\t-\t-\tSGATWVDLV\t26621.0\t48.66\tVSGATWVDL\t8383.4\t56.73\tVSGATWVDL\t-1.34\t28.63\n')
AssertionError: 'allele\tseq_num\tstart\tend\tpeptide\tconsensus_percentile_rank\tcomblib_core\tcomblib_score\tcomblib_rank\tsmm_align_core\tsmm_align_ic50\tsmm_align_rank\tnn_align_core\tnn_align_ic50\tnn_align_rank\tsturniolo_core\tsturniolo_score\tsturniolo_rank\nHLA-DRB1*03:01\t1\t8\t22\tEGVSGATWVDLVLEG\t20.165\t-\t-\t-\tVSGATWVDL\t5932.0\t11.7\t-\t-\t-\tVSGATWVDL\t-1.34\t28.63\nHLA-DRB1*03:01\t1\t4\t18\tRDFLEGVSGATWVDL\t22.705\t-\t-\t-\tFLEGVSGAT\t8523.0\t17.28\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t2\t16\tSNRDFLEGVSGATWV\t23.225\t-\t-\t-\tFLEGVSGAT\t8986.0\t18.32\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t3\t17\tNRDFLEGVSGATWVD\t23.345\t-\t-\t-\tFLEGVSGAT\t9085.0\t18.56\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t1\t15\tMSNRDFLEGVSGATW\t23.62\t-\t-\t-\tFLEGVSGAT\t9343.0\t19.11\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t6\t20\tFLEGVSGATWVDLVL\t32.195\t-\t-\t-\tFLEGVSGAT\t18363.0\t36.26\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t5\t19\tDFLEGVSGATWVDLV\t32.585\t-\t-\t-\tFLEGVSGAT\t18841.0\t37.04\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t7\t21\tLEGVSGATWVDLVLE\t38.645\t-\t-\t-\tSGATWVDLV\t26621.0\t48.66\t-\t-\t-\tVSGATWVDL\t-1.34\t28.63\n' != 'allele\tseq_num\tstart\tend\tpeptide\tconsensus_percentile_rank\tcomblib_core\tcomblib_score\tcomblib_rank\tsmm_align_core\tsmm_align_ic50\tsmm_align_rank\tnn_align_core\tnn_align_ic50\tnn_align_rank\tsturniolo_core\tsturniolo_score\tsturniolo_rank\nHLA-DRB1*03:01\t1\t1\t15\tMSNRDFLEGVSGATW\t28.13\t-\t-\t-\tFLEGVSGAT\t9343.0\t19.11\tFLEGVSGAT\t15398.6\t72.13\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t2\t16\tSNRDFLEGVSGATWV\t28.13\t-\t-\t-\tFLEGVSGAT\t8986.0\t18.32\tFLEGVSGAT\t13753.3\t69.06\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t3\t17\tNRDFLEGVSGATWVD\t28.13\t-\t-\t-\tFLEGVSGAT\t9085.0\t18.56\tFLEGVSGAT\t12966.4\t67.52\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t4\t18\tRDFLEGVSGATWVDL\t28.13\t-\t-\t-\tFLEGVSGAT\t8523.0\t17.28\tFLEGVSGAT\t12159.0\t65.84\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t8\t22\tEGVSGATWVDLVLEG\t28.63\t-\t-\t-\tVSGATWVDL\t5932.0\t11.7\tTWVDLVLEG\t3336.2\t37.49\tVSGATWVDL\t-1.34\t28.63\nHLA-DRB1*03:01\t1\t6\t20\tFLEGVSGATWVDLVL\t36.26\t-\t-\t-\tFLEGVSGAT\t18363.0\t36.26\tVSGATWVDL\t9927.8\t60.7\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t5\t19\tDFLEGVSGATWVDLV\t37.04\t-\t-\t-\tFLEGVSGAT\t18841.0\t37.04\tVSGATWVDL\t12588.1\t66.77\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t7\t21\tLEGVSGATWVDLVLE\t48.66\t-\t-\t-\tSGATWVDLV\t26621.0\t48.66\tVSGATWVDL\t8383.4\t56.73\tVSGATWVDL\t-1.34\t28.63\n'

======================================================================
FAIL: test_netmhciipan (__main__.Test_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./configure.py", line 34, in test_netmhciipan
    self.assertEqual(result, 'allele\tseq_num\tstart\tend\tcore_peptide\tpeptide\tic50\tpercentile_rank\nHLA-DRB1*03:01\t1\t8\t22\tTWVDLVLEG\tEGVSGATWVDLVLEG\t7652.64\t75.42\nHLA-DRB1*03:01\t1\t1\t15\tSNRDFLEGV\tMSNRDFLEGVSGATW\t8635.35\t78.96\nHLA-DRB1*03:01\t1\t2\t16\tSNRDFLEGV\tSNRDFLEGVSGATWV\t10886.54\t84.73\nHLA-DRB1*03:01\t1\t7\t21\tSGATWVDLV\tLEGVSGATWVDLVLE\t11077.96\t85.17\nHLA-DRB1*03:01\t1\t4\t18\tFLEGVSGAT\tRDFLEGVSGATWVDL\t13714.94\t90.29\nHLA-DRB1*03:01\t1\t6\t20\tSGATWVDLV\tFLEGVSGATWVDLVL\t13762.36\t90.36\nHLA-DRB1*03:01\t1\t3\t17\tFLEGVSGAT\tNRDFLEGVSGATWVD\t13782.93\t90.4\nHLA-DRB1*03:01\t1\t5\t19\tVSGATWVDL\tDFLEGVSGATWVDLV\t14686.07\t91.54\n')
AssertionError: 'allele\tseq_num\tstart\tend\tcore_peptide\tpeptide\tic50\tpercentile_rank\n' != 'allele\tseq_num\tstart\tend\tcore_peptide\tpeptide\tic50\tpercentile_rank\nHLA-DRB1*03:01\t1\t8\t22\tTWVDLVLEG\tEGVSGATWVDLVLEG\t7652.64\t75.42\nHLA-DRB1*03:01\t1\t1\t15\tSNRDFLEGV\tMSNRDFLEGVSGATW\t8635.35\t78.96\nHLA-DRB1*03:01\t1\t2\t16\tSNRDFLEGV\tSNRDFLEGVSGATWV\t10886.54\t84.73\nHLA-DRB1*03:01\t1\t7\t21\tSGATWVDLV\tLEGVSGATWVDLVLE\t11077.96\t85.17\nHLA-DRB1*03:01\t1\t4\t18\tFLEGVSGAT\tRDFLEGVSGATWVDL\t13714.94\t90.29\nHLA-DRB1*03:01\t1\t6\t20\tSGATWVDLV\tFLEGVSGATWVDLVL\t13762.36\t90.36\nHLA-DRB1*03:01\t1\t3\t17\tFLEGVSGAT\tNRDFLEGVSGATWVD\t13782.93\t90.4\nHLA-DRB1*03:01\t1\t5\t19\tVSGATWVDL\tDFLEGVSGATWVDLV\t14686.07\t91.54\n'

======================================================================
FAIL: test_nn (__main__.Test_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./configure.py", line 39, in test_nn
    self.assertEqual(result, 'allele\tseq_num\tstart\tend\tcore_peptide\tpeptide\tic50\tpercentile_rank\nHLA-DRB1*03:01\t1\t8\t22\tTWVDLVLEG\tEGVSGATWVDLVLEG\t3336.2\t37.49\nHLA-DRB1*03:01\t1\t7\t21\tVSGATWVDL\tLEGVSGATWVDLVLE\t8383.4\t56.73\nHLA-DRB1*03:01\t1\t6\t20\tVSGATWVDL\tFLEGVSGATWVDLVL\t9927.8\t60.7\nHLA-DRB1*03:01\t1\t4\t18\tFLEGVSGAT\tRDFLEGVSGATWVDL\t12159.0\t65.84\nHLA-DRB1*03:01\t1\t5\t19\tVSGATWVDL\tDFLEGVSGATWVDLV\t12588.1\t66.77\nHLA-DRB1*03:01\t1\t3\t17\tFLEGVSGAT\tNRDFLEGVSGATWVD\t12966.4\t67.52\nHLA-DRB1*03:01\t1\t2\t16\tFLEGVSGAT\tSNRDFLEGVSGATWV\t13753.3\t69.06\nHLA-DRB1*03:01\t1\t1\t15\tFLEGVSGAT\tMSNRDFLEGVSGATW\t15398.6\t72.13\n')
AssertionError: 'allele\tseq_num\tstart\tend\tcore_peptide\tpeptide\tic50\tpercentile_rank\n' != 'allele\tseq_num\tstart\tend\tcore_peptide\tpeptide\tic50\tpercentile_rank\nHLA-DRB1*03:01\t1\t8\t22\tTWVDLVLEG\tEGVSGATWVDLVLEG\t3336.2\t37.49\nHLA-DRB1*03:01\t1\t7\t21\tVSGATWVDL\tLEGVSGATWVDLVLE\t8383.4\t56.73\nHLA-DRB1*03:01\t1\t6\t20\tVSGATWVDL\tFLEGVSGATWVDLVL\t9927.8\t60.7\nHLA-DRB1*03:01\t1\t4\t18\tFLEGVSGAT\tRDFLEGVSGATWVDL\t12159.0\t65.84\nHLA-DRB1*03:01\t1\t5\t19\tVSGATWVDL\tDFLEGVSGATWVDLV\t12588.1\t66.77\nHLA-DRB1*03:01\t1\t3\t17\tFLEGVSGAT\tNRDFLEGVSGATWVD\t12966.4\t67.52\nHLA-DRB1*03:01\t1\t2\t16\tFLEGVSGAT\tSNRDFLEGVSGATWV\t13753.3\t69.06\nHLA-DRB1*03:01\t1\t1\t15\tFLEGVSGAT\tMSNRDFLEGVSGATW\t15398.6\t72.13\n'

======================================================================
FAIL: test_recommended (__main__.Test_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./configure.py", line 24, in test_recommended
    self.assertEqual(result, 'allele\tseq_num\tstart\tend\tpeptide\tmethod\tconsensus_percentile_rank\tcomblib_core\tcomblib_score\tcomblib_rank\tsmm_align_core\tsmm_align_ic50\tsmm_align_rank\tnn_align_core\tnn_align_ic50\tnn_align_rank\tnetmhciipan_core\tnetmhciipan_ic50\tnetmhciipan_rank\tsturniolo_core\tsturniolo_score\tsturniolo_rank\nHLA-DRB1*03:01\t1\t1\t15\tMSNRDFLEGVSGATW\tSMM-NN-Sturniolo\t28.13\t-\t-\t-\tFLEGVSGAT\t9343.0\t19.11\tFLEGVSGAT\t15398.6\t72.13\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t2\t16\tSNRDFLEGVSGATWV\tSMM-NN-Sturniolo\t28.13\t-\t-\t-\tFLEGVSGAT\t8986.0\t18.32\tFLEGVSGAT\t13753.3\t69.06\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t3\t17\tNRDFLEGVSGATWVD\tSMM-NN-Sturniolo\t28.13\t-\t-\t-\tFLEGVSGAT\t9085.0\t18.56\tFLEGVSGAT\t12966.4\t67.52\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t4\t18\tRDFLEGVSGATWVDL\tSMM-NN-Sturniolo\t28.13\t-\t-\t-\tFLEGVSGAT\t8523.0\t17.28\tFLEGVSGAT\t12159.0\t65.84\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t8\t22\tEGVSGATWVDLVLEG\tSMM-NN-Sturniolo\t28.63\t-\t-\t-\tVSGATWVDL\t5932.0\t11.7\tTWVDLVLEG\t3336.2\t37.49\t-\t-\t-\tVSGATWVDL\t-1.34\t28.63\nHLA-DRB1*03:01\t1\t6\t20\tFLEGVSGATWVDLVL\tSMM-NN-Sturniolo\t36.26\t-\t-\t-\tFLEGVSGAT\t18363.0\t36.26\tVSGATWVDL\t9927.8\t60.7\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t5\t19\tDFLEGVSGATWVDLV\tSMM-NN-Sturniolo\t37.04\t-\t-\t-\tFLEGVSGAT\t18841.0\t37.04\tVSGATWVDL\t12588.1\t66.77\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t7\t21\tLEGVSGATWVDLVLE\tSMM-NN-Sturniolo\t48.66\t-\t-\t-\tSGATWVDLV\t26621.0\t48.66\tVSGATWVDL\t8383.4\t56.73\t-\t-\t-\tVSGATWVDL\t-1.34\t28.63\n')
AssertionError: 'allele\tseq_num\tstart\tend\tpeptide\tmethod\tconsensus_percentile_rank\tcomblib_core\tcomblib_score\tcomblib_rank\tsmm_align_core\tsmm_align_ic50\tsmm_align_rank\tnn_align_core\tnn_align_ic50\tnn_align_rank\tnetmhciipan_core\tnetmhciipan_ic50\tnetmhciipan_rank\tsturniolo_core\tsturniolo_score\tsturniolo_rank\nHLA-DRB1*03:01\t1\t8\t22\tEGVSGATWVDLVLEG\tSMM-Sturniolo\t20.165\t-\t-\t-\tVSGATWVDL\t5932.0\t11.7\t-\t-\t-\t-\t-\t-\tVSGATWVDL\t-1.34\t28.63\nHLA-DRB1*03:01\t1\t4\t18\tRDFLEGVSGATWVDL\tSMM-Sturniolo\t22.705\t-\t-\t-\tFLEGVSGAT\t8523.0\t17.28\t-\t-\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t2\t16\tSNRDFLEGVSGATWV\tSMM-Sturniolo\t23.225\t-\t-\t-\tFLEGVSGAT\t8986.0\t18.32\t-\t-\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t3\t17\tNRDFLEGVSGATWVD\tSMM-Sturniolo\t23.345\t-\t-\t-\tFLEGVSGAT\t9085.0\t18.56\t-\t-\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t1\t15\tMSNRDFLEGVSGATW\tSMM-Sturniolo\t23.62\t-\t-\t-\tFLEGVSGAT\t9343.0\t19.11\t-\t-\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t6\t20\tFLEGVSGATWVDLVL\tSMM-Sturniolo\t32.195\t-\t-\t-\tFLEGVSGAT\t18363.0\t36.26\t-\t-\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t5\t19\tDFLEGVSGATWVDLV\tSMM-Sturniolo\t32.585\t-\t-\t-\tFLEGVSGAT\t18841.0\t37.04\t-\t-\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t7\t21\tLEGVSGATWVDLVLE\tSMM-Sturniolo\t38.645\t-\t-\t-\tSGATWVDLV\t26621.0\t48.66\t-\t-\t-\t-\t-\t-\tVSGATWVDL\t-1.34\t28.63\n' != 'allele\tseq_num\tstart\tend\tpeptide\tmethod\tconsensus_percentile_rank\tcomblib_core\tcomblib_score\tcomblib_rank\tsmm_align_core\tsmm_align_ic50\tsmm_align_rank\tnn_align_core\tnn_align_ic50\tnn_align_rank\tnetmhciipan_core\tnetmhciipan_ic50\tnetmhciipan_rank\tsturniolo_core\tsturniolo_score\tsturniolo_rank\nHLA-DRB1*03:01\t1\t1\t15\tMSNRDFLEGVSGATW\tSMM-NN-Sturniolo\t28.13\t-\t-\t-\tFLEGVSGAT\t9343.0\t19.11\tFLEGVSGAT\t15398.6\t72.13\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t2\t16\tSNRDFLEGVSGATWV\tSMM-NN-Sturniolo\t28.13\t-\t-\t-\tFLEGVSGAT\t8986.0\t18.32\tFLEGVSGAT\t13753.3\t69.06\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t3\t17\tNRDFLEGVSGATWVD\tSMM-NN-Sturniolo\t28.13\t-\t-\t-\tFLEGVSGAT\t9085.0\t18.56\tFLEGVSGAT\t12966.4\t67.52\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t4\t18\tRDFLEGVSGATWVDL\tSMM-NN-Sturniolo\t28.13\t-\t-\t-\tFLEGVSGAT\t8523.0\t17.28\tFLEGVSGAT\t12159.0\t65.84\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t8\t22\tEGVSGATWVDLVLEG\tSMM-NN-Sturniolo\t28.63\t-\t-\t-\tVSGATWVDL\t5932.0\t11.7\tTWVDLVLEG\t3336.2\t37.49\t-\t-\t-\tVSGATWVDL\t-1.34\t28.63\nHLA-DRB1*03:01\t1\t6\t20\tFLEGVSGATWVDLVL\tSMM-NN-Sturniolo\t36.26\t-\t-\t-\tFLEGVSGAT\t18363.0\t36.26\tVSGATWVDL\t9927.8\t60.7\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t5\t19\tDFLEGVSGATWVDLV\tSMM-NN-Sturniolo\t37.04\t-\t-\t-\tFLEGVSGAT\t18841.0\t37.04\tVSGATWVDL\t12588.1\t66.77\t-\t-\t-\tFLEGVSGAT\t-1.2\t28.13\nHLA-DRB1*03:01\t1\t7\t21\tLEGVSGATWVDLVLE\tSMM-NN-Sturniolo\t48.66\t-\t-\t-\tSGATWVDLV\t26621.0\t48.66\tVSGATWVDL\t8383.4\t56.73\t-\t-\t-\tVSGATWVDL\t-1.34\t28.63\n'

----------------------------------------------------------------------
Ran 9 tests in 59.491s

FAILED (failures=4)
```

thank you !

**Comment by susannasiebert** [comment]
As this is an error with IEDB and not with pVACtools, I would recommend making an issue on IEDB's help forum (help.iedb.org). Alternatively, you might want to try our Docker container (griffithlab/pvactools) which comes with IEDB pre-installed.

**Comment by zhangyafeng1** [comment]
I am sorry to reply too late. 
I don't have permission to use Docker.  
Do you think it will be caused by the version of perl ?  Because it prompts " Perl lib version (5.18.2) doesn't match executable  version (v5.16.3) "

And I tried the new version of mhc_ii  (version : IEDB_MHC_II-2.22.1.tar.gz) , when I run ./configure.py , There is only one error left.. as follows:

======================================================================
FAIL: test_netmhciipan (__main__.Test_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./configure.py", line 34, in test_netmhciipan
    self.assertEqual(result, 'allele\tseq_num\tstart\tend\tlength\tcore_peptide\tpeptide\tic50\tpercentile_rank\tadjusted_rank\nHLA-DRB1*03:01\t1\t8\t22\t15\tTWVDLVLEG\tEGVSGATWVDLVLEG\t5141.52\t68.0\t68.00\nHLA-DRB1*03:01\t1\t7\t21\t15\tVSGATWVDL\tLEGVSGATWVDLVLE\t7834.87\t81.0\t81.00\nHLA-DRB1*03:01\t1\t6\t20\t15\tVSGATWVDL\tFLEGVSGATWVDLVL\t9153.53\t85.0\t85.00\nHLA-DRB1*03:01\t1\t1\t15\t15\tSNRDFLEGV\tMSNRDFLEGVSGATW\t10147.65\t88.0\t88.00\nHLA-DRB1*03:01\t1\t5\t19\t15\tVSGATWVDL\tDFLEGVSGATWVDLV\t10676.91\t89.0\t89.00\nHLA-DRB1*03:01\t1\t4\t18\t15\tLEGVSGATW\tRDFLEGVSGATWVDL\t10863.48\t89.0\t89.00\nHLA-DRB1*03:01\t1\t2\t16\t15\tLEGVSGATW\tSNRDFLEGVSGATWV\t11487.24\t90.0\t90.00\nHLA-DRB1*03:01\t1\t3\t17\t15\tLEGVSGATW\tNRDFLEGVSGATWVD\t12561.68\t92.0\t92.00\n'  )
AssertionError: 'allele\tseq_num\tstart\tend\tlength\tcore_peptide\tpeptide\tic50\tpercentile_rank\tadjusted_rank\n' != 'allele\tseq_num\tstart\tend\tlength\tcore_peptide\tpeptide\tic50\tpercentile_rank\tadjusted_rank\nHLA-DRB1*03:01\t1\t8\t22\t15\tTWVDLVLEG\tEGVSGATWVDLVLEG\t5141.52\t68.0\t68.00\nHLA-DRB1*03:01\t1\t7\t21\t15\tVSGATWVDL\tLEGVSGATWVDLVLE\t7834.87\t81.0\t81.00\nHLA-DRB1*03:01\t1\t6\t20\t15\tVSGATWVDL\tFLEGVSGATWVDLVL\t9153.53\t85.0\t85.00\nHLA-DRB1*03:01\t1\t1\t15\t15\tSNRDFLEGV\tMSNRDFLEGVSGATW\t10147.65\t88.0\t88.00\nHLA-DRB1*03:01\t1\t5\t19\t15\tVSGATWVDL\tDFLEGVSGATWVDLV\t10676.91\t89.0\t89.00\nHLA-DRB1*03:01\t1\t4\t18\t15\tLEGVSGATW\tRDFLEGVSGATWVDL\t10863.48\t89.0\t89.00\nHLA-DRB1*03:01\t1\t2\t16\t15\tLEGVSGATW\tSNRDFLEGVSGATWV\t11487.24\t90.0\t90.00\nHLA-DRB1*03:01\t1\t3\t17\t15\tLEGVSGATW\tNRDFLEGVSGATWVD\t12561.68\t92.0\t92.00\n'
----------------------------------------------------------------------
Ran 9 tests in 129.192s
FAILED (failures=1)
 
From the error report, it seems that the netmhciipan algorithm does not predict the location.
So I don't know what is the cause of the error.  My reason?  or the reason for the software ?
I don't know how to solve this problem , I am very grateful that you can help me.

**Comment by susannasiebert** [comment]
I’m very sorry but we are unable to provide assistance with IEDB package installation errors. Please contact IEDB directly at the website I linked to previously.

**Comment by susannasiebert** [comment]
pVACtools can also be run without a standalone IEDB installation although it is not recommended for large datasets. However, if you are unable to install IEDB successfully you can at least give it a try and see if that works for you.

**Comment by zhangyafeng1** [comment]
Thank you very much , I will look for other solutions

**Comment by zhangyafeng1** [comment]
The version of Perl it needs is 5.10.1 . When I use Perl 5.10.1, it does not report a error.
