### ISSUE TITLE
subprocess.CalledProcessError AND TypeError: __init__() missing 1 required positional argument: 'cmd'

### ISSUE THREAD

**Issue by zhangyafeng1** [griffithlab/pVACtools#466]
hello, my code is 
```
/bin/bash -c "conda init"
pvacseq run \
 vcf-readcount-annotator.vcf \
 s_18T135 \
 HLA-A*02:01 \
 NetMHCcons\
 /path/pvacseq_run \
 -e 8 \
 --iedb-install-directory path_iedb/ \
```

but it has a error:
```
Executing MHC Class I predictions
Converting .vcf to TSV
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Splitting TSV into smaller chunks - Entries 101-200
Splitting TSV into smaller chunks - Entries 201-300
Splitting TSV into smaller chunks - Entries 301-400
Splitting TSV into smaller chunks - Entries 401-500
Splitting TSV into smaller chunks - Entries 501-540
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-200
Generating Variant Peptide FASTA and Key Files - Entries 201-400
Generating Variant Peptide FASTA and Key Files - Entries 401-600
Generating Variant Peptide FASTA and Key Files - Entries 601-800
Generating Variant Peptide FASTA and Key Files - Entries 801-1000
Generating Variant Peptide FASTA and Key Files - Entries 1001-1080
Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHCcons - File /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pvacseq_run/MHC_Class_I/tmp/s_18T135.netmhccons.HLA-A*02:01.8.tsv_1-200
ERROR:netmhccons_1_1_executable.netmhccons_1_1_python_interface:len(peptide_list) != len(scores) -- 14 != 0

Traceback (most recent call last):
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/predict_binding.py", line 452, in <module>
    Prediction().main()
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/predict_binding.py", line 444, in main
    self.commandline_input(args)
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/predict_binding.py", line 107, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.as_amino_acid_text())
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/seqpredictor.py", line 819, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/seqpredictor.py", line 406, in predict_sequence
    scores = predict_netmhccons(sequence, (allele_name_or_sequence, self.length))
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/../method/netmhccons-1.1-executable/netmhccons_1_1_executable/netmhccons_1_1_python_interface.py", line 19, in predict_sequence
    scores = predict_peptide_list(peptide_list, allele_length_pair)
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/../method/netmhccons-1.1-executable/netmhccons_1_1_executable/netmhccons_1_1_python_interface.py", line 81, in predict_peptide_list
    raise Exception(msg)
Exception: len(peptide_list) != len(scores) -- 14 != 0
An exception occured in thread 0: (<class 'subprocess.CalledProcessError'>, Command '['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/predict_binding.py netmhccons HLA-A*02:01 8 /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pvacseq_run/MHC_Class_I/tmp/s_18T135_21.fa.split_1-200']' returned non-zero exit status 1.).
Traceback (most recent call last):
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/lib/pipeline.py", line 342, in call_iedb
    lib.call_iedb.main(arguments)
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/lib/call_iedb.py", line 55, in main
    raise err
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/lib/call_iedb.py", line 50, in main
    (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/lib/prediction_class.py", line 57, in predict
    response = run(['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python {}'.format(arguments)], stdout=response_fh, check=True)
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pVACtools/mhc_i/src/predict_binding.py netmhccons HLA-A*02:01 8 /ifs/TJPROJ3/HWEU/USER/zhangyafeng/pvacseq_run/MHC_Class_I/tmp/s_18T135_21.fa.split_1-200']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/bin/pvacseq", line 10, in <module>
    sys.exit(main())
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/tools/pvacseq/run.py", line 164, in main
    pipeline.execute()
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/lib/pipeline.py", line 440, in execute
    self.call_iedb(chunks)
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/lib/pipeline.py", line 343, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/ifs/TJPROJ3/HWEU/USER/zhangyafeng/sorftware/anaconda3/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: __init__() missing 1 required positional argument: 'cmd'
```

I don't know why，Is it because I installed less ？
Thank you for your help.
best regards!

**Comment by susannasiebert** [comment]
This appears to be a common error with NetMHCcons but we haven't been able to figure out what exactly causes it. Our best guess is that NetMHCcons runs out of memory while making predictions and thus returns no results. You might be able to get around this by reducing your `--fasta-size` and/or `--downstream-sequence-length` or running on a machine with more RAM.

**Comment by susannasiebert** [comment]
Since there hasn't been any activity on this ticket, I assume that my recommendation solved this problem. Please feel free to reopen should you still run into issues.
