### ISSUE TITLE
Upgrade to latest vaxrank version

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#493]
The current vaxrank version (1.2.0) is incompatible with our current usage in pVACtools:
```
  File "/home/travis/build/griffithlab/pVACtools/lib/calculate_manufacturability.py", line 8, in __new__
    return VaccinePeptideBase.__new__(
NameError: name 'VaccinePeptideBase' is not defined
```
I pinned vaxrank to the latest know working version for now but we should upgrade, if possible.

**Comment by wt12318** [comment]
I have encountered the problem:
```
Executing MHC Class I predictions
Converting .vcf to TSV
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-16
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-32
Completed
Making binding predictions on Allele HLA-A*32:01 and Epitope Length 9 with Method NetMHCpan - File /public/home/wangshx/wt/calnb/pvacseq_test/TCGA-02-0047-01A-01D-1490-08/MHC_Class_I/tmp/TCGA-02-0047-01A-01D-1490-08.netmhcpan.HLA-A*32:01.9.tsv_1-32
Making binding predictions on Allele HLA-B*15:01 and Epitope Length 9 with Method NetMHCpan - File /public/home/wangshx/wt/calnb/pvacseq_test/TCGA-02-0047-01A-01D-1490-08/MHC_Class_I/tmp/TCGA-02-0047-01A-01D-1490-08.netmhcpan.HLA-B*15:01.9.tsv_1-32
Making binding predictions on Allele HLA-C*03:03 and Epitope Length 9 with Method NetMHCpan - File /public/home/wangshx/wt/calnb/pvacseq_test/TCGA-02-0047-01A-01D-1490-08/MHC_Class_I/tmp/TCGA-02-0047-01A-01D-1490-08.netmhcpan.HLA-C*03:03.9.tsv_1-32
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 9 with Method NetMHCpan - File /public/home/wangshx/wt/calnb/pvacseq_test/TCGA-02-0047-01A-01D-1490-08/MHC_Class_I/tmp/TCGA-02-0047-01A-01D-1490-08.netmhcpan.HLA-A*02:01.9.tsv_1-32
Making binding predictions on Allele HLA-C*03:03 and Epitope Length 9 with Method NetMHCpan - File /public/home/wangshx/wt/calnb/pvacseq_test/TCGA-02-0047-01A-01D-1490-08/MHC_Class_I/tmp/TCGA-02-0047-01A-01D-1490-08.netmhcpan.HLA-C*03:03.9.tsv_1-32 - Completed
Making binding predictions on Allele HLA-A*32:01 and Epitope Length 9 with Method NetMHCpan - File /public/home/wangshx/wt/calnb/pvacseq_test/TCGA-02-0047-01A-01D-1490-08/MHC_Class_I/tmp/TCGA-02-0047-01A-01D-1490-08.netmhcpan.HLA-A*32:01.9.tsv_1-32 - Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 9 with Method NetMHCpan - File /public/home/wangshx/wt/calnb/pvacseq_test/TCGA-02-0047-01A-01D-1490-08/MHC_Class_I/tmp/TCGA-02-0047-01A-01D-1490-08.netmhcpan.HLA-A*02:01.9.tsv_1-32 - Completed
Making binding predictions on Allele HLA-B*15:01 and Epitope Length 9 with Method NetMHCpan - File /public/home/wangshx/wt/calnb/pvacseq_test/TCGA-02-0047-01A-01D-1490-08/MHC_Class_I/tmp/TCGA-02-0047-01A-01D-1490-08.netmhcpan.HLA-B*15:01.9.tsv_1-32 - Completed
Parsing binding predictions for Allele HLA-A*02:01 and Epitope Length 9 - Entries 1-32
Parsing prediction file for Allele HLA-A*02:01 and Epitope Length 9 - Entries 1-32
Parsing prediction file for Allele HLA-A*02:01 and Epitope Length 9 - Entries 1-32 - Completed
Parsing binding predictions for Allele HLA-A*32:01 and Epitope Length 9 - Entries 1-32
Parsing prediction file for Allele HLA-A*32:01 and Epitope Length 9 - Entries 1-32
Parsing prediction file for Allele HLA-A*32:01 and Epitope Length 9 - Entries 1-32 - Completed
Parsing binding predictions for Allele HLA-B*15:01 and Epitope Length 9 - Entries 1-32
Parsing prediction file for Allele HLA-B*15:01 and Epitope Length 9 - Entries 1-32
Parsing prediction file for Allele HLA-B*15:01 and Epitope Length 9 - Entries 1-32 - Completed
Parsing binding predictions for Allele HLA-C*03:03 and Epitope Length 9 - Entries 1-32
Parsing prediction file for Allele HLA-C*03:03 and Epitope Length 9 - Entries 1-32
Parsing prediction file for Allele HLA-C*03:03 and Epitope Length 9 - Entries 1-32 - Completed
Combining Parsed Prediction Files
Completed
Calculating Manufacturability Metrics
Traceback (most recent call last):
  File "/public/home/liuxs/anaconda3/envs/neopipeline/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/public/home/liuxs/anaconda3/envs/neopipeline/lib/python3.5/site-packages/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/public/home/liuxs/anaconda3/envs/neopipeline/lib/python3.5/site-packages/tools/pvacseq/run.py", line 164, in main
    pipeline.execute()
  File "/public/home/liuxs/anaconda3/envs/neopipeline/lib/python3.5/site-packages/lib/pipeline.py", line 472, in execute
    PostProcessor(**post_processing_params).execute()
  File "/public/home/liuxs/anaconda3/envs/neopipeline/lib/python3.5/site-packages/lib/post_processor.py", line 29, in execute
    self.calculate_manufacturability()
  File "/public/home/liuxs/anaconda3/envs/neopipeline/lib/python3.5/site-packages/lib/post_processor.py", line 50, in calculate_manufacturability
    CalculateManufacturability(self.input_file, self.manufacturability_fh.name, self.file_type).execute()
  File "/public/home/liuxs/anaconda3/envs/neopipeline/lib/python3.5/site-packages/lib/calculate_manufacturability.py", line 76, in execute
    peptide = PvacpeptideVaccinePeptide(sequence)
  File "/public/home/liuxs/anaconda3/envs/neopipeline/lib/python3.5/site-packages/lib/calculate_manufacturability.py", line 8, in __new__
    return VaccinePeptideBase.__new__(
NameError: name 'VaccinePeptideBase' is not defined
```

**Comment by susannasiebert** [comment]
@wt12318 You will need to manually downgrade the vaxrank package to an older version (e.g., by running `pip install vaxrank==1.0.2`)

**Comment by wt12318** [comment]
thanks
