### ISSUE TITLE
Pvacseq test run of Getting started error

### ISSUE THREAD

**Issue by jeongmeani** [griffithlab/pVACtools#507]
Hi, 
a few days ago, i have installed Pvactools and got test run that Pvactools homepage guide "Getting started". https://pvactools.readthedocs.io/en/latest/pvacseq/getting_started.html
i referred this code
`/pvacseq_example_data/input.vcf \
Test \
HLA-A*02:01,HLA-B*35:01,DRB1*11:01 \
MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \
/pvacseq_output_data \
-e 8,9,10
--iedb-install-directory /opt/iedb`

but it gave me this error.

> Traceback (most recent call last):
>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/lib/pipeline.py", line 343, in 
> call_iedb
>  lib.call_iedb.main(arguments)
>  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/lib/call_iedb.py", line 62, in main
>  tmp_output_filehandle.write(response_text)
> TypeError: a bytes-like object is required, not 'NoneType'

so i checked call_iedb.py script and prediction_class.py, i find something.
line 45 of prediction_class.py, there is `if line.startswith(b"allele"):` code.
but the input file contents are like below

> b'HLA-DRB1*11:01\t34\t802\t816\tPPCAVCIGH\tSPEPSQPPCAVCIGH\t29283.0\t99.21' 
> b'HLA-DRB1*11:01\t34\t843\t857\tPESEPPHHE\tPESEPPHHEPPYIPP\t29636.2\t99.29'

so i think that lines were skipped to `else` and return nothing.

i wonder whether i have installed Pvactools and iedb as wrong way or something else?

Best Regards
Jeongmin

**Comment by susannasiebert** [comment]
Hi Jeongmin,
It looks like one of the class II prediction files is missing its header. Can you please attach the full prediction file and let us know the name of the file? This will inform which prediction algorithm produced this output.
What version of IEDB do you have installed? And just to confirm, this is a standalone installation, not the Docker container, correct?
Thanks,
Susanna

**Comment by jeongmeani** [comment]
Hi, Susanna.
Umm.. what is prediction file exactly?
yes! i have installed standalone installation not the Docker container.
and IEDB version is that MHC-I is 2.19.2 and MHC-II is 2.17.6

my detail analysis step is below.
1) `pvacseq download_example_data ./ `
2) `pvacseq run \ 
./pvacseq_example_data/input.vcf \ 
Test \ 
HLA-A*02:01,HLA-B*35:01,DRB1*11:01 \ 
MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \
./pvacseq_output_data \
-e 8,9,10
--iedb-install-directory /data/ref/iedb`
3) and got error message, so i run only call_iedb.py like below
`Python /call_iedb.py /data/tools/pvacseq_example_data/pvacseq_output_data/MHC_Class_II/tmp/Test_31.fa.split_1-128 /data/tools/pvacseq_example_data/pvacseq_output_data/MHC_Class_II/tmp/Test.nn_align.DRB1*11:01.15.tsv_1-128 NNalign DRB1*11:01 -r 2 -e /data/ref/iedb/mhc_ii/mhc_II_binding.py`
4) this printed same error message 
> TypeError: a bytes-like object is required, not 'NoneType'
5) So i open prediction_class.py and on this script, **response variable get mhc_II_binding.py output**

**i think this response variable have no its header you said above.**
what can i do?
would i attach out_directory/tmp files?

Thanks for your helping.

Best regards
Jeongmin

**Comment by susannasiebert** [comment]
No need to attach the tmp directory. It looks like you were able to identify that NNalign is the prediction algorithm resulting in this error. I will try to reproduce this error on my end.

**Comment by jeongmeani** [comment]
Ok!
when you reproduce error and get to know how to fix this, please let me know.

Best Regards.
Jeongmin

**Comment by susannasiebert** [comment]
Unfortunately, I'm unable to reproduce this issue. I'm using the pVACtools docker container, which has the same versions of IEDB MHC II (2.17.6) installed. Do you mind attaching the `/data/tools/pvacseq_example_data/pvacseq_output_data/MHC_Class_II/tmp/Test.nn_align.DRB1*11:01.15.tsv_1-128` file to this ticket?

**Comment by jeongmeani** [comment]
OK!
i have run that code you request.
it prints many lines including header.  i post some of lines.

> allele  seq_num start   end     core_peptide    peptide ic50    percentile_rank
> HLA-DRB1*11:01  47      10      24      FLASTRLTS       GWEFLASTRLTSELN 4.8     0.21
> HLA-DRB1*11:01  48      10      24      FLAFTRLTS       GWEFLAFTRLTSELN 5.6     0.34
> HLA-DRB1*11:01  47      9       23      FLASTRLTS       LGWEFLASTRLTSEL 5.8     0.38
> HLA-DRB1*11:01  47      11      25      FLASTRLTS       WEFLASTRLTSELNF 6.1     0.44
> HLA-DRB1*11:01  48      11      25      FLAFTRLTS       WEFLAFTRLTSELNF 6.7     0.56
> HLA-DRB1*11:01  48      9       23      FLAFTRLTS       LGWEFLAFTRLTSEL 7.2     0.67
> HLA-DRB1*11:01  47      12      26      FLASTRLTS       EFLASTRLTSELNFL 7.7     0.78
> HLA-DRB1*11:01  48      12      26      FLAFTRLTS       EFLAFTRLTSELNFL 7.8     0.81
> HLA-DRB1*11:01  47      8       22      FLASTRLTS       ALGWEFLASTRLTSE 8.4     0.95
> HLA-DRB1*11:01  48      13      27      FLAFTRLTS       FLAFTRLTSELNFLL 9.4     1.18
> HLA-DRB1*11:01  47      13      27      FLASTRLTS       FLASTRLTSELNFLL 10.5    1.44
> HLA-DRB1*11:01  48      8       22      FLAFTRLTS       ALGWEFLAFTRLTSE 11.1    1.58

this lines have header you said yesterday.
but why `if line.startswith(b"allele"):`  in prediction_class.py doesn't catch that header?

Thanks for your helping.

Best Regards.
Jeongmin

**Comment by jeongmeani** [comment]
after running mhc_ii/mhc_II_binding.py,
i looked into this in detail.
i get something strange.

On prediction_class.py, i add `print(response_fh.read())` in line 59.
and the code prints below.

>b']0;root@penta01:/data/tools/pvacseq_example_data\x07\x1b]0;root@penta01:/data/tools/pvacseq_example_data\x07allele\tseq_num\tstart\tend\tcore_peptide\tpeptide\tic50\tpercentile_rank\nHLA-DRB1*11:01\t47\t10\t24\tFLASTRLTS\tGWEFLASTRLTSELN\t4.8\t0.21\n
HLA-DRB1*11:01\t48\t10\t24\tFLAFTRLTS\tGWEFLAFTRLTSELN\t5.6\t0.34\n
HLA-DRB1*11:01\t47\t9\t23\tFLASTRLTS\tLGWEFLASTRLTSEL\t5.8\t0.38\n
HLA-DRB1*11:01\t47\t11\t25\tFLASTRLTS\tWEFLASTRLTSELNF\t6.1\t0.44\n
HLA-DRB1*11:01\t48\t11\t25\tFLAFTRLTS\tWEFLAFTRLTSELNF\t6.7\t0.56\n
HLA-DRB1*11:01\t48\t9\t23\tFLAFTRLTS\tLGWEFLAFTRLTSEL\t7.2\t0.67\n
HLA-DRB1*11:01\t47\t12\t26\tFLASTRLTS\tEFLASTRLTSELNFL\t7.7\t0.78\n

this header is strange to have my working directory path.
so i think because of that, error occurs.

is my server setting wrong?
or 
1. `response = run(['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python {}'.format(arguments)], stdout=response_fh, check=True)`

2. `response_fh.seek(0)`

should this codes be modified?

Best Regards.
Jeongmin

**Comment by susannasiebert** [comment]
Do you have anything in your bash configuration that prepends your current working directory to the prompt?

**Comment by jeongmeani** [comment]
I could not find any bash configuration that influences this situation.
So i modify some code in prediction_class.py like below
In predict funtion
```          
iedb_cmd=['python2']
for i in arguments.split(' '):
      iedb_cmd.append(i)
response = run(iedb_cmd, stdout=PIPE)
response_fh.seek(1)
# response_text = self.filter_response(response_fh.read())
response_text = self.filter_response(response.stdout) # jmkim append
response_fh.close()
return (response_text, 'wb')
```

it works successfully!

very thank you for kindly your reply so far.

Best Regards.
Jeongmin

**Comment by susannasiebert** [comment]
Your solution works if we can be sure that the IEDB output files always output exactly one leading empty line. I will add this issue to the 2.0 milestone and think about reworking the filtering logic.

I'm a bit concerned, that the extra path information might still show up in the intermediate files and would mess with downstream parsing steps. You didn't encounter any downstream errors? I would be interested to see what the header lines of any of the intermediate files from IEDB look like after they get saved. Could you attach one of the intermediate files to this ticket? For example `pvacseq_output_data/MHC_Class_II/tmp/Test.nn_align.DRB1*11:01.15.tsv_1-128`. You will need to run with `-k` flag so that the tmp files don't get deleted upon a successful run.

**Comment by jeongmeani** [comment]
Oh, Sorry for late reply.

i did not encounter any downstream error.
and i attach the intermediate files to be transformed to TXT format. 

[Test.DRB1%2A11%3A01.15.parsed.tsv_1-128.txt](https://github.com/griffithlab/pVACtools/files/4367137/Test.DRB1.2A11.3A01.15.parsed.tsv_1-128.txt)
[Test.MHCnuggetsII.DRB1%2A11%3A01.15.tsv_1-128.txt](https://github.com/griffithlab/pVACtools/files/4367139/Test.MHCnuggetsII.DRB1.2A11.3A01.15.tsv_1-128.txt)
[Test.nn_align.DRB1%2A11%3A01.15.tsv_1-128.txt](https://github.com/griffithlab/pVACtools/files/4367140/Test.nn_align.DRB1.2A11.3A01.15.tsv_1-128.txt)
[Test.smm_align.DRB1%2A11%3A01.15.tsv_1-128.txt](https://github.com/griffithlab/pVACtools/files/4367141/Test.smm_align.DRB1.2A11.3A01.15.tsv_1-128.txt)

and if you catch any strange things. please tell me!

Thank you for your helping.

Best Regards.
Jeongmin
