### ISSUE TITLE
pVACseq error during Class II prediction [__init__() missing 1 required positional argument: 'cmd']

### ISSUE THREAD

**Issue by ahwanpandey** [griffithlab/pVACtools#562]
Issue related to:
https://github.com/griffithlab/pVACtools/issues/411

Hi @susannasiebert

I have gotten some time again to work on neoantigen prediction for our data. I am running version 1.5.7 and the issues still persists. But I think I have narrowed down the issues to some prediction tools. Note that the issues are only for MHC Class II predictions.

1) This is the full command that I am trying to run. It shows the "Unable to open(r) file" messages and also errors out without completing:

```
# ------------------------
THE COMMAND
#------------------------

pvactools.sif pvacseq run \
AN_T_MAOC00037-3-8_N_MAOC00037-5-7.pvacseq.VEP.peptides.vcf \
MAOC00037-3-8 \
DPA1*01:03,DPB1*04:01,DPB1*31:01,DPA1*01:03-DPB1*04:01,DPA1*01:03-DPB1*31:01,DQA1*01:02,DQA1*01:03,DQB1*06:02,DQB1*06:03,DQA1*01:02-DQB1*0$
MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC NetMHCIIpan NetMHCcons NetMHCpan PickPocket SMM SMMPMBEC SMMalign \
./test \
-e 8,9,10,11 \
--normal-sample-name MAOC00037-5-7 \
--iedb-install-directory /opt/iedb \
--n-threads 8 \
--binding-threshold 500 \
--top-score-metric median \
--peptide-sequence-length 21 \
--additional-report-columns sample_name \
--fasta-size 1000 \
--downstream-sequence-length 1000 \
--minimum-fold-change 0.0 \
--normal-cov 0 \
--tdna-cov 0 \
--trna-cov 0 \
--normal-vaf 0 \
--tdna-vaf  0 \
--trna-vaf 0 \
--expn-val 0 \
--maximum-transcript-support-level 1

#------------------------------
THE ERROR
# -----------------------------

Unable to open(r) file
list index out of range
Making binding predictions on Allele.... etc...
Making binding predictions on Allele.... etc...
An exception occured in thread 7: (<class 'subprocess.CalledProcessError'>, Command '['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python /opt/iedb/mhc_ii/mhc_II_binding.py smm_align DRB1*15:01 /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250']' returned non-zero exit status 1.).
Traceback (most recent call last):
  File "/opt/conda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/run.py", line 192, in main
    pipeline.execute()
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 443, in execute
    self.call_iedb(chunks)
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 343, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/opt/conda/lib/python3.6/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: __init__() missing 1 required positional argument: 'cmd'
```

2) After looking at some of the logs of the above command, I decided to exclude "SMMalign" and "NNalign" and re-run. This time there are no "Unable to open(r) file" messages and there are no errors. This works!

3) Then I ran the command with just SMMalign and DRB1*15:01. This shows the "Unable to open(r) file" messages but completes without errors.

4) Finally, I ran the command with just NNalign and DRB1*15:01. This shows the "Unable to open(r) file" messages and also errors out without completing.

I have run the all the commands with or without multi-threading, and also with RAM from 16GB to 128GB, and with fasta-sizes 200 and 1000. The issues from 1) 3) and 4) persist in all the runs.

I have uploaded the test VCF into Dropbox if you would like to try to run on your end.
https://www.dropbox.com/sh/q34lfczjvg0rp4q/AAAxjHgTb2Z_uTB1M403jB0Pa?dl=0

Thanks for the help.

**Comment by susannasiebert** [comment]
Thank you for the update and for digging into this. I will try to replicate this issue on my end.

**Comment by susannasiebert** [comment]
Unfortunately, I'm unable to reproduce this issue on my end. Can you try to run the call to iedb directly? It would look some thing like this:

**Comment by ahwanpandey** [comment]
Hi @susannasiebert . Thanks for the followup.

I am using the docker version. Our cluster uses singularity to import the docker images (https://singularity.lbl.gov/). So I am guessing the correct way to run the command directly is:

1. Get into the "docker" environment of pvactools by executing `]$ pvactools.sif`
The bash prompt now looks like this
```
Singularity> ls -lah /opt/
total 0
drwxr-xr-x  5 root    root     86 Mar 18 02:03 .
drwxr-xr-x  1 apandey apandey  80 Jun  9 08:19 ..
drwxr-xr-x 14 root    root    307 Jun  9  2018 conda
drwxr-xr-x  4 root    root     81 Mar 18 02:03 iedb
drwxr-xr-x  3 root    root     28 Mar 18 02:19 mhcflurry_data

```
2. Error after running the command (Note: I've broken up the command here but the error is the same even if I run on the same line with ";"
```
Singularity> conda activate pvactools_py27

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="/opt/conda/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^
```
```
Singularity> ls -lah /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250
-rw-rw-r-- 1 apandey apandey 3.7K Jun  3 19:47 /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250

Singularity> python /opt/iedb/mhc_ii/mhc_II_binding.py smm_align DRB1*15:01 /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250
  File "/opt/iedb/mhc_ii/mhc_II_binding.py", line 197
    print "Content-Type: text/html"
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Content-Type: text/html")?
```

**Comment by susannasiebert** [comment]
The second command is failing because the first fails to activate the correct conda environment. The only time I've seen this error when using docker containers is if something in the user's system is overwriting the docker image's environment. That would be something to check with your sys admin.

However, executing everything in one command appears to work so you should try and see if that is possible. Maybe this would work:
```
pvactools.sif  /bin/bash -l -c 'conda activate pvactools_py27; python /opt/iedb/mhc_ii/mhc_II_binding.py smm_align DRB1*15:01 /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250'
```

**Comment by ahwanpandey** [comment]
I ran the command as you suggested. Here is the output

for smm_align
```
]$ pvactools.sif  /bin/bash -l -c 'conda activate pvactools_py27; python /opt/iedb/mhc_ii/mhc_II_binding.py smm_align DRB1*15:01 /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250'
/home/apandey/.bashrc: line 36: module: command not found
/home/apandey/.bashrc: line 37: module: command not found
/home/apandey/.bashrc: line 38: module: command not found
/home/apandey/.bashrc: line 40: module: command not found
/home/apandey/.bashrc: line 42: module: command not found
/home/apandey/.bashrc: line 43: module: command not found
/home/apandey/.bashrc: line 44: module: command not found
/home/apandey/.bashrc: line 45: module: command not found
/home/apandey/.bashrc: line 46: module: command not found
/home/apandey/.bashrc: line 47: module: command not found
/home/apandey/.bashrc: line 48: module: command not found
/home/apandey/.bashrc: line 49: module: command not found
/home/apandey/.bashrc: line 50: module: command not found
/home/apandey/.bashrc: line 51: module: command not found
/home/apandey/.bashrc: line 52: module: command not found
/home/apandey/.bashrc: line 57: module: command not found
/home/apandey/.bashrc: line 58: module: command not found
/home/apandey/.bashrc: line 60: module: command not found
/home/apandey/.bashrc: line 62: module: command not found
/home/apandey/.bashrc: line 63: module: command not found
/home/apandey/.bashrc: line 64: module: command not found
/home/apandey/.bashrc: line 67: mypython: command not found
Unable to open(r) file
list index out of range
```

for nn_align
```
]$ pvactools.sif  /bin/bash -l -c 'conda activate pvactools_py27; python /opt/iedb/mhc_ii/mhc_II_binding.py nn_align DRB1*15:01 /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250'
/home/apandey/.bashrc: line 36: module: command not found
/home/apandey/.bashrc: line 37: module: command not found
/home/apandey/.bashrc: line 38: module: command not found
/home/apandey/.bashrc: line 40: module: command not found
/home/apandey/.bashrc: line 42: module: command not found
/home/apandey/.bashrc: line 43: module: command not found
/home/apandey/.bashrc: line 44: module: command not found
/home/apandey/.bashrc: line 45: module: command not found
/home/apandey/.bashrc: line 46: module: command not found
/home/apandey/.bashrc: line 47: module: command not found
/home/apandey/.bashrc: line 48: module: command not found
/home/apandey/.bashrc: line 49: module: command not found
/home/apandey/.bashrc: line 50: module: command not found
/home/apandey/.bashrc: line 51: module: command not found
/home/apandey/.bashrc: line 52: module: command not found
/home/apandey/.bashrc: line 57: module: command not found
/home/apandey/.bashrc: line 58: module: command not found
/home/apandey/.bashrc: line 60: module: command not found
/home/apandey/.bashrc: line 62: module: command not found
/home/apandey/.bashrc: line 63: module: command not found
/home/apandey/.bashrc: line 64: module: command not found
/home/apandey/.bashrc: line 67: mypython: command not found
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
Unable to open(r) file
allele  seq_num start   end     core_peptide    peptide ic50    percentile_rank
```

**Comment by susannasiebert** [comment]
Can you check what the permissions on the `MAOC00037-3-8_31.fa.split_1-250` file are?

**Comment by ahwanpandey** [comment]
Here are the permissions:

```
]$ ls -l /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250
-rw-rw-r-- 1 apandey apandey 3747 Jun  3 19:47 /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pvactools/test/MHC_Class_II/tmp/MAOC00037-3-8_31.fa.split_1-250
```

I have also update the dropbox link with this file if you want to test the command at your end as well.

**Comment by susannasiebert** [comment]
Unfortunately, I'm unable to reproduce this error when running this on the Docker container. I'm unable to determine if this is something about your system or about running this in singularity. It might be worthwhile to file a ticket with IEDB directly to get some more insights on what might be going on here.

**Comment by susannasiebert** [comment]
@ahwanpandey have you been able to resolve this issue?

**Comment by ahwanpandey** [comment]
@susannasiebert sorry I haven't had the opportunity to test more. Have reverted back to the version that was working for now. Please close the issue if you'd like.
