### ISSUE TITLE
pvacseq isn't compatible in Python 3.8.1

### ISSUE THREAD

**Issue by fortissi2mo** [griffithlab/pVACtools#566]
* pvactools version: 1.5.9
* Python version: 3.8.1
* Operating System:  Linux

**Describe the bug**
I guess that the pvacseq tool is not compatible in Python 3.8.1. Please fix it.

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

**Log Output**
```
$ pvacseq

Traceback (most recent call last):
  File "/opt/Yonsei/python/3.8.1/bin/pvacseq", line 5, in <module>
    from tools.pvacseq.main import main
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/site-packages/tools/pvacseq/__init__.py", line 15, in <module>
    from . import *
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/site-packages/tools/pvacseq/run.py", line 4, in <module>
    from lib.prediction_class import *
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/site-packages/lib/__init__.py", line 28, in <module>
    from . import *
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/site-packages/lib/vector_visualization.py", line 244
    return scheme[count]\
                                      ^
```

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.
No output.

**Expected behavior**
interchanging in the pvacseq

**Comment by susannasiebert** [comment]
I made #568 to resolve this particular error. However, I haven't been able to actually install pVACtools on Python 3.8 because of version conflicts in Python 3.8 + tensorflow + mhcflurry. @fortissi2mo if you could let me know your installation steps, that would be helpful. Without being able to fully install pVACtools I can't guarantee that #568 will resolve all potential errors on our side that prevent a 3.8 installation.

**Comment by susannasiebert** [comment]
1.5.10. is now live and resolves this particular error. I'm closing this issue but please do reopen if you're still having problems with installing pVACtools in Python 3.8
