### ISSUE TITLE
Crashes during the class II prediction process

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/pVACtools#588]
**To Reproduce**
I'm running this in the `susannakiwala/pvactools:2.0.0-alpha.2` container with the command:
```
/opt/conda/bin/pvacseq run --iedb-install-directory /opt/iedb/ --allele-specific-binding-thresholds --netmhc-stab --tdna-vaf 0 --normal-vaf 100 --trna-cov 0 --tdna-cov 0 --normal-cov 0 --trna-vaf 0 --expn-val 0 --binding-threshold 500 -k -t 4 --pass-only M_GC-OxParp_A-OxParp_A_FF_DNA.vep.vcf TUMOR H-2-Db,H-2-Kb,H2-IAb all .
```

Working directory is here on our local filesystem, if you have access:
`/gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_A-OxParp_A_FF_DNA` 

Something comparable happens in every sample I've run it on (similar mouse cell line samples).  Class I predictions work fine, but Class II craps out.

**Log Output**
```
Making binding predictions on Allele H2-IAb and Epitope Length 18 with Method SMMalign - File /gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_A-OxParp_A_FF_DNA/MHC_Class_II/tmp/TUMOR.smm_align.H2-IAb.18.tsv_1-200 - Completed
Making binding predictions on Allele H2-IAb and Epitope Length 12 with Method NNalign - File /gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_A-OxParp_A_FF_DNA/MHC_Class_II/tmp/TUMOR.nn_align.H2-IAb.12.tsv_201-250
Making binding predictions on Allele H2-IAb and Epitope Length 12 with Method NNalign - File /gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_A-OxParp_A_FF_DNA/MHC_Class_II/tmp/TUMOR.nn_align.H2-IAb.12.tsv_201-250 - Completed
An exception occured in thread 0: (<class 'subprocess.CalledProcessError'>, Command '['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python /opt/iedb/mhc_ii/mhc_II_binding.py nn_align H2-IAb /gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_A-OxParp_A_FF_DNA/MHC_Class_II/tmp/TUMOR_31.fa.split_1-200 12']' returned non-zero exit status 137.).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 363, in call_iedb
    lib.call_iedb.main(arguments)
  File "/opt/conda/lib/python3.6/site-packages/lib/call_iedb.py", line 55, in main
    raise err
  File "/opt/conda/lib/python3.6/site-packages/lib/call_iedb.py", line 50, in main
    (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
  File "/opt/conda/lib/python3.6/site-packages/lib/prediction_class.py", line 57, in predict
    response = run(['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python {}'.format(arguments)], stdout=response_fh, check=True)
  File "/opt/conda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python /opt/iedb/mhc_ii/mhc_II_binding.py nn_align H2-IAb /gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_A-OxParp_A_FF_DNA/MHC_Class_II/tmp/TUMOR_31.fa.split_1-200 12']' returned non-zero exit status 137.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/run.py", line 149, in main
    pipeline.execute()
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 465, in execute
    self.call_iedb(chunks)
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 364, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/opt/conda/lib/python3.6/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: __init__() missing 1 required positional argument: 'cmd'

```

This one seems to have happened in NNalign, but I also have examples where it happened in (or just after) NetMHCIIpan:

```Making binding predictions on Allele H2-IAb and Epitope Length 15 with Method NetMHCIIpan - File /gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_F-OxParp_F_FF_DNA/MHC_Class_II/tmp/TUMOR.NetMHCIIpan.H2-IAb.15.tsv_1-200
Making binding predictions on Allele H2-IAb and Epitope Length 15 with Method NetMHCIIpan - File /gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_F-OxParp_F_FF_DNA/MHC_Class_II/tmp/TUMOR.NetMHCIIpan.H2-IAb.15.tsv_1-200 - Completed
An exception occured in thread 1: (<class 'subprocess.CalledProcessError'>, Command '['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python /opt/iedb/mhc_ii/mhc_II_binding.py smm_align H2-IAb /gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_F-OxParp_F_FF_DNA/MHC_Class_II/tmp/TUMOR_31.fa.split_1-200 15']' returned non-zero exit status 137.).
Traceback (most recent call last):
  File "/opt/conda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/run.py", line 149, in main
    pipeline.execute()
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 465, in execute
    self.call_iedb(chunks)
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 364, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/opt/conda/lib/python3.6/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: __init__() missing 1 required positional argument: 'cmd'
```

Full logs are at these paths locally if it helps:

```
/gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_A-OxParp_A_FF_DNA/err.log
/gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_B-OxParp_B_FF_DNA/err.log
/gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_C-OxParp_C_FF_DNA/err.log
/gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_D-OxParp_D_FF_DNA/err.log
/gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_E-OxParp_E_FF_DNA/err.log
/gscmnt/gc2548/gillanders/analyses/mouse_exomes_hawkins/M_GC-OxParp_F-OxParp_F_FF_DNA/err.log
```

**Comment by susannasiebert** [comment]
Could you try and rerun with the latest version `2.0.0-alpha.6` and see if the problem still persists there? I don't expect it to really make a difference since class II has always been more unstable.

Next, could you try and run it without threads?

**Comment by chrisamiller** [comment]
Yeah, running with the newest alpha did the trick, for whatever reason. Jobs with single or multiple cores both completed.  I'll go ahead and resolve this - thanks!
