### ISSUE TITLE
debug mode conflicts with bokeh server, throwing 'Port already in use' error on startup 

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#63]
Added from https://github.com/griffithlab/pVAC-Seq/issues/317

Original requestor: @jmcmichael 

If the pvacseq-api server is started in debug mode, the bokeh server throws 'Port already in use' error:

`pvacseq-api --debug`
```
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with fsevents reloader
2017-07-24 09:50:58,557 Starting Bokeh server version 0.12.4
2017-07-24 09:50:58,565 Starting Bokeh server on port 5006 with applications at paths ['/visualizations']
2017-07-24 09:50:58,565 Starting Bokeh server with process id: 78942
Initializing app configuration
A reboot has occurred since the server was first started
pid's of old pVAC-Seq runs with id's 60 and lower may be innacurate
Visualization server started on PID 78986
Checking files for process 22
[...]
Checking files for process 60
Launching Frontend Server
Initialization complete.  Booting API
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 1211, in <module>
    test(HandlerClass=handler_class, port=args.port, bind=args.bind)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 1185, in test
    with ServerClass(server_address, HandlerClass) as httpd:
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
 * Debugger is active!
 * Debugger pin code: 247-540-431
2017-07-24 09:51:00,748 Starting Bokeh server version 0.12.4
2017-07-24 09:51:00,750 Cannot start Bokeh server, port None is already in use
```

**Comment by susannasiebert** [comment]
Original comment from  @amberzw 

In case other people want to know:

Problem: when app restarts in debug mode the first time, it isn't shutdown first, so the Bokeh server is still up from the first time the app is run.

Temporary solution: in a separate window, find the process running on port 5006 (`lsof -i tcp:5006`) and kill that process (`kill [PID]`). Save any file related to the pvacseq server and the app will automatically reload. The OSError message that the address is already in use will still appear, but a new Bokeh server will be successfully started on port 5006. On any later reloads, the Bokeh server will be shutdown properly and a new one will be successfully started, but the OSError message will still appear (it shouldn't mean anything though I think)

Unfortunately, I haven't found a way to call the @atexit.register functions defined in initialize() in .utils before the first reload into debug mode, or a successful method of hard coding killing a process on port 5006 if the port is in use that isn't specific to an operating system. Maybe someone else might know how to do this?
