### ISSUE TITLE
MHCnuggets error with new pvacseq v2.0 docker

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#645]
* pvactools version: 2.0.0
* Run using docker `griffithlab/pvactools:2.0.0` 

**Describe the bug**
With the latest pvactools 2.0.0 and the associated docker, usage of MHCnuggetsII runs into error. Usage of other prediction algorithms (NetMHC and its variants, class I and II) work all fine and finish without issue. The same inputs (with the appropriate VEP plugins) worked with MHCnuggetsII in pvactools dockers <2.0.0.

**To Reproduce**
ln -s $TMPDIR /tmp/pvacseq && export TMPDIR=/tmp/pvacseq && /usr/local/bin/pvacseq run --iedb-install-directory /opt/iedb --pass-only -e2 12,18 --expn-val 1 --n-threads 8 --normal-cov 5 --normal-sample-name test_normal --normal-vaf 0.05 -p ./phased.vcf.gz --tdna-cov 10 --tdna-vaf 0.25 --trna-cov 10 --trna-vaf 0.25 ./annotated.expression.vcf.gz test_tumor 'DQA1*01:02-DQB1*05:02' MHCnuggetsII pvacseq_predictions

**Log Output**
```
2021-02-14T10:56:17.595148671Z An exception occured in thread 0: (<class 'Exception'>, An error occurred while calling MHCnuggets:
2021-02-14T10:56:17.595171139Z 2021-02-14 10:56:17.301147: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-14T10:56:17.595175890Z 2021-02-14 10:56:17.301180: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-14T10:56:17.595180611Z 2021-02-14 10:56:17.301203: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a5f12f239500): /proc/driver/nvidia/version does not exist
2021-02-14T10:56:17.595184784Z 2021-02-14 10:56:17.301363: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-02-14T10:56:17.595189600Z 2021-02-14 10:56:17.307214: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2999995000 Hz
2021-02-14T10:56:17.595200654Z 2021-02-14 10:56:17.307546: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa0f8000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-14T10:56:17.595204967Z 2021-02-14 10:56:17.307571: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-02-14T10:56:17.595208772Z Traceback (most recent call last):
2021-02-14T10:56:17.595212339Z   File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 76, in <module>
2021-02-14T10:56:17.595215886Z     main()
2021-02-14T10:56:17.595219116Z   File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 59, in main
2021-02-14T10:56:17.595222838Z     predict(args.class_type, tmp_file.name, mhcnuggets_allele(args.allele, args.class_type), output=tmp_output_file.name)
2021-02-14T10:56:17.595226497Z   File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/predict.py", line 54, in predict
2021-02-14T10:56:17.595229636Z     model = mhcnuggets_lstm(input_size)
2021-02-14T10:56:17.595233304Z   File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/models.py", line 55, in mhcnuggets_lstm
2021-02-14T10:56:17.595236822Z     model.add(LSTM(hidden_size, dropout=dropout, recurrent_dropout=dropout))
2021-02-14T10:56:17.595241685Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
2021-02-14T10:56:17.595245381Z     result = method(self, *args, **kwargs)
2021-02-14T10:56:17.595249180Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 213, in add
2021-02-14T10:56:17.595252871Z     output_tensor = layer(self.outputs[0])
2021-02-14T10:56:17.595255760Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 654, in __call__
2021-02-14T10:56:17.595259274Z     return super(RNN, self).__call__(inputs, **kwargs)
2021-02-14T10:56:17.595262581Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
2021-02-14T10:56:17.595266281Z     outputs = call_fn(cast_inputs, *args, **kwargs)
2021-02-14T10:56:17.595269669Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 1112, in call
2021-02-14T10:56:17.595273279Z     inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
2021-02-14T10:56:17.595276763Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 848, in _process_inputs
2021-02-14T10:56:17.595280445Z     initial_state = self.get_initial_state(inputs)
2021-02-14T10:56:17.595283874Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 637, in get_initial_state
2021-02-14T10:56:17.595287596Z     inputs=None, batch_size=batch_size, dtype=dtype)
2021-02-14T10:56:17.595290796Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2481, in get_initial_state
2021-02-14T10:56:17.595297799Z     self, inputs, batch_size, dtype))
2021-02-14T10:56:17.595301399Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2926, in _generate_zero_filled_state_for_cell
2021-02-14T10:56:17.595305511Z     return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
2021-02-14T10:56:17.595308576Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2942, in _generate_zero_filled_state
2021-02-14T10:56:17.595311924Z     return nest.map_structure(create_zeros, state_size)
2021-02-14T10:56:17.595315506Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in map_structure
2021-02-14T10:56:17.595319226Z     structure[0], [func(*x) for x in entries],
2021-02-14T10:56:17.595322192Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in <listcomp>
2021-02-14T10:56:17.595325398Z     structure[0], [func(*x) for x in entries],
2021-02-14T10:56:17.595329606Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2939, in create_zeros
2021-02-14T10:56:17.595333441Z     return array_ops.zeros(init_state_size, dtype=dtype)
2021-02-14T10:56:17.595336948Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2677, in wrapped
2021-02-14T10:56:17.595340884Z     tensor = fun(*args, **kwargs)
2021-02-14T10:56:17.595344130Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2721, in zeros
2021-02-14T10:56:17.595347494Z     output = _constant_if_small(zero, shape, dtype, name)
2021-02-14T10:56:17.595350674Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2662, in _constant_if_small
2021-02-14T10:56:17.595354156Z     if np.prod(shape) < 1000:
2021-02-14T10:56:17.595357749Z   File "<__array_function__ internals>", line 6, in prod
2021-02-14T10:56:17.595361456Z   File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
2021-02-14T10:56:17.595365102Z     keepdims=keepdims, initial=initial, where=where)
2021-02-14T10:56:17.595368365Z   File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
2021-02-14T10:56:17.595372040Z     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
2021-02-14T10:56:17.595375991Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 749, in __array__
2021-02-14T10:56:17.595379817Z     " array.".format(self.name))
2021-02-14T10:56:17.595383433Z NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array.
2021-02-14T10:56:17.595386951Z ).
2021-02-14T10:56:17.596410796Z Traceback (most recent call last):
2021-02-14T10:56:17.596423361Z   File "/usr/local/lib/python3.7/site-packages/lib/prediction_class.py", line 105, in predict
2021-02-14T10:56:17.596433650Z     response = run(arguments, check=True, stdout=DEVNULL, stderr=stderr_fh)
2021-02-14T10:56:17.596437482Z   File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
2021-02-14T10:56:17.596440033Z     output=stdout, stderr=stderr)
2021-02-14T10:56:17.596442719Z subprocess.CalledProcessError: Command '['python', '/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py', '/sbgenomics/workspaces/49a7cbe7-e206-4f9d-bb3a-b57644a4f5e2/tasks/1d2e779e-b1dc-4ffb-82c9-c46453b69dff/pvacseq_pvacseq/pvacseq_predictions/MHC_Class_II/tmp/test_tumor.12.fa.split_1-22', 'DQA1*01:02-DQB1*05:02', '12', 'II', '/tmp/pvacseq/tmpehxpfpad']' returned non-zero exit status 1.
2021-02-14T10:56:17.596446066Z 
2021-02-14T10:56:17.596448202Z During handling of the above exception, another exception occurred:
2021-02-14T10:56:17.596450453Z 
2021-02-14T10:56:17.596452636Z Traceback (most recent call last):
2021-02-14T10:56:17.596454836Z   File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 373, in call_iedb
2021-02-14T10:56:17.596457168Z     lib.call_iedb.main(arguments)
2021-02-14T10:56:17.596459323Z   File "/usr/local/lib/python3.7/site-packages/lib/call_iedb.py", line 41, in main
2021-02-14T10:56:17.596461736Z     raise err
2021-02-14T10:56:17.596463874Z   File "/usr/local/lib/python3.7/site-packages/lib/call_iedb.py", line 36, in main
2021-02-14T10:56:17.596466219Z     (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
2021-02-14T10:56:17.596468692Z   File "/usr/local/lib/python3.7/site-packages/lib/prediction_class.py", line 450, in predict
2021-02-14T10:56:17.596471080Z     return MHCnuggets.predict(self, input_file, allele, epitope_length, iedb_executable_path, iedb_retries, 'II')
2021-02-14T10:56:17.596473413Z   File "/usr/local/lib/python3.7/site-packages/lib/prediction_class.py", line 111, in predict
2021-02-14T10:56:17.596475697Z     raise Exception("An error occurred while calling MHCnuggets:\n{}".format(err))
2021-02-14T10:56:17.596478155Z Exception: An error occurred while calling MHCnuggets:
2021-02-14T10:56:17.596480413Z 2021-02-14 10:56:17.301147: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-14T10:56:17.596483469Z 2021-02-14 10:56:17.301180: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-14T10:56:17.596485881Z 2021-02-14 10:56:17.301203: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a5f12f239500): /proc/driver/nvidia/version does not exist
2021-02-14T10:56:17.596488397Z 2021-02-14 10:56:17.301363: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-02-14T10:56:17.596490923Z 2021-02-14 10:56:17.307214: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2999995000 Hz
2021-02-14T10:56:17.596495540Z 2021-02-14 10:56:17.307546: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa0f8000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-14T10:56:17.596498139Z 2021-02-14 10:56:17.307571: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-02-14T10:56:17.596500528Z Traceback (most recent call last):
2021-02-14T10:56:17.596502663Z   File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 76, in <module>
2021-02-14T10:56:17.596505237Z     main()
2021-02-14T10:56:17.596507358Z   File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 59, in main
2021-02-14T10:56:17.596509672Z     predict(args.class_type, tmp_file.name, mhcnuggets_allele(args.allele, args.class_type), output=tmp_output_file.name)
2021-02-14T10:56:17.596512008Z   File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/predict.py", line 54, in predict
2021-02-14T10:56:17.596514481Z     model = mhcnuggets_lstm(input_size)
2021-02-14T10:56:17.596516636Z   File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/models.py", line 55, in mhcnuggets_lstm
2021-02-14T10:56:17.596518986Z     model.add(LSTM(hidden_size, dropout=dropout, recurrent_dropout=dropout))
2021-02-14T10:56:17.596521248Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
2021-02-14T10:56:17.596523656Z     result = method(self, *args, **kwargs)
2021-02-14T10:56:17.596525834Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 213, in add
2021-02-14T10:56:17.596528761Z     output_tensor = layer(self.outputs[0])
2021-02-14T10:56:17.596531048Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 654, in __call__
2021-02-14T10:56:17.596533408Z     return super(RNN, self).__call__(inputs, **kwargs)
2021-02-14T10:56:17.596535948Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
2021-02-14T10:56:17.596538321Z     outputs = call_fn(cast_inputs, *args, **kwargs)
2021-02-14T10:56:17.596540493Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 1112, in call
2021-02-14T10:56:17.596542880Z     inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
2021-02-14T10:56:17.596545551Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 848, in _process_inputs
2021-02-14T10:56:17.596547901Z     initial_state = self.get_initial_state(inputs)
2021-02-14T10:56:17.596550068Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 637, in get_initial_state
2021-02-14T10:56:17.596552445Z     inputs=None, batch_size=batch_size, dtype=dtype)
2021-02-14T10:56:17.596556860Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2481, in get_initial_state
2021-02-14T10:56:17.596559339Z     self, inputs, batch_size, dtype))
2021-02-14T10:56:17.596561535Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2926, in _generate_zero_filled_state_for_cell
2021-02-14T10:56:17.596563944Z     return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
2021-02-14T10:56:17.596566231Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2942, in _generate_zero_filled_state
2021-02-14T10:56:17.596568612Z     return nest.map_structure(create_zeros, state_size)
2021-02-14T10:56:17.596570863Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in map_structure
2021-02-14T10:56:17.596573200Z     structure[0], [func(*x) for x in entries],
2021-02-14T10:56:17.596575407Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in <listcomp>
2021-02-14T10:56:17.596577839Z     structure[0], [func(*x) for x in entries],
2021-02-14T10:56:17.596579997Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2939, in create_zeros
2021-02-14T10:56:17.596582336Z     return array_ops.zeros(init_state_size, dtype=dtype)
2021-02-14T10:56:17.596584535Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2677, in wrapped
2021-02-14T10:56:17.596586872Z     tensor = fun(*args, **kwargs)
2021-02-14T10:56:17.596589025Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2721, in zeros
2021-02-14T10:56:17.596591345Z     output = _constant_if_small(zero, shape, dtype, name)
2021-02-14T10:56:17.596593839Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2662, in _constant_if_small
2021-02-14T10:56:17.596596247Z     if np.prod(shape) < 1000:
2021-02-14T10:56:17.596598487Z   File "<__array_function__ internals>", line 6, in prod
2021-02-14T10:56:17.596600838Z   File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
2021-02-14T10:56:17.596603160Z     keepdims=keepdims, initial=initial, where=where)
2021-02-14T10:56:17.596605355Z   File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
2021-02-14T10:56:17.596607717Z     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
2021-02-14T10:56:17.596609924Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 749, in __array__
2021-02-14T10:56:17.596612265Z     " array.".format(self.name))
2021-02-14T10:56:17.596614499Z NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array.
2021-02-14T10:56:17.596616790Z 
2021-02-14T10:56:17.596620720Z 
2021-02-14T10:56:17.596622937Z During handling of the above exception, another exception occurred:
2021-02-14T10:56:17.596625238Z 
2021-02-14T10:56:17.596627287Z Traceback (most recent call last):
2021-02-14T10:56:17.596629434Z   File "/usr/local/bin/pvacseq", line 8, in <module>
2021-02-14T10:56:17.596631796Z     sys.exit(main())
2021-02-14T10:56:17.596633908Z   File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
2021-02-14T10:56:17.596636213Z     args[0].func.main(args[1])
2021-02-14T10:56:17.596638355Z   File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/run.py", line 149, in main
2021-02-14T10:56:17.596640652Z     pipeline.execute()
2021-02-14T10:56:17.596642770Z   File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 475, in execute
2021-02-14T10:56:17.596645096Z     self.call_iedb(chunks)
2021-02-14T10:56:17.596647230Z   File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 374, in call_iedb
2021-02-14T10:56:17.596649558Z     p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
2021-02-14T10:56:17.596652029Z   File "/usr/local/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
2021-02-14T10:56:17.596654393Z     raise exc_t(exc_val)
2021-02-14T10:56:17.596656578Z Exception: An error occurred while calling MHCnuggets:
2021-02-14T10:56:17.596658846Z 2021-02-14 10:56:17.301147: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-14T10:56:17.596661370Z 2021-02-14 10:56:17.301180: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-14T10:56:17.596663906Z 2021-02-14 10:56:17.301203: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a5f12f239500): /proc/driver/nvidia/version does not exist
2021-02-14T10:56:17.596666478Z 2021-02-14 10:56:17.301363: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-02-14T10:56:17.596668934Z 2021-02-14 10:56:17.307214: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2999995000 Hz
2021-02-14T10:56:17.596671269Z 2021-02-14 10:56:17.307546: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa0f8000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-14T10:56:17.596673816Z 2021-02-14 10:56:17.307571: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-02-14T10:56:17.596676213Z Traceback (most recent call last):
2021-02-14T10:56:17.596678388Z   File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 76, in <module>
2021-02-14T10:56:17.596680813Z     main()
2021-02-14T10:56:17.596684803Z   File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 59, in main
2021-02-14T10:56:17.596687225Z     predict(args.class_type, tmp_file.name, mhcnuggets_allele(args.allele, args.class_type), output=tmp_output_file.name)
2021-02-14T10:56:17.596689567Z   File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/predict.py", line 54, in predict
2021-02-14T10:56:17.596691872Z     model = mhcnuggets_lstm(input_size)
2021-02-14T10:56:17.596694010Z   File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/models.py", line 55, in mhcnuggets_lstm
2021-02-14T10:56:17.596696341Z     model.add(LSTM(hidden_size, dropout=dropout, recurrent_dropout=dropout))
2021-02-14T10:56:17.596698589Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
2021-02-14T10:56:17.596700954Z     result = method(self, *args, **kwargs)
2021-02-14T10:56:17.596703151Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 213, in add
2021-02-14T10:56:17.596705533Z     output_tensor = layer(self.outputs[0])
2021-02-14T10:56:17.596707704Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 654, in __call__
2021-02-14T10:56:17.596710037Z     return super(RNN, self).__call__(inputs, **kwargs)
2021-02-14T10:56:17.596712236Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
2021-02-14T10:56:17.596714756Z     outputs = call_fn(cast_inputs, *args, **kwargs)
2021-02-14T10:56:17.596716961Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 1112, in call
2021-02-14T10:56:17.596719315Z     inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
2021-02-14T10:56:17.596721579Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 848, in _process_inputs
2021-02-14T10:56:17.596723947Z     initial_state = self.get_initial_state(inputs)
2021-02-14T10:56:17.596726120Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 637, in get_initial_state
2021-02-14T10:56:17.596728485Z     inputs=None, batch_size=batch_size, dtype=dtype)
2021-02-14T10:56:17.596730662Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2481, in get_initial_state
2021-02-14T10:56:17.596733023Z     self, inputs, batch_size, dtype))
2021-02-14T10:56:17.596735195Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2926, in _generate_zero_filled_state_for_cell
2021-02-14T10:56:17.596737589Z     return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
2021-02-14T10:56:17.596739837Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2942, in _generate_zero_filled_state
2021-02-14T10:56:17.596742222Z     return nest.map_structure(create_zeros, state_size)
2021-02-14T10:56:17.596746293Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in map_structure
2021-02-14T10:56:17.596748777Z     structure[0], [func(*x) for x in entries],
2021-02-14T10:56:17.596750964Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in <listcomp>
2021-02-14T10:56:17.596753392Z     structure[0], [func(*x) for x in entries],
2021-02-14T10:56:17.596755571Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2939, in create_zeros
2021-02-14T10:56:17.596757911Z     return array_ops.zeros(init_state_size, dtype=dtype)
2021-02-14T10:56:17.596760092Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2677, in wrapped
2021-02-14T10:56:17.596762426Z     tensor = fun(*args, **kwargs)
2021-02-14T10:56:17.596764558Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2721, in zeros
2021-02-14T10:56:17.596766889Z     output = _constant_if_small(zero, shape, dtype, name)
2021-02-14T10:56:17.596769296Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2662, in _constant_if_small
2021-02-14T10:56:17.596771662Z     if np.prod(shape) < 1000:
2021-02-14T10:56:17.596773870Z   File "<__array_function__ internals>", line 6, in prod
2021-02-14T10:56:17.596776277Z   File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
2021-02-14T10:56:17.596778610Z     keepdims=keepdims, initial=initial, where=where)
2021-02-14T10:56:17.596780807Z   File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
2021-02-14T10:56:17.596783139Z     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
2021-02-14T10:56:17.596785332Z   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 749, in __array__
2021-02-14T10:56:17.596787692Z     " array.".format(self.name))
2021-02-14T10:56:17.596789949Z NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array.
2021-02-14T10:56:17.604451361Z 
```

**Additional comments**
I wonder if this is due to changes in the python version, and/or omit of `RUN pip install mhcnuggets==2.2`

**Comment by susannasiebert** [comment]
It looks like the tensorflow version I was pinning in the container had a bug in it. I updated tensorflow to 2.2.2 and rebuilt the 2.0.0 and latest docker container. You will need to make sure to either pull the new versions (`docker pull griffithlab/pvactools:2.0.0`) or to remove your locally cached images (`docker rmi griffithlab/pvactools:2.0.0`). Let me know if that fixes it for you.

**Comment by malachig** [comment]
Thanks for reporting this @boyangzhao and for the quick fix @susannasiebert

**Comment by boyangzhao** [comment]
I just ran through our unit tests, and confirm it's working with the new docker! thanks for the quick response!

**Comment by susannasiebert** [comment]
Awesome. Closing this issue.
