### ISSUE TITLE
ValueError in calculate_reference_proteome_similarity.py

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#655]
* pvactools version: 2.0.0
* docker: griffithlab/pvactools:2.0.0

**Describe the bug**
There is some error message when running pvaseq with `run-reference-proteome-similarity`. The same set of inputs run fine without the blast proteome option turned on. I've had some previous smaller inputs that ran fine with this option, but on a larger input data, the error was observed.

**Log Output**
```
2021-04-05T19:51:01.736292580Z Traceback (most recent call last):
2021-04-05T19:51:01.736305543Z   File "/usr/local/bin/pvacseq", line 8, in <module>
2021-04-05T19:51:01.736308993Z     sys.exit(main())
2021-04-05T19:51:01.736311634Z   File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
2021-04-05T19:51:01.736314350Z     args[0].func.main(args[1])
2021-04-05T19:51:01.736316880Z   File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/run.py", line 122, in main
2021-04-05T19:51:01.736319483Z     pipeline.execute()
2021-04-05T19:51:01.736321889Z   File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 504, in execute
2021-04-05T19:51:01.736324472Z     PostProcessor(**post_processing_params).execute()
2021-04-05T19:51:01.736326940Z   File "/usr/local/lib/python3.7/site-packages/lib/post_processor.py", line 37, in execute
2021-04-05T19:51:01.736329467Z     self.calculate_reference_proteome_similarity()
2021-04-05T19:51:01.736332003Z   File "/usr/local/lib/python3.7/site-packages/lib/post_processor.py", line 139, in calculate_reference_proteome_similarity
2021-04-05T19:51:01.736334916Z     file_type=self.file_type
2021-04-05T19:51:01.736337213Z   File "/usr/local/lib/python3.7/site-packages/lib/calculate_reference_proteome_similarity.py", line 140, in execute
2021-04-05T19:51:01.736339857Z     for blast_record in NCBIXML.parse(result_handle):
2021-04-05T19:51:01.736342211Z   File "/usr/local/lib/python3.7/site-packages/Bio/Blast/NCBIXML.py", line 805, in parse
2021-04-05T19:51:01.736344766Z     % (XML_START, text[:20]))
2021-04-05T19:51:01.736347166Z ValueError: Your XML file did not start with '<?xml'... but instead '\n\n\n'
```

**Comment by susannasiebert** [comment]
Thank you for this bug report. This isn't something we have encountered before so it will be difficult to debug on our end. Would you be able to share your input file with us? Hopefully, we would be able to replicate this error that way.

**Comment by boyangzhao** [comment]
I've attached the following file (the vcf.gz file along with the index file; I exclude the phasing vcf for now). This came out of a workflow run where the error message is now below (again related to the blast feature). When I try to rerun just the pvacseq part with this input, now it hangs indefinitely. It's not clear if all these behaviors are related or they're different issues.

```
2021-04-06T22:12:59.147282358Z Traceback (most recent call last):
2021-04-06T22:12:59.147298339Z   File "/usr/local/bin/pvacseq", line 8, in <module>
2021-04-06T22:12:59.147301610Z     sys.exit(main())
2021-04-06T22:12:59.147303962Z   File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
2021-04-06T22:12:59.147306577Z     args[0].func.main(args[1])
2021-04-06T22:12:59.147308855Z   File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/run.py", line 122, in main
2021-04-06T22:12:59.147311320Z     pipeline.execute()
2021-04-06T22:12:59.147313436Z   File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 504, in execute
2021-04-06T22:12:59.147315811Z     PostProcessor(**post_processing_params).execute()
2021-04-06T22:12:59.147318527Z   File "/usr/local/lib/python3.7/site-packages/lib/post_processor.py", line 37, in execute
2021-04-06T22:12:59.147320831Z     self.calculate_reference_proteome_similarity()
2021-04-06T22:12:59.147323131Z   File "/usr/local/lib/python3.7/site-packages/lib/post_processor.py", line 139, in calculate_reference_proteome_similarity
2021-04-06T22:12:59.147326082Z     file_type=self.file_type
2021-04-06T22:12:59.147328325Z   File "/usr/local/lib/python3.7/site-packages/lib/calculate_reference_proteome_similarity.py", line 134, in execute
2021-04-06T22:12:59.147330881Z     peptide = self.extract_n_mer(mt_records_dict[line['Index']], int(line['Sub-peptide Position']), int(line['Mutation Position']), len(mt_amino_acids))
2021-04-06T22:12:59.147333356Z KeyError: '967.FZD3.ENST00000240093.7.missense.378P/S'
```

[Archive.zip](https://github.com/griffithlab/pVACtools/files/6273137/Archive.zip)

**Comment by susannasiebert** [comment]
I apologize for the delay in getting to work on this issue. I have some time this week to debug it.

Your second error indicates to me that there are some concatenated temporary files in your output directory with incomplete records, probably because the run failed previously.  If you would be able to share your existing output files with us, that would help me trying to debug this further.

Can you please also share the full pvacseq command you tried to run?

**Comment by boyangzhao** [comment]
I reran our task several times and can no longer replicate this error. The jobs all finished successfully. It may be due to intermittent interruption of tasks/instances and temporary files not correct in that particular run before (?). But since I have reran this several times without seeing this error, I will close this issue now.
