### ISSUE TITLE
Question on running the example file using 

### ISSUE THREAD

**Issue by ShumingZhang1997** [griffithlab/pVACtools#661]
I tried to run the pVACbind with the example files, the following error raised. At your convenience, would you mind telling me what's the potential problem and how should I fix it? (Installed version: 2.0.1, Python==3.8.5, mhcflurry==2.0.1, Linux operating system). Thank you so much for the help.

Best,
Shuming

```
Executing MHC Class I predictions
Splitting FASTA into smaller chunks
Splitting FASTA into smaller chunks - Entries 1-48
Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /media/sf_spQSP-HCC/antigenData/example/pvacbind_example_data/MHC_Class_I/tmp/Test.MHCflurry.HLA-A*02:01.8.tsv_1-48
An exception occured in thread 0: (<class 'FileNotFoundError'>, [Errno 2] No such file or directory: '/media/sf_spQSP-HCC/antigenData/example/pvacbind_example_data/MHC_Class_I/tmp/Test.MHCflurry.HLA-A*02:01.8.tsv_1-48.tmp').
Traceback (most recent call last):
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/pipeline.py", line 679, in call_iedb
    lib.call_iedb.main(arguments)
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/call_iedb.py", line 45, in main
    response_text.to_csv(tmp_output_file, index=False, sep="\t")
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3387, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 228, in save
    with get_handle(
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/media/sf_spQSP-HCC/antigenData/example/pvacbind_example_data/MHC_Class_I/tmp/Test.MHCflurry.HLA-A*02:01.8.tsv_1-48.tmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shumingzhang/.local/bin/pvacbind", line 8, in <module>
    sys.exit(main())
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/tools/pvacbind/main.py", line 65, in main
    args[0].func.main(args[1])
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/tools/pvacbind/run.py", line 100, in main
    pipeline.execute()
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/pipeline.py", line 744, in execute
    self.call_iedb(chunks, length)
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/pipeline.py", line 680, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
FileNotFoundError: [Errno 2] No such file or directory: '/media/sf_spQSP-HCC/antigenData/example/pvacbind_example_data/MHC_Class_I/tmp/Test.MHCflurry.HLA-A*02:01.8.tsv_1-48.tmp'

```

**Comment by ShumingZhang1997** [comment]
Here are the log information generated automatically

```
additional_report_columns: null
allele_specific_binding_thresholds: false
alleles:
- HLA-A*02:01
- HLA-B*35:01
binding_threshold: 500
downstream_sequence_length: 1000
epitope_lengths:
- 8
- 9
- 10
exclude_NAs: false
expn_val: null
fasta_size: 200
iedb_executable: null
iedb_retries: 5
input_file: example/pvacbind_example_data/input.fasta
input_file_type: fasta
keep_tmp_files: false
maximum_transcript_support_level: null
minimum_fold_change: 0
n_threads: 1
net_chop_method: null
net_chop_threshold: 0.5
netmhc_stab: false
normal_cov: null
normal_sample_name: null
normal_vaf: null
output_dir: /media/sf_spQSP-HCC/antigenData/example/pvacbind_example_data/MHC_Class_I
pass_only: false
percentile_threshold: null
phased_proximal_variants_vcf: null
prediction_algorithms:
- MHCflurry
- NetMHC
- PickPocket
- SMM
- SMMPMBEC
proximal_variants_file: null
pvactools_version: 2.0.1
run_reference_proteome_similarity: false
sample_name: Test
spacers: null
species: human
tdna_cov: null
tdna_vaf: null
tmp_dir: /media/sf_spQSP-HCC/antigenData/example/pvacbind_example_data/MHC_Class_I/tmp
top_score_metric: median
trna_cov: null
trna_vaf: null


```

**Comment by ShumingZhang1997** [comment]
To add:
The operating system I am using is Ubuntu 20.04. I don't know if that makes any difference

**Comment by susannasiebert** [comment]
Hi Shuming,

Can you confirm whether or not you ran the `mhcflurry-downloads fetch` command after installing MHCflurry? Without it, MHCflurry is unable to run. 

Thanks,
Susanna

**Comment by ShumingZhang1997** [comment]
![Screenshot 2021-04-19 123512](https://user-images.githubusercontent.com/55164491/115271854-c662ad80-a10b-11eb-972b-4eda1fbae424.png)
This the response I got after I typed `mhcflurry-downloads fetch`. By the way, this error is also raised for other prediction tools as well. and the error messages are the same, just substitute with other tool names (I tested them all)

```
Executing MHC Class I predictions
Converting .vcf to TSV
Completed
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-24
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 1-48
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 1-48
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 1-48
Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCnuggetsI - File /media/sf_spQSP-HCC/antigenData/example/output/MHC_Class_I/tmp/Test.MHCnuggetsI.HLA-A*02:01.8.tsv_1-48
An exception occured in thread 0: (<class 'Exception'>, An error occurred while calling MHCnuggets:
).
Traceback (most recent call last):
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/prediction_class.py", line 105, in predict
    response = run(arguments, check=True, stdout=DEVNULL, stderr=stderr_fh)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/pipeline.py", line 373, in call_iedb
    lib.call_iedb.main(arguments)
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/call_iedb.py", line 41, in main
    raise err
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/call_iedb.py", line 36, in main
    (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/prediction_class.py", line 361, in predict
    return MHCnuggets.predict(self, input_file, allele, epitope_length, iedb_executable_path, iedb_retries, 'I')
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/prediction_class.py", line 111, in predict
    raise Exception("An error occurred while calling MHCnuggets:\n{}".format(err))
Exception: An error occurred while calling MHCnuggets:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shumingzhang/.local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/tools/pvacseq/run.py", line 122, in main
    pipeline.execute()
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/pipeline.py", line 475, in execute
    self.call_iedb(chunks)
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/lib/pipeline.py", line 374, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/home/shumingzhang/.local/lib/python3.8/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
Exception: An error occurred while calling MHCnuggets:


```

**Comment by ShumingZhang1997** [comment]
Hi Susanna,
Really grateful for the help. I used docker to run the program, and everything works fine. However, I saw this while running the program on Docker, using both pvacseq and pvacbind. I wonder if that's normal. However, the contents in the output files are identical compared to the outputs you gave.

Best,
Shuming
```
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 9 with Method NetMHC - File /pvactools_example_data/output/MHC_Class_I/tmp/Test.ann.HLA-A*02:01.9.tsv_1-48
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
```

**Comment by susannasiebert** [comment]
That's really strange. I would expect the pipeline to fail if you're getting segmentation faults. If you do get outputs and they appear complete than you might just be able to ignore them. Are you getting all the normal log messages written to stdout?

Also, are you using the standalone IEDB installations inside of docker (i.e., using the `--iedb-install-directory` option)?

**Comment by ShumingZhang1997** [comment]
Yes, below is my shell script for running the program. Also, I attached the output files and the stdout message. I believe there is only one tool that produces the segmentation fault. At your convenience, could you please speculate what might be the problem? Again, thank you so much for the support and quick response.

Best,
Shuming
[output.zip](https://github.com/griffithlab/pVACtools/files/6338384/output.zip)
[stdout_log_message.txt](https://github.com/griffithlab/pVACtools/files/6338386/stdout_log_message.txt)

 

```
#!/bin/bash
pvacbind run \
/pvactools_example_data/pvacbind_example_data/input.fasta \
Test \
HLA-A*02:01,HLA-B*35:01,DRB1*11:01 \
MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \
/pvactools_example_data/output \
-e1 8,9,10 -e2 15 --iedb-install-directory /opt/iedb
```

**Comment by susannasiebert** [comment]
It appears that the segmentation faults happen during the prediction calls for NetMHC. I don't get any segmentation faults when I run pVACbind on docker on my machine (directly or using your bash script). Taking a closer look at your result files, it looks like the columns from NetMHC are always NA so it looks like you aren't getting any results from that caller after all.

Let's trying running NetMHC directly inside the docker container to see if that will give us any more specific error: 
`python mhc_i/src/predict_binding.py ann HLA-A*02:01 9 /pvactools_example_data/pvacbind_example_data/input.fasta`

**Comment by ShumingZhang1997** [comment]
Hi Susanna,
Here is the output I got from running the script you provided. 
```
root@d24e4fdac037:/opt/iedb# python mhc_i/src/predict_binding.py ann HLA-A*02:01 9 /pvactools_example_data/pvacbind_example_data/input.fasta
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
allele  seq_num start   end     length  peptide ic50    rank
```
