### ISSUE TITLE
MHCnuggetsI error when running pVACseq (pVACtools 2.0.3)

### ISSUE THREAD

**Issue by rbowenj** [griffithlab/pVACtools#694]
Hi, 

Thanks for the recent 2.0.3 release!

I've been trying to run pVACseq on your test `input_somatic.vcf.gz` file (using the command specified in the pVACseq Getting Started docs) but am encountering an error from MHCnuggetsI (output below). I am running pVACseq using the `griffithlab/pvactools:2.0.3` Docker. 
The error does not occur when I run the same command using pVACtools version 2.0.2.

Thanks

```
Executing MHC Class I predictions
Converting .vcf to TSV
frameshift_variant transcript does not contain a FrameshiftSequence. Skipping.
chr20 57340103 CTA C ENST00000371263.7
Completed
Converting VCF to TSV
frameshift_variant transcript does not contain a FrameshiftSequence. Skipping.
chr20 57340103 CTA C ENST00000371263.7
Completed
Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Splitting TSV into smaller chunks - Entries 101-200
Splitting TSV into smaller chunks - Entries 201-300
Splitting TSV into smaller chunks - Entries 301-400
Splitting TSV into smaller chunks - Entries 401-411
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 1-200
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 1-200
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 1-200
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 201-400
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 201-400
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 201-400
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 401-600
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 401-600
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 401-600
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 601-800
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 601-800
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 601-800
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 801-822
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 801-822
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 801-822
Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /opt/iedb/outdir/MHC_Class_I/tmp/Test.MHCflurry.HLA-A*02:01.8.tsv_1-200
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /opt/iedb/outdir/MHC_Class_I/tmp/Test.MHCflurry.HLA-A*02:01.8.tsv_1-200 - Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCnuggetsI - File /opt/iedb/outdir/MHC_Class_I/tmp/Test.MHCnuggetsI.HLA-A*02:01.8.tsv_1-200
An exception occured in thread 0: (<class 'Exception'>, An error occurred while calling MHCnuggets:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 14, in <module>
    raise err
  File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 11, in <module>
    from mhcnuggets.src.predict import predict
  File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/predict.py", line 11, in <module>
    from mhcnuggets.src.models import get_predictions, mhcnuggets_lstm
  File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/models.py", line 9, in <module>
    import keras
  File "/usr/local/lib/python3.7/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.7/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/usr/local/lib/python3.7/site-packages/keras/backend.py", line 36, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/context.py)
).
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lib/prediction_class.py", line 105, in predict
    response = run(arguments, check=True, stdout=DEVNULL, stderr=stderr_fh)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', '/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py', '/opt/iedb/outdir/MHC_Class_I/tmp/Test.8.fa.split_1-200', 'HLA-A*02:01', '8', 'I', '/tmp/tmppeb7hfzn']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 373, in call_iedb
    lib.call_iedb.main(arguments)
  File "/usr/local/lib/python3.7/site-packages/lib/call_iedb.py", line 41, in main
    raise err
  File "/usr/local/lib/python3.7/site-packages/lib/call_iedb.py", line 36, in main
    (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
  File "/usr/local/lib/python3.7/site-packages/lib/prediction_class.py", line 361, in predict
    return MHCnuggets.predict(self, input_file, allele, epitope_length, iedb_executable_path, iedb_retries, 'I')
  File "/usr/local/lib/python3.7/site-packages/lib/prediction_class.py", line 111, in predict
    raise Exception("An error occurred while calling MHCnuggets:\n{}".format(err))
Exception: An error occurred while calling MHCnuggets:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 14, in <module>
    raise err
  File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 11, in <module>
    from mhcnuggets.src.predict import predict
  File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/predict.py", line 11, in <module>
    from mhcnuggets.src.models import get_predictions, mhcnuggets_lstm
  File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/models.py", line 9, in <module>
    import keras
  File "/usr/local/lib/python3.7/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.7/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/usr/local/lib/python3.7/site-packages/keras/backend.py", line 36, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/context.py)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/run.py", line 122, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 475, in execute
    self.call_iedb(chunks)
  File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 374, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/usr/local/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
Exception: An error occurred while calling MHCnuggets:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 14, in <module>
    raise err
  File "/usr/local/lib/python3.7/site-packages/lib/call_mhcnuggets.py", line 11, in <module>
    from mhcnuggets.src.predict import predict
  File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/predict.py", line 11, in <module>
    from mhcnuggets.src.models import get_predictions, mhcnuggets_lstm
  File "/usr/local/lib/python3.7/site-packages/mhcnuggets/src/models.py", line 9, in <module>
    import keras
  File "/usr/local/lib/python3.7/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.7/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/usr/local/lib/python3.7/site-packages/keras/backend.py", line 36, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/context.py)
```

**Comment by Stikus** [comment]
Hello, we encountered the same problem, but, according to my research, it is not tied to pVACtools version (we encountered this error when rebuilding old image).

There are plenty of questions about this error on the internet:

- https://stackoverflow.com/questions/66964492/importerror-cannot-import-name-get-config-from-tensorflow-python-eager-conte
- https://github.com/tensorflow/models/issues/10071
- https://github.com/tensorflow/tensorflow/issues/48734

After manual installation of old version of `keras==2.4.3` before `pvactools` everything start to work again.
According to `keras` [releases](https://github.com/keras-team/keras/releases) version `2.6.0` (current) didn't support old versions of `tensorflow` (and we are using `tensorflow=2.2.2`) - if I understood all correctly.

Just compare current `keras/backend.py`: https://github.com/keras-team/keras/blob/v2.6.0/keras/backend.py with old https://github.com/keras-team/keras/blob/2.4.0/keras/backend.py - this file causing errors as you can see:
```
  File "/usr/local/lib/python3.7/site-packages/keras/backend.py", line 36, in <module>
    from tensorflow.python.eager.context import get_config
```

So if we plan to use `tensorflow==2.2.2` we should pin `keras` to old version (i.e. 2.4.3). For now, when we install `mhcnuggents` we get this requirement: https://github.com/KarchinLab/mhcnuggets/blob/master/setup.py#L25 - just `keras`.

Btw @susannasiebert you have 2 lines with `mhcnuggets` and `mhcflurry` in [setup.py](https://github.com/griffithlab/pVACtools/blob/v2.0.3/setup.py#L97) - one with version and one without:
```
        'mhcflurry',
        'mhcnuggets',
        'pysam',
        'Pillow',
        'pymp-pypi',
        'connexion==1.4.2',
        'py-postgresql',
        'watchdog',
        'flask-cors',
        'bokeh==0.13.0',
        'tornado==5.0.2',
        'swagger-spec-validator==2.1.0',
        'jsonschema==2.6.0',
        'mock',
        'vaxrank>=1.1.0',
        'tensorflow==2.2.2',
        'mhcnuggets==2.3.3',
        'mhcflurry==2.0.1',
```

**Comment by susannasiebert** [comment]
@stikus thanks for the troubleshooting. I will confirm this on my end and rebuild the 2.0.3 docker container with the keras version you mentioned.

**Comment by susannasiebert** [comment]
I've updated the 2.0.3 container (new sha256:b1ef076ca92f815c84db2efe6b9b1c874853048f16ed79f268c7bc318257ee1d) to pin the keras version. For some reason while using docker build it wasn't able to find keras 2.3.4 so I used keras 2.3.1, which should work just as well. Please give it a try on your end to confirm.

**Comment by Stikus** [comment]
> For some reason while using docker build it wasn't able to find keras 2.3.4 so I used keras 2.3.1, which should work just as well.

https://pypi.org/project/keras/#history - there are no `2.3.4` - I'm talking about `2.4.3` - last release before `2.6.0`.

**Comment by susannasiebert** [comment]
Oh, doh. I apologize. I think the version I made should still work but I will make sure to pin 2.4.3 going forward.

**Comment by serge2016** [comment]
Thank you for fast solution!
