### ISSUE TITLE
Exception: An error occurred while calling MHCflurry

### ISSUE THREAD

**Issue by Reda94** [griffithlab/pVACtools#699]
pvactools version: pvactools version 2.0.3 Docker installation (I pulled the container using singularity)
Python version: 3.7
Operating System: Centos 7 (centos-release-7-6.1810.2.el7.centos.x86_64)

[sample.genotyped.vep.vcf.zip](https://github.com/griffithlab/pVACtools/files/7076303/sample.genotyped.vep.vcf.zip)
@susannasiebert I am getting the following error while trying to run MHCflurry for the attached VCF file:

```
An exception occured in thread 1: (<class 'Exception'>, An error occurred while calling MHCflurry:
).
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/run.py", line 122, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 475, in execute
    self.call_iedb(chunks)
  File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 374, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/usr/local/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
Exception: An error occurred while calling MHCflurry:
```

This is the command I used:

```
singularity exec --env MHCFLURRY_DATA_DIR=/opt/mhcflurry_data -B /cluster/Reda/pvacseq_runs/test_sample:/home/test_sample /cluster/Reda/pVACtools_installation_no_MHCflurry_bug/pvactools_latest.sif \
pvacseq run \
--iedb-install-directory /opt/iedb \
--keep-tmp-files \
--n-threads 16 \
--fasta-size 100000 \
--class-i-epitope-length 8,9,10 \
/home/test_sample/sample.genotyped.vep.vcf \
sample \
$(cat /cluster/Reda/haplotypes_reformatted_for_pvacseq/sample.txt) \
MHCflurry \
/home/test_sample
```

This is the whole command output:

```
Executing MHC Class I predictions
Converting .vcf to TSV
Completed
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-17781
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 1-35562
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 1-35562
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 1-35562
Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 10 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-A*02:01.10.tsv_1-35562
Making binding predictions on Allele HLA-A*32:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-A*32:01.9.tsv_1-35562
Making binding predictions on Allele HLA-B*14:01 and Epitope Length 8 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-B*14:01.8.tsv_1-35562
Making binding predictions on Allele HLA-B*14:01 and Epitope Length 10 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-B*14:01.10.tsv_1-35562
Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-B*18:01.9.tsv_1-35562
Making binding predictions on Allele HLA-C*07:01 and Epitope Length 8 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*07:01.8.tsv_1-35562
Making binding predictions on Allele HLA-C*07:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*07:01.9.tsv_1-35562
Making binding predictions on Allele HLA-C*07:01 and Epitope Length 10 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*07:01.10.tsv_1-35562
Making binding predictions on Allele HLA-C*08:02 and Epitope Length 8 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*08:02.8.tsv_1-35562
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-A*02:01.8.tsv_1-35562
Making binding predictions on Allele HLA-C*08:02 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*08:02.9.tsv_1-35562
Making binding predictions on Allele HLA-C*08:02 and Epitope Length 10 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*08:02.10.tsv_1-35562
Making binding predictions on Allele HLA-C*07:01 and Epitope Length 8 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*07:01.8.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-B*14:01 and Epitope Length 8 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-B*14:01.8.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-B*14:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-B*14:01.9.tsv_1-35562
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-A*02:01.8.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-A*02:01.9.tsv_1-35562
Making binding predictions on Allele HLA-C*08:02 and Epitope Length 8 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*08:02.8.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-C*07:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*07:01.9.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-A*32:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-A*32:01.9.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-A*32:01 and Epitope Length 10 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-A*32:01.10.tsv_1-35562
Making binding predictions on Allele HLA-C*08:02 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-C*08:02.9.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-B*18:01.9.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-B*18:01.10.tsv_1-35562
Making binding predictions on Allele HLA-B*14:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-B*14:01.9.tsv_1-35562 - Completed
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 9 with Method MHCflurry - File /home/TCGA-AZ-4315/MHC_Class_I/tmp/TCGA-AZ-4315.MHCflurry.HLA-A*02:01.9.tsv_1-35562 - Completed
An exception occured in thread 1: (<class 'Exception'>, An error occurred while calling MHCflurry:
).
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/run.py", line 122, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 475, in execute
    self.call_iedb(chunks)
  File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 374, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/usr/local/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
Exception: An error occurred while calling MHCflurry:
```

@susannasiebert could you please help me figure out what's going on?

**Comment by susannasiebert** [comment]
Unfortunately, the error message you posted is from the parent process and not the actual error from the MHCflurry child process so it doesn't tell me what is actually causing the call to MHCflurry to fail. Are there any additional error messages? 

My best guess is that you are running out of memory. Either reduce the number of threads and/or reduce your fasta-size parameter and see if that fixes your problem.

**Comment by Reda94** [comment]
@susannasiebert I do not get any other error message. I will try your memory suggestions. Have you tried to run the example on the provided vcf? Thanks

**Comment by susannasiebert** [comment]
I'm in the process of running it.

**Comment by susannasiebert** [comment]
I also got an error in my run:
```
An exception occured in thread 3: (<class 'Exception'>, An error occurred while calling MHCflurry:
).
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lib/prediction_class.py", line 321, in predict
    response = run(arguments, check=True, stdout=DEVNULL, stderr=stderr_fh)
  File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'mhcflurry-predict'
```
I assume that this is the same reason your run is failing. I'm not sure why your error output appears to be suppressed. I think there are probably too many peptides in the call to the prediction algorithm although it is odd that it works for some of the calls to MHCflurry. I will try to run with a smaller fasta-size number to see if that resolved this error.

**Comment by susannasiebert** [comment]
I reduced the fasta size to 10000 and my run succeeded without errors.

**Comment by Reda94** [comment]
@susannasiebert thanks, I ran it with a reduced fasta size and it worked.

I have a question regarding pvacseq with MHCnuggetsI: is there a reason why it does not produce percentile ranks like it does for NetMHCpan and MHCflurry?

**Comment by susannasiebert** [comment]
Wonderful. I'll be closing this issue.

In regards to your MHCnuggets question, this would be something to ask the authors of this particular prediction algorithm. There GitHub repo can be found [here](https://github.com/openvax/mhcflurry). We simply pass along the percentile information if it is made available by each prediction algorithm.

**Comment by Reda94** [comment]
@susannasiebert sorry to ask this here, but is there a way to know which exact version of the tool was ran in pvacseq 2.0.3? Thanks

**Comment by susannasiebert** [comment]
You can run `pip show mhcnuggets` from inside your container to determine that.

**Comment by Reda94** [comment]
@susannasiebert what about netMHCpan and MHCflurry?

**Comment by susannasiebert** [comment]
MHCflurry is a python package so the procedure is the same. NetMHCpan is run via IEDB so you can find that information in the README of the IEDB installation.
