### ISSUE TITLE
An exception occured in thread 17: (<class 'Exception'>, An error occurred while calling MHCflurry:

### ISSUE THREAD

**Issue by iichelhadi** [griffithlab/pVACtools#720]
* pvactools version:2.0.4
* Python version:3.6.12
* Operating System: centOS

**Describe the bug**
Hi Guys
I am having new issues with pvacseq on VEP.vcf file. I tried rerunning `pvacseq` on a VEP.vcf file on which I already successfully processed but same issues.
The issues seem to arise when I am trying to predict using mhcflurry v2.0.1 and mhcnuggets v2.3.3 both are installed using pip as per instructions according to your tutorial.

**To Reproduce**
pvacseq run --iedb-install-directory /home/svu/phaei/IEDB --binding-threshold 500 --n-threads 24 --net-chop-method "cterm" --netmhc-stab --exclude-NAs --normal-sample-name 1880_N vcf_files5/1880_somatic.filtered.VEP.vcf 1880_T HLA-A*02:03,HLA-A*02:06 MHCflurry MHCnuggetsI NetMHC NetMHCpan pvacseq8/1880/

**Log Output**
```
An exception occured in thread 17: (<class 'Exception'>, An error occurred while calling MHCflurry:
).
Traceback (most recent call last):
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/lib/prediction_class.py", line 321, in predict
    response = run(arguments, check=True, stdout=DEVNULL, stderr=stderr_fh)
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mhcflurry-predict', '--alleles', 'HLA-A*02:03', '--out', '/tmp/tmpjzckbrer', '--peptides', 'EEEEQELR', 'RCPSSSSS', 'TCLLLWVK', 'EPSGLEEE', 'VPPPPPIA', 'PARVPPPL', 'LLLLLLAG', 'CLLLLLSL', 'PAGACLLL', 'ASSSSSSN', 'EEAAAAGG', 'EYLTYLLL', 'GWVRRGPH', 'PPIALAVV', 'PSSRVVNG', 'RLPLLLVL', 'HAVIRCPS', 'PSSSSSVS', 'PPPPPPRT', 'MSEQGRET', 'SGGGGCEE', 'ASPSYPRA', 'IRCPSSSS', 'GMHAVGSV', 'DLIKFMLR', 'LLLLGFSI', 'FPCGGGGG', 'PPPPSPSY', 'NGAAAAAA', 'ASSSSSSS', 'CPSSSSSS', 'IKSMLRNE', 'GAAAAAGA', 'ATTTTTTA', 'HTLPGSVQ', 'LDEYLTCL', 'LIKFMLRN', 'LNGAAAAA', 'SGGGGGCE', 'HGEDAVPY', 'PCGGGGKM', 'KDLIKSML', 'GITYIVVK', 'GGGGKMGE', 'HHTLPGSV', 'GAGSTTTT', 'PARVPPPP', 'GNPPPPPS', 'GDGISRLT', 'LGNPPPPP', 'LAALQSGG', 'LLLGFSIC', 'ETEEEGGG', 'VKKRHHTR', 'LQSGGGGL', 'AANNNNNK', 'RESGQLVH', 'SSLGNPPP', 'RPSSRVVH', 'ASSSSSSF', 'SRPTTLPL', 'SHGTLRFI', 'ASSSSSFQ', 'RLLLLLGF', 'LCGLVVKA', 'KAGVIPIQ', 'QPPHHLPQ', 'GACLLLLS', 'LAGRAAGA', 'SVGVPPPP', 'QQQPPHHL', 'PLGEASWP', 'HGTLRFIR', 'PAASSSSS', 'EEEEEEAS', 'VLLLLLLL', 'LTYLLLWV', 'TLRFIRLE', 'EEDEEEEE', 'GDGISRPT', 'IVVQKRHH', 'QERELTQL', 'QARHGDLL', 'CGLVVMAG', 'QKRHHTRL', 'HPAASSSS', 'AAAGAAGS', 'TEEEGGGG', 'DLLLPALR', 'VKAGVIPI', 'LLLLVLAA', 'AANNNNKR', 'ELTQLREK', 'IKFMLRNE', 'GNPPPPPP', 'PGLNGAAA', 'QERELTHL', 'SGQLVHID', 'QQQQPPHH', 'RHGDLLLP', 'PQQQQPPH', 'GDLLLPAL', 'RELTQLRE', 'APAAPPPP', 'RELTHLRE', 'TRKTTVAA', 'LVLAAVTG', 'RVVNGEDA', 'RHGDLLLL', 'SMLRNERQ', 'HGDLLLLP', 'LNLSHGTL', 'RVPPPLPI', 'AGAGSTTT', 'RPESGGGG', 'IVVKKRHH', 'SGGGGLEP', 'AASSSSSF', 'IQEEDEEE', 'HALHPAAS', 'LCGLVVMA', 'SRLTTLPL', 'TTKGMHAV', 'NNNKRKGR', 'QLVHIDFG', 'RLTTLPLT', 'HHHTLPGS', 'AAAAAGAP', 'GALRFIRL', 'LLLAGRAA', 'TYIVVQKR', 'LHHHHHHT', 'PPPPIALA', 'LEEEEEEE', 'TTSPGPPA', 'EAAAGGGV', 'LLLLPPQL', 'SQERELTQ', 'CKDLIKFM', 'LSHGALRF', 'ECKDLIKF', 'CKDLIKSM', 'LLLVLAAV', 'YLTCLLLW', 'TLDEYLTY', 'SSSSFQPS', 'DGISRPTT', 'GGGGGKMG', 'RRLLLLLG', 'GISRLTTL', 'EEEQELRW', 'LQSGGGGG', 'LLLLAGRA', 'TYLLLWVK', 'LTHLREKL', 'FHIDFGHF', 'AAAAAGAA', 'MAAAAAAA', 'DLIKSMLR', 'CGLVVKAG', 'RVLLLLLL', 'HGDLLLPA', 'NNNNNKRK', 'AQPQQQQP', 'GAAGSAAP', 'KRKGRARW', 'LLLLLSLD', 'LPLLLVLA', 'EEQELRWM', 'VAATTTTT', 'LLVLAAVT', 'LPLLLLVL', 'GTLRFIRL', 'KGMHAVGS', 'AAPAAPPP', 'GAGSTTTS', 'LTQLREKL', 'GRETEEEG', 'PHAVIRCP', 'KKRHHTRL', 'QQQQQPPH', 'PSPSYPRA', 'VPPPASPS', 'EDEEEEDD', 'QEEDEEEE', 'FQPSPENC', 'KSMLRNER', 'VQKRHHTR', 'QPGLNGAA', 'ATTTTTTT', 'ESGQLFHI', 'TEEEEGGG', 'QSGGGGGL', 'GLVVMAGV', 'KFMLRNER', 'PPSPSYPR', 'SIQEEDEE', 'RGPHGEAS', 'FPCGGGGK', 'PCGGGGGK', 'NRPESGGG', 'ASSLGNPP', 'PPPPPPSE', 'SSSSSFQP', 'HHHHHHTL', 'VRRGPHGE', 'NNNNKRKG', 'GSTTTTSP', 'EAAAAGGG', 'QLNLSHGA', 'VGVPPPAS', 'NGAAAAAG', 'MHAVGQSE', 'WVRRGPHG', 'AAAAGGGV', 'QSRVLLLL', 'QLFHIDFG', 'PQQQQQPP', 'PPPPPPPR', 'STTTSPGP', 'LLCGLVVK', 'DGISRLTT', 'DEYLTCLL', 'RRLLLLGF', 'LNLSHGAL', 'ARHGDLLL', 'GKMGENSG', 'AGGGVGAG', 'AAAAAAAG', 'CPSSSSSV', 'VIRCPSSS', 'HLREKLRE', 'PTTLPLTT', 'EEEEEDDA', 'RRNRPESG', 'ITYIVVKK', 'QPQQQQPP', 'SSSSSSFQ', 'VPPPLPIA', 'LVVMAGVI', 'LSHGTLRF', 'PASPSYPR', 'ACLLLLSL', 'AAAGGGVG', 'PPPSPSYP', 'FMLRNERQ', 'RRGPLGEA', 'YIVVKKRH', 'RETEEEEG', 'VVQKRHHT', 'ANNNNKRK', 'ANNNNNKR', 'DLLLLPAL', 'ETEEEEGG', 'RVPPPPPI', 'QLREKLRE', 'LVHIDFGH', 'EGDGISRP', 'AGSTTTSP', 'KTTVAATT', 'STTTTSPG', 'VRRGPLGE', 'RNRPESGG', 'TFSPAGAC', 'GPHGEASW', 'NKRKGRAR', 'LLLLLLLP', 'GDLLLLPA', 'ALQSGGGG', 'TTTSPGPP', 'TVAATTTT', 'REEEEEQE', 'TTTTTTTA', 'APPPPPPP', 'EYLTCLLL', 'PLLLVLAA', 'ALRFIRLE', 'ERELTHLR', 'RESGQLFH', 'AAGAAGSA', 'VVKAGVIP', 'CGGGGKMG', 'SPAGACLL', 'SSIQEEDE', 'VHGEDAVP', 'EQARHGDL', 'SGLEEEEE', 'RLLLLGFS', 'PAAPPPPP', 'EEAAAGGG', 'ELTHLREK', 'AGSTTTTS', 'ESGGGGGC', 'PSSSSSSV', 'LLLLPALR', 'VGVPPPPS', 'PPLLLLLA', 'QGRETEEE', 'GAAAAAAG', 'DEEEEDDA', 'HHHHTLPG', 'QLNLSHGT', 'EEEEEASG', 'DEEEEEDD', 'NPPPPPPS', 'GLAALQSG', 'AVGQSEIV', 'PESGGGGC', 'AAGGGVGA', 'SLGNPPPP', 'PHGEASWP', 'RKTTVAAT', 'AAAAAAGA', 'RPSSRVVN', 'EEEEEQEL', 'TLDEYLTC', 'HGALRFIR', 'EQGRETEE', 'YIVVQKRH', 'GITYIVVQ', 'GPLGEASW', 'SHGALRFI', 'PREEEEEQ', 'ACLLLLLS', 'CLLLWVKQ', 'ALHPAASS', 'LLLLLLPP', 'RRGPHGEA', 'PLLLLLAG', 'ARVPPPPP', 'QSGGGGLE', 'SVGVPPPA', 'HHHHHTLP', 'LHHHHHTL', 'LRLPLLLV', 'GWVRRGPL', 'GVPPPPSP', 'SFQPSPEN', 'LVVKAGVI', 'NNKRKGRA', 'PSGLEEEE', 'PPLLLLLL', 'EGDGISRL', 'VVMAGVIP', 'PLLLLLLA', 'PPPPPIAL', 'LHPAASSS', 'GGKMGENS', 'TKGMHAVG', 'GQLVHIDF', 'TYIVVKKR', 'REEEEEEQ', 'NGEDAVPY', 'GSTTTSPG', 'QQPPHHLP', 'GLNGAAAA', 'ESGQLVHI', 'LGFSICLI', 'LAANNNNK', 'WVRRGPLG', 'VMAGVIPI', 'ESGGGGCE', 'SQERELTH', 'ITYIVVQK', 'GLVVKAGV', 'HAVGQSEI', 'PGLAALQS', 'GGGVGAGA', 'SGQLFHID', 'EEEEEEEA', 'GISRPTTL', 'EEEEEEQE', 'GMHAVGQS', 'GVPPPASP', 'EEDEEEED', 'AQPQQQQQ', 'YLLLWVKQ', 'VLLLLLLP', 'LLGFSICL', 'LLCGLVVM', 'LLLLLGFS', 'LLLLLAGR', 'GGGGGLEP', 'VVHGEDAV', 'LPIALAVV', 'VNGEDAVP', 'GRRLLLLG', 'TTTTSPGP', 'ARVPPPLP', 'LLLLLPPQ', 'FSPAGACL', 'CLLLLSLD', 'PLLLLVLA', 'NPPPPPSE', 'CGGGGGKM', 'MAAAAAAG', 'SGGGGGLE', 'EEEEAAAG', 'GLEEEEEE', 'EEEAAAAG', 'RLPLLLLV', 'LTCLLLWV', 'ERELTQLR', 'PPASPSYP', 'LGEASWPA', 'IRESGQLF', 'GRETEEEE', 'SRVVNGED', 'LIKSMLRN', 'ISRLTTLP', 'VVNGEDAV', 'AGACLLLL', 'PSSRVVHG', 'VHIDFGHF', 'PLPIALAV', 'EDEEEEED', 'SRVVHGED', 'SSRVVNGE', 'SSSSSSSN', 'GRRLLLLL', 'AASSLGNP', 'LLAGRAAG', 'PPHHLPQQ', 'SSRVVHGE', 'VVKKRHHT', 'SSFQPSPE', 'ALHHHHHH', 'AASSSSSS', 'TQLREKLR', 'RETEEEGG', 'DEYLTYLL', 'PPPLPIAL', 'RPTTLPLT', 'HGEASWPA', 'PPPPPPPP', 'ECKDLIKS', 'NLSHGALR', 'LTTLPLTT', 'KGMHAVGQ', 'PPPASPSY', 'AALQSGGG', 'SSSSSSVS', 'IRESGQLV', 'YLTYLLLW', 'AATTTTTT', 'KDLIKFML', 'LEEEEEEA', 'PREEEEEE', 'LFHIDFGH', 'AVIRCPSS', 'LRLPLLLL', 'ISRPTTLP', 'EEEAAAGG', 'PPLPIALA', 'NLSHGTLR', 'MAGVIPIQ', 'THLREKLR', 'SSSFQPSP', 'PESGGGGG', 'EQELRWME', 'GQLFHIDF', 'RGPLGEAS', 'GACLLLLL', 'AGAAGSAA', 'AAAAGAAG', 'SRVLLLLL', 'TTVAATTT', 'VPPPPSPS', 'ALHHHHHT', 'EEEEAAAA', 'QPQQQQQP', 'TSPGPPAA', 'GGGKMGEN', 'EPREEEEE', 'EEEEGGGG', 'LDEYLTYL', 'RVVHGEDA', 'LAANNNNN', 'GGGGGCEE', 'AAPPPPPP', 'PPPIALAV', 'SEQGRETE']' died with <Signals.SIGILL: 4>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/lib/pipeline.py", line 373, in call_iedb
    lib.call_iedb.main(arguments)
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/lib/call_iedb.py", line 41, in main
    raise err
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/lib/call_iedb.py", line 36, in main
    (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/lib/prediction_class.py", line 327, in predict
    raise Exception("An error occurred while calling MHCflurry:\n{}".format(err))
Exception: An error occurred while calling MHCflurry:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/tools/pvacseq/run.py", line 122, in main
    pipeline.execute()
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/lib/pipeline.py", line 475, in execute
    self.call_iedb(chunks)
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/lib/pipeline.py", line 374, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/pvactools/lib/python3.6/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
Exception: An error occurred while calling MHCflurry:
```
I am not sure what the issues is. The script was running fine until recently.

regards

EL

**Comment by susannasiebert** [comment]
Newer versions of pip have a different way of resolving dependencies that has made installation very slow. You can try installing with the requirements.txt file here: https://raw.githubusercontent.com/griffithlab/pVACtools/staging/requirements.txt.
```
 pip install pvactools -r requirements.txt 
```
Please note that this file is for the upcoming pVACtools feature release so some packages might be missing but this should get you most of the way there.

Alternatively, using our docker container will alleviate a lot of these system-specific installation issues you are seeing.

**Comment by iichelhadi** [comment]
thank you. Unfortunately I already removed the old environment.

**Comment by iichelhadi** [comment]
Hi Susanna,
I am encountering the same issue again after running `pvacbind`. So I ran the following code
`mhcflurry-predict --alleles HLA-A*02:03 --out /tmp/tmpd856lbah --peptides SVWLLLPA MMSKQRET SMLDAVLG MLSTVGSF LQDVYSGV LSVWLLLP YMMSKQRE MLDAVLGV LSTVGSFL MSKQRETI VLQDVYSG RLSVWLLL`

This is the output I got
```
Forcing tensorflow backend.
Illegal instruction (core dumped)
```
These are the version of the packages I am using:
python                3.8.5
pvactools              2.0.4
mhcnuggets             2.3.3
mhcflurry              2.0.1
mhctools               1.8.1
tensorboard            2.2.2
tensorboard-plugin-wit 1.8.0
tensorflow             2.2.2
tensorflow-estimator   2.2.0

Any help would be greatly appreciated
thank you

**Comment by susannasiebert** [comment]
I think you might be running into the same issue as the one described [here](https://github.com/griffithlab/pVACtools/issues/351) where the newer (2.0 and above) version of tensorflow is incompatible with your computer hardware. You might want to attempt downgrading tensorflow to an older version. 1.5.0 has worked for other people in the past but I think other 1.x versions might also work. 

However, the newest version of MHCflurry does require tensorflow >=2.2.0 so I'm not sure if that simply downgrading tensorflow will work. It looks like MHCflurry 1.4 might've been the last version supporting that tensorflow version so you would need to jump to that version as well.

MHCnuggets doesn't pin a specific tensorflow version so you might be ok with either.

**Comment by iichelhadi** [comment]
> 

Thank you for the quick reply. The issues seems to be with HPC cluster and is being resolved.
