### ISSUE TITLE
Binding filter bug

### ISSUE THREAD

**Issue by shadihames** [griffithlab/pVACtools#837]
* pvactools version: 3.0.0
* Python version: 3.6.12
* Operating System: Linux

**Describe the bug**
pVACfuse filtering isn't working when running the tool. The <sample_name>.all_epitopes.tsv and <sample_name>.all_epitopes.aggregated.tsv files are output but the run fails when it hits the binding filter part. I can run pvacfuse top_score_filter with no issue, but I get the same error when I run pvacfuse binding_filter. 

**To Reproduce**
pvacfuse run /AGFusion/GRCh37/$sample $HLA_LIST NetMHC NetMHCpan PickPocket /pVACfuse/GRCh37/$sample --iedb-install-directory $DIR/1_Data/7_Refs --additional-report-columns sample_name --allele-specific-binding-thresholds -r 20 -t 2

**Log Output**
```
Traceback (most recent call last):
  File "/conda/envs/pvactools/bin/pvacfuse", line 8, in <module>
    sys.exit(main())
  File "/conda/envs/pvactools/lib/python3.6/site-packages/pvactools/tools/pvacfuse/main.py", line 94, in main
    args[0].func.main(args[1])
  File "/conda/envs/pvactools/lib/python3.6/site-packages/pvactools/tools/pvacfuse/run.py", line 231, in main
    create_net_class_report(output_files, all_epitopes_file, filtered_file, args, run_arguments)
  File "/3_Tools/conda/envs/pvactools/lib/python3.6/site-packages/pvactools/tools/pvacfuse/run.py", line 41, in create_net_class_report
    PostProcessor(**post_processing_params).execute()
  File "/3_Tools/conda/envs/pvactools/lib/python3.6/site-packages/pvactools/lib/post_processor.py", line 33, in execute
    self.execute_binding_filter()
  File "/3_Tools/conda/envs/pvactools/lib/python3.6/site-packages/pvactools/lib/post_processor.py", line 70, in execute_binding_filter
    self.file_type,
  File "/3_Tools/conda/envs/pvactools/lib/python3.6/site-packages/pvactools/lib/binding_filter.py", line 24, in execute
    AlleleSpecificBindingFilter(self.input_file, self.output_file, self.binding_threshold, self.minimum_fold_change, self.top_score_metric, self.exclude_nas, self.percentile_threshold, self.file_type).execute()
  File "/3_Tools/conda/envs/pvactools/lib/python3.6/site-packages/pvactools/lib/allele_specific_binding_filter.py", line 34, in execute
    score = float(entry['Median MT Score'])
KeyError: 'Median MT Score'
```

**Comment by shadihames** [comment]
@susannasiebert 
Hi, did the fix work? Just wanted to know before I try to update pvactools. Thanks!
