### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by biolxy** [griffithlab/pVACtools#839]
epitope prediction algorithms:  `MHCflurry NetMHC NetMHCcons NetMHCpan`

The program does not report an error when my input file is small, but when the file is large and has a large hlatype, it reports an error, is it because iedb denied me access?  Thanks for your reply !

```
An exception occured in thread 1: (<class 'requests.exceptions.ConnectionError'>, None: Max retries exceeded with url: /tools_api/mhci/ (Caused by None)).
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 116, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/run.py", line 131, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 473, in execute
    self.call_iedb(chunks)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 380, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/usr/local/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /tools_api/mhci/ (Caused by None)
```

**Comment by susannasiebert** [comment]
I believe you are right. For large requests we recommend using [the standalone IEDB installations](https://pvactools.readthedocs.io/en/latest/install.html#installing-iedb-binding-prediction-tools-strongly-recommended). These come pre-installed in our latest and latest-slim docker images.
