### ISSUE TITLE
Issue of pvacvector run with own data: KeyError: 'ETV3L.ENST00000671886.missense.35G/S'

### ISSUE THREAD

**Issue by QianhuiXu** [griffithlab/pVACtools#869]
pvactools version: 3.1.0
Python version:3.6
Operating System:Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-125-generic x86_64)

**Describe the bug**
Issue of pvacvector run with own VEP annotated vcf

**To Reproduce**
pvacvector run \
/home/shpc_100668/pvactool/hccpvacseq/112.filtered.tsv \
112 \
HLA-A*11:01,HLA-A*24:02,HLA-B*15:01,HLA-B*40:01,HLA-C*01:02,HLA-C*07:02 \
MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \
/home/shpc_100668/pvactool/hccpvacvectorout/ \
-e1 8,9,10,11,12 \
-v /home/shpc_100668/pvactool/hccpvacseq/111-112_filtered.mutect2.VEPout.vcf

**Log Output**
```
No MHC class II alleles chosen. Skipping MHC class II predictions.
Traceback (most recent call last):
  File "/home/shpc_100668/anaconda3/envs/pvactool/bin/pvacvector", line 8, in <module>
    sys.exit(main())
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/tools/pvacvector/main.py", line 50, in main
    args[0].func.main(args[1])
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/tools/pvacvector/run.py", line 455, in main
    generator.execute()
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/pvacvector_input_fasta_generator.py", line 89, in execute
    extracted_peptides = self.extract_peptide_sequences(transcripts_dict, epitopes)
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/pvacvector_input_fasta_generator.py", line 99, in extract_peptide_sequences
    full_sequence = transcript_dict[identifier]
KeyError: 'ETV3L.ENST00000671886.missense.35G/S'
```

**Output File**
None.

**Expected behavior**
I'm really at a loss as to how to proceed, and any guidance would be much appreciated!
Thank you for your kind help!

**Comment by susannasiebert** [comment]
Can you please confirm that the `112.filtered.tsv` file was generated from a pVACseq run that used `111-112_filtered.mutect2.VEPout.vcf` as the input file? pVACvector won't work otherwise or if the VCF file has been modified after running pVACseq. 

If this doesn't resolve your issue, please attach botch files to this ticket for further debugging.

**Comment by QianhuiXu** [comment]
Thank you for your swift reply and kind help!
The 112.filtered.tsv file was generated by others using pvacseq. I re-run pVACseq to get the new 112.filtered.tsv file and this problem has been solved. Thank you very much!
