### ISSUE TITLE
Issue of pvacseq run KeyError: 57

### ISSUE THREAD

**Issue by QianhuiXu** [griffithlab/pVACtools#873]
pvactools version: 3.1.0
Python version:3.6
Operating System:Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-125-generic x86_64)

**Describe the bug**
Issue of pvacseq run.

**To Reproduce**
pvacseq run /home/shpc_100668/pvactool/vepannotate/558-557_filtered.mutect2.VEPout.vcf 557 HLA-A*11:01,HLA-B*15:01,HLA-B*40:01,HLA-C*04:01 MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign /home/shpc_100668/pvactool/hccpvacseq/hcc557pvacseqoutput/ -e1 8,9,10,11,12 --n-threads 48.

**Log Output**
```
Parsing prediction file for Allele HLA-A*11:01 and Epitope Length 8 - Entries 401-600
Traceback (most recent call last):
  File "/home/shpc_100668/anaconda3/envs/pvactool/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/tools/pvacseq/main.py", line 116, in main
    args[0].func.main(args[1])
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/tools/pvacseq/run.py", line 132, in main
    pipeline.execute()
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/pipeline.py", line 474, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/pipeline.py", line 435, in parse_outputs
    parser.execute()
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/output_parser.py", line 438, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/output_parser.py", line 362, in process_input_iedb_file
    iedb_results = self.parse_iedb_file(tsv_entries)
  File "/home/shpc_100668/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/output_parser.py", line 584, in parse_iedb_file
    if protein_identifiers_from_label[protein_label] is not None:
KeyError: 57
```

**Output File**
557.tsv, 557.fasta and some tmp files..

**Expected behavior**
I'm really at a loss as to how to proceed, and any guidance would be much appreciated!
Thank you for your kind help!

**Comment by susannasiebert** [comment]
Can you try running on a new (empty) output directory and see if that fixes the issue?

**Comment by susannasiebert** [comment]
I assume that my suggestion fixed this issue so I will close it but do reopen it, if you're still running into this error.
