### ISSUE TITLE
IndexError from Running reference proteome similarity

### ISSUE THREAD

**Issue by nameOnStone** [griffithlab/pVACtools#969]
* pvactools version: 3.1.2 (lastest)
* Python version: 3.6
* Operating System: Centos

**Describe the bug**
`IndexError` came from function `calculate_reference_proteome_similarity.py`

**To Reproduce**
```
set +e && \
        source /work/duolin.wang/third_software/miniconda3/etc/profile.d/conda.sh
        conda activate tensorflow && \
        export PATH=/work/duolin.wang/third_software/miniconda3/envs/tensorflow/bin:$PATH && \
        export BLASTDB=/work/duolin.wang/db/blastdb && \
        pvacseq run \
        problem.vcf \
        T764504 \
        HLA-C*12:03,HLA-A*11:01,HLA-A*26:01,HLA-B*40:06,HLA-C*08:01,HLA-B*38:01,HLA-F*01:01,HLA-E*01:01,DPA1*02:01,DQA1*05:05,DRB9*01:01,HLA-E*01:03,DPB1*10:01,DRB2*01:01,DRB3*02:02,DPB1*14:01,DPA1*02:02,DRA*01:01,HLA-G*01:01,DQB1*03:01,DRB1*11:03,DRB1*11:01 \
        all \
        bug_pvactools \
        -e1 8,9,10,11 \
        -e2 12,13,14,15,16,17,18 \
        --iedb-install-directory /work/public/1.software/iedb \
        --normal-sample-name N764504 \
        --tdna-vaf 0.03 \
        -t 4  -c 1  -m median \
        --blastp-path /work/public/1.software/BLAST/ncbi-blast-2.13.0+/bin/blastp \
        --blastp-db refseq_select_prot \
        --run-reference-proteome-similarity
```

**Log Output**
```
Traceback (most recent call last):
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/tools/pvacseq/main.py", line 116, in main
    args[0].func.main(args[1])
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/tools/pvacseq/run.py", line 133, in main
    pipeline.execute()
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 466, in execute
    PostProcessor(**post_processing_params).execute()
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/lib/post_processor.py", line 39, in execute
    self.calculate_reference_proteome_similarity()
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/lib/post_processor.py", line 129, in calculate_reference_proteome_similarity
    CalculateReferenceProteomeSimilarity(
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/lib/calculate_reference_proteome_similarity.py", line 352, in execute
    unique_peptides = pymp.shared.list(self._get_unique_peptides(mt_records_dict, wt_records_dict))
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/lib/calculate_reference_proteome_similarity.py", line 336, in _get_unique_peptides
    _, full_peptide = self._get_peptide(line, mt_records_dict, wt_records_dict)
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/lib/calculate_reference_proteome_similarity.py", line 236, in _get_peptide
    peptide = self.extract_n_mer_from_fs(full_peptide, wt_records_dict[line['Index']], epitope, int(line['Sub-peptide Position']))
  File "/work/duolin.wang/third_software/miniconda3/envs/tensorflow/lib/python3.8/site-packages/pvactools/lib/calculate_reference_proteome_similarity.py", line 205, in extract_n_mer_from_fs
    diff_position = [i for i in range(len(wt_peptide)) if wt_peptide[i] != full_peptide[i]][0]
IndexError: list index out of range
```
[problem.vcf.gz](https://github.com/griffithlab/pVACtools/files/11526341/problem.vcf.gz)

**problem**
I can see where the bug came from this sentence `diff_position = [i for i in range(len(wt_peptide)) if wt_peptide[i] != full_peptide[i]][0]`, the reason is `wt_peptide` is fully part of `full_peptide`, so actullay `diff_position` is an empty list, SO it happend `IndexError`， but I don't know how to handle this situation，please help， thank you

**Comment by susannasiebert** [comment]
Hi @nameOnStone, thank you for the bug report. I just released a new version of pVACtools (3.1.3) that should fix this issue. Please give it a try and let me know if you're running into any problems.
