### ISSUE TITLE
KeyError: 'MHCflurry'

### ISSUE THREAD

**Issue by brycemash** [griffithlab/pVACtools#978]
* pvactools version: 3.1.1
* Python version: 3.6.13

**Describe the bug**
After the binding predictions complete, it is having problems parsing the files. 

...
Parsing prediction file for Allele H-2-Kb and Epitope Length 8 - Entries 1201-1290 - Completed
Parsing binding predictions for Allele H-2-Kb and Epitope Length 9 - Entries 1201-1290
Parsing prediction file for Allele H-2-Kb and Epitope Length 9 - Entries 1201-1290
Parsing prediction file for Allele H-2-Kb and Epitope Length 9 - Entries 1201-1290 - Completed
Parsing binding predictions for Allele H-2-Kb and Epitope Length 10 - Entries 1201-1290
Parsing prediction file for Allele H-2-Kb and Epitope Length 10 - Entries 1201-1290
Traceback (most recent call last):
  File "/broad/dunnlab/BLM/conda_libraries/pvactools_conda/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/broad/dunnlab/BLM/conda_libraries/pvactools_conda/lib/python3.6/site-packages/pvactools/tools/pvacseq/main.py", line 116, in main
    args[0].func.main(args[1])
  File "/broad/dunnlab/BLM/conda_libraries/pvactools_conda/lib/python3.6/site-packages/pvactools/tools/pvacseq/run.py", line 133, in main
    pipeline.execute()
  File "/broad/dunnlab/BLM/conda_libraries/pvactools_conda/lib/python3.6/site-packages/pvactools/lib/pipeline.py", line 434, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
  File "/broad/dunnlab/BLM/conda_libraries/pvactools_conda/lib/python3.6/site-packages/pvactools/lib/pipeline.py", line 395, in parse_outputs
    parser.execute()
  File "/broad/dunnlab/BLM/conda_libraries/pvactools_conda/lib/python3.6/site-packages/pvactools/lib/output_parser.py", line 438, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
  File "/broad/dunnlab/BLM/conda_libraries/pvactools_conda/lib/python3.6/site-packages/pvactools/lib/output_parser.py", line 363, in process_input_iedb_file
    iedb_results_with_metrics = self.add_summary_metrics(iedb_results)
  File "/broad/dunnlab/BLM/conda_libraries/pvactools_conda/lib/python3.6/site-packages/pvactools/lib/output_parser.py", line 311, in add_summary_metrics
    result['corresponding_wt_{}'.format(metric)] = result['wt_{}s'.format(metric)][best_mt_value_method]
KeyError: 'MHCflurry'

**To Reproduce**

vcf-genotype-annotator broad/dunnlab/BLM/pvac/Mutation/INDEL/Annotation/SR_NF.GATK.indel.mm10_multianno.vcf NF_indel 0/1 -o broad/dunnlab/BLM/pvac/Mutation/INDEL/Annotation/SR_NF.GATK.indel.mm10_multianno.gt.vcf

vep \
--input_file broad/dunnlab/BLM/pvac/Mutation/INDEL/Annotation/SR_NF.GATK.indel.mm10_multianno.gt.vcf \
--output_file broad/dunnlab/BLM/pvac/Mutation/INDEL/Annotation/SR_NF.GATK.indel.mm10_multianno.gt.vep.vcf \
--format vcf --vcf --symbol --terms SO --tsl \
--hgvs --fasta broad/dunnlab/BLM/pvac/usftp21.novogene.com/mm10.fa \
--offline --cache \
--dir_cache broad/dunnlab/BLM/pvac \
--plugin Frameshift --plugin Wildtype \
--dir_plugins /broad/dunnlab/BLM/pvac/VEP_plugins \
--species mus_musculus --cache_version 102

ref-transcript-mismatch-reporter broad/dunnlab/BLM/pvac/Mutation/INDEL/Annotation/SR_NF.GATK.indel.mm10_multianno.gt.vep.vcf \
--filter hard \
-o broad/dunnlab/BLM/pvac/Mutation/INDEL/Annotation/SR_NF.GATK.indel.mm10_multianno.gt.vep.filtered.vcf

pvacseq run \
broad/dunnlab/BLM/pvac/Mutation/INDEL/Annotation/SR_NF.GATK.indel.mm10_multianno.gt.vep.filtered.vcf \
NF_indel \
H-2-Kb,H-2-Db \
MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \
broad/dunnlab/BLM/pvac/output/NF_indel \
-e1 8,9,10 -e2 15

**Comment by brycemash** [comment]
Deleting the output folder and restarting the run worked.

**Comment by susannasiebert** [comment]
@brycemash I noticed you closed and then reopened this issue. Are you still running into errors?

**Comment by brycemash** [comment]
I was able to fix this by deleting the intermediate files that were causing inconsistencies, although it took a few deletions to complete.
