### ISSUE TITLE
MHCflurry error: TypeError: Descriptors cannot not be created directly

### ISSUE THREAD

**Issue by ysbioinfo** [griffithlab/pVACtools#979]
* pvactools version:
* 3.0.4
* Python version:
* 3.8.13
* Operating System:
CentOS 7

**Describe the bug**
I run pvacseq on a VCF file, enabling both NetMHCpan and MHCflurry prediction. But it throws out an error.
**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.
```
pvacseq run P007020_004T.vcf \
                    P007020_004T \
                    HLA-A*02:01,HLA-A*03:01,HLA-B*35:01,HLA-B*35:01,HLA-C*03:02,HLA-C*04:01 \
                    NetMHCpan NetMHCIIpan MHCflurry' \
                    out \
                    -e1 8,9,10,11 \
                    --netmhc-stab
```
**Log Output**
```
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /mnt/efs/NGS/yangshi/A317_306_WES/pvac_out/P007020_004T/MHC
_Class_I/tmp/P007020_004T.MHCflurry.HLA-A*02:01.8.tsv_1-200
CRITICAL:pymp:An exception occured in thread 0: (<class 'Exception'>, An error occurred while calling MHCflurry:
Traceback (most recent call last):
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/bin/mhcflurry-predict", line 8, in <module>
    sys.exit(run())
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/mhcflurry/predict_command.py", line 204, in run
    predictor = Class1PresentationPredictor.load(models_dir)
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/mhcflurry/class1_presentation_predictor.py", line 956, in load
    affinity_predictor = Class1AffinityPredictor.load(
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/mhcflurry/class1_affinity_predictor.py", line 549, in load
    optimized = result.optimize()
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/mhcflurry/class1_affinity_predictor.py", line 594, in optimize
    Class1NeuralNetwork.merge(
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/mhcflurry/class1_neural_network.py", line 1107, in merge
    configure_tensorflow()
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/mhcflurry/common.py", line 62, in configure_tensorflow
    import tensorflow
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.

**Expected behavior**

**Comment by susannasiebert** [comment]
Hi @ysbioinfo,

Thank you for your interest in pVACtools and I apologize that you're running into errors using our software. Is this from a standalone installation of pVACtools or are you using the Docker container? If this is a standalone installation, please try downgrading the protobuf package to 3.20.x or lower (`pip install protofbuf 3.20.0`), as suggested in the error message from the stacktrace you posted.

Also, I would suggest upgrading to our latest version (3.1.3) to ensure that you get the latest features and bugfixes.

**Comment by ysbioinfo** [comment]
Thanks! It works!
