### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by dlgoode** [griffithlab/pVACtools#994]
### Installation Type

Docker

### pVACtools Version / Docker Image

4.0.0 - running via Singularity (v3.7.3)

### Describe the bug

Running pVACtools using Singularity on a CentOS Linux 7 HPC at work.  (Docker not permitted)

Keep running into 
`'TypeError: argument of type 'NoneType' is not iterable'` for a particular allele, epitope length and entry chunk combination. (HLA-A*03:01, 9, 1001-1200)

Based on similar reports of KeyErrors [#970 ](https://github.com/griffithlab/pVACtools/issues/970) I tried erasing the corresponding files in tmp/ dir but pVACseq regenerates the files and bug re-occurs.

Tried excluding the offending allele but get another, similar bug from a different  allele, epitope length and entry chunk combo:
```
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 764, in parse_iedb_file
    if protein_identifiers_from_label[protein_label] is not None:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 62
```

I'm new to pVACtools and epitope prediction in general. Seems like it must be an issue with my input but I'm not sure where to start looking or what to look for. Or could be a problem with running pVACtools via Singularity.

Thanks for your help.

### How to reproduce this bug

```Shell
singularity run \
--bind /scratch/users/dgoode/:/scratch/  \
/config/binaries/singularity/containers/pvactools/4.0.0/pvactools.sif  \
pvacseq run /pVACTools_CWL/VCFs/224_IN_SomMutns_hg38_wVEP_Tx_all.vcf 224  \
HLA-A*11:01,HLA-A*03:01,HLA-B*55:01,HLA-B*44:03,HLA-C*03:03,HLA-C*16:01 \
all \ 
/pVACTools_CWL/224_pVACseq_predictions \
-e1 9,10 -e2 15 \
--normal-sample-name 34 \
--pass-only
```

### Log output

```
Parsing binding predictions for Allele HLA-A*03:01 and Epitope Length 9 - Entries 1001-1200
Parsing prediction file for Allele HLA-A*03:01 and Epitope Length 9 - Entries 1001-1200
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.11/site-packages/pvactools/tools/pvacseq/run.py", line 138, in main
    pipeline.execute()
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/pipeline.py", line 452, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/pipeline.py", line 413, in parse_outputs
    parser.execute()
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 626, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 511, in process_input_iedb_file
    iedb_results = self.parse_iedb_file(tsv_entries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 797, in parse_iedb_file
    return self.match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 403, in match_wildtype_and_mutant_entries
    self.match_wildtype_and_mutant_entry_for_inframe_indel(result, mt_position, wt_results, previous_result, iedb_results_for_wt_iedb_result_key)
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 310, in match_wildtype_and_mutant_entry_for_inframe_indel
    result['mutation_position'] = self.determine_ins_mut_position_from_previous_result(previous_result, mt_epitope_seq, result)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 77, in determine_ins_mut_position_from_previous_result
    previous_mutation_position = self.position_to_tuple(previous_result['mutation_position'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 180, in position_to_tuple
    elif '-' in mut_pos:
         ^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by susannasiebert** [comment]
Hi @dlgoode,
Thank you for your interest in pVACtools and for reporting this bug. There are a couple of different issues going on.
(1) For the protein_identifiers_from_label[protein_label] error, we have been noticing that the IEDB API sometimes returns results that don't match the request. This results in the error you noticed first. We have filed a bug report with them but that issue is still being investigated. In the meantime we recommend switching to the standalone IEDB by either installing that software locally or making use of the IEDB installations that come with our Docker containers via the `--iedb-install-directory /opt/iedb` parameter
(2) For the second error, I think this will be fixed with the change in PR https://github.com/griffithlab/pVACtools/pull/985, which will be released soon (targeting early next week).

**Comment by dlgoode** [comment]
Thank you for your prompt attention on this. 

Indeed using --iedb-install-directory /opt/iedb fixed the first problem but the second error remains. 

Please do let me know when your new release comes out. I'm on a tight timeframe a grant application.

**Comment by losuler** [comment]
Just providing an update to say that I've been working with @dlgoode to get this working (using the same environment), and I built a new Docker image from the 4.0.0 branch of griffithlab/docker-pvactools[^1], using the hotfix branch from this repo[^2]:

```diff
--- a/Dockerfile
+++ b/Dockerfile
@@ -48,7 +48,7 @@ RUN rm IEDB_MHC_II-3.1.8.tar.gz
 #pVACtools 4.0.0
 RUN mkdir /opt/mhcflurry_data
 ENV MHCFLURRY_DATA_DIR=/opt/mhcflurry_data
-RUN pip install pvactools==4.0.0
+RUN pip install git+https://github.com/griffithlab/pVACtools@hotfix
 RUN mhcflurry-downloads fetch
 
 CMD ["/bin/bash"]
 ```
 
However, running the same command as @dlgoode, I got a different error this time:

```
Parsing binding predictions for Allele HLA-A*03:01 and Epitope Length 9 - Entries 601-800
Parsing prediction file for Allele HLA-A*03:01 and Epitope Length 9 - Entries 601-800
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.11/site-packages/pvactools/tools/pvacseq/run.py", line 138, in main
    pipeline.execute()
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/pipeline.py", line 452, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/pipeline.py", line 413, in parse_outputs
    parser.execute()
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 629, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 514, in process_input_iedb_file
    iedb_results = self.parse_iedb_file(tsv_entries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 800, in parse_iedb_file
    return self.match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 406, in match_wildtype_and_mutant_entries
    self.match_wildtype_and_mutant_entry_for_inframe_indel(result, mt_position, wt_results, previous_result, iedb_results_for_wt_iedb_result_key)
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 313, in match_wildtype_and_mutant_entry_for_inframe_indel
    result['mutation_position'] = previous_result['mutation_position'] - 1
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

 [^1]: https://github.com/griffithlab/docker-pvactools/tree/4.0.0
 [^2]: https://github.com/griffithlab/pVACtools/tree/hotfix

**Comment by susannasiebert** [comment]
Would you be able to share your input VCF and/or your pVACseq output files with us? I'm not sure I will be able to fix this error without being able to reproduce it.

**Comment by susannasiebert** [comment]
I think I was able to determine the source of your error but I wasn't able to confirm the fix since I didn't have any data to reproduce this edge case. I made a PR from the `mutation_position` branch. You should be able to build a docker container off of it by replacing `hotfix` in your pip install with `mutation_position`. I would appreciate if you could give it a try and let me know if that fixes your error.

**Comment by dlgoode** [comment]
Thanks for making the fix but it appears we're still getting the same error. @losuler will be in touch with more details.

I have uploaded the input VCF that we used to a private repo that I have just invited you to join. I hope that it will be helpful.

**Comment by losuler** [comment]
Looks to be very similar, however, with a few differences compared to the original error @dlgoode posted:

```
Parsing binding predictions for Allele HLA-A*03:01 and Epitope Length 10 - Entries 1001-1200
Parsing prediction file for Allele HLA-A*03:01 and Epitope Length 10 - Entries 1001-1200
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.11/site-packages/pvactools/tools/pvacseq/run.py", line 138, in main
    pipeline.execute()
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/pipeline.py", line 452, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/pipeline.py", line 413, in parse_outputs
    parser.execute()
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 629, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 514, in process_input_iedb_file
    iedb_results = self.parse_iedb_file(tsv_entries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 800, in parse_iedb_file
    return self.match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 403, in match_wildtype_and_mutant_entries
    self.match_wildtype_and_mutant_entry_for_frameshift(result, mt_position, wt_results, previous_result)
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 232, in match_wildtype_and_mutant_entry_for_frameshift
    previous_mutation_position = self.position_to_tuple(previous_result['mutation_position'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvactools/lib/output_parser.py", line 180, in position_to_tuple
    elif '-' in mut_pos:
         ^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

These appear to be the notable differences between @dlgoode's original error log and now this one:

```diff
30d27
<     result['mutation_position'] = self.determine_ins_mut_position_from_previous_result(previous_result, mt_epitope_seq, result)
32c29
<     self.match_wildtype_and_mutant_entry_for_inframe_indel(result, mt_position, wt_results, previous_result, iedb_results_for_wt_iedb_result_key)
---
>     self.match_wildtype_and_mutant_entry_for_frameshift(result, mt_position, wt_results, previous_result)
36c33
< TypeError: argument of type 'NoneType' is not iterable
---
> TypeError: argument of type 'int' is not iterable
```

**Comment by erdikilic** [comment]
I am getting this error, any updates? I can share our VCF file for fast debugging.

**Comment by susannasiebert** [comment]
@erdikilic I would appreciate the VCF file since I don't have an example to reproduce this on my end. Can you please attach it to this issue?

**Comment by erdikilic** [comment]
@susannasiebert Still needed? I can sent it via email.

**Comment by susannasiebert** [comment]
I would definitely appreciate the second test case. You can either send it to help@pvactools.org (which is public mailing list) or to susanna.kiwala@wustl.edu if it needs to be kept confidential.

**Comment by susannasiebert** [comment]
@dlgoode @losuler I pushed a couple of additional commits. With those changes I was able to get run your VCF to completion (on just one allele and prediction algorithm). Please give it another try and let me know if that fixes these issues for you.

**Comment by erdikilic** [comment]
@susannasiebert Will you update docker images on Docker Hub if the problem was solved?

**Comment by susannasiebert** [comment]
Once I make a bugfix release (4.0.1) I will also make matching Docker images.

**Comment by dlgoode** [comment]
Thanks very much for the new commits @susannasiebert 

We'll test them out and let you know how it goes.

**Comment by susannasiebert** [comment]
That's great news. I made a new release (4.0.1) with this fix as well.
